import test from 'node:test';import assert from 'node:assert/strict';import {Store,hash} from '../server/store.mjs';import {CountForecasts} from '../server/count-forecasts.mjs';import {CountSchedules} from '../server/count-schedules.mjs';
test('registered count schedules issue once, recover durable forecasts, and retain missed and stopped slots',async t=>{
 let now=Date.UTC(2030,0,1);t.mock.method(Date,'now',()=>now);const store=new Store(':memory:'),snapshot=store.snapshot([],now,'fixture'),cells=Array(72).fill(.5),parent={id:'parent',version:'equal-area-weekly-gnn-0.2.1',artifact:{weights:[1]},weightsSha256:hash({weights:[1]})};
 const learned={get:()=>parent,tectonic:()=>({id:'tectonic',createdAt:now-1,report:{fit:{cells}}}),predict:async()=>({report:{grid:{rows:6,columns:12},weightsSha256:parent.weightsSha256},projection:{cells,componentCells:Object.fromEntries(['graph','noNeighbors','trainingMean','recentRate'].map(n=>[n,cells])),inputSnapshotId:snapshot}})},counts=new CountForecasts(store,learned),schedules=new CountSchedules(store,counts),feed=()=>({status:'live',fetchedAt:now,generated:now}),input=()=>({name:'Registered fixture',parentRunId:'parent',start:new Date(now+180000).toISOString(),issuances:2,stepDays:7}),register=()=>{const i=input(),p=schedules.preview(i);return schedules.register({...i,previewHash:p.previewHash});};
 try{
  assert.throws(()=>schedules.preview({...input(),stepDays:1}),/Choose/);const i=input(),p=schedules.preview(i);assert.throws(()=>schedules.register({...i,name:'changed',previewHash:p.previewHash}),/changed/);const plan=schedules.register({...i,previewHash:p.previewHash});assert.equal(schedules.register({...i,previewHash:p.previewHash}).id,plan.id);
  assert.equal((await schedules.tick(feed())).changes,0);now=plan.spec.start;
  store.db.exec("CREATE TRIGGER fixture_slot_fail BEFORE INSERT ON count_plan_slots BEGIN SELECT RAISE(ABORT,'fixture failure'); END;");await schedules.tick(feed());assert.equal(counts.list().length,1);assert.equal(schedules.get(plan.id).slots.length,0);store.db.exec('DROP TRIGGER fixture_slot_fail');await schedules.tick(feed());assert.equal(counts.list().length,1);assert.equal(schedules.get(plan.id).slots[0].status,'ISSUED');
  schedules.stop(plan.id);await schedules.tick(feed());assert.equal(schedules.get(plan.id).slots.find(s=>s.ordinal===1).status,'CANCELLED');
  const missed=register();now=missed.spec.start+300001;await schedules.tick(feed());assert.equal(schedules.get(missed.id).slots[0].status,'MISSED_WINDOW');
  const stopping=register(),predict=learned.predict;let release;learned.predict=(...args)=>new Promise(resolve=>{release=async()=>resolve(await predict(...args));});now=stopping.spec.start;const pending=schedules.tick(feed());assert.ok(release);schedules.stop(stopping.id);await release();await pending;assert.equal(counts.list().length,1);await schedules.tick(feed());assert.equal(schedules.get(stopping.id).slots.find(s=>s.ordinal===0).status,'CANCELLED');learned.predict=predict;
  const version=register();now=version.spec.start;schedules.runtimeHash='changed';await schedules.tick(feed());assert.equal(schedules.get(version.id).slots[0].status,'SKIPPED_VERSION');
  const issued=store.db.prepare('SELECT body FROM count_forecasts LIMIT 1').get(),changedForecast=JSON.parse(issued.body);changedForecast.weightsSha256='wrong-weights';const changedId=hash(changedForecast);store.db.prepare('INSERT INTO count_forecasts VALUES(?,?,?)').run(changedId,changedForecast.issuedAt,JSON.stringify(changedForecast));const slot=JSON.parse(store.db.prepare('SELECT body FROM count_plan_slots WHERE plan_id=? AND ordinal=0').get(plan.id).body);slot.forecastId=changedId;store.db.exec('DROP TRIGGER frozen_count_plan_slots_UPDATE');store.db.prepare('UPDATE count_plan_slots SET id=?,body=? WHERE plan_id=? AND ordinal=0').run(hash(slot),JSON.stringify(slot),plan.id);assert.throws(()=>schedules.get(plan.id),/registered slot/);
  assert.throws(()=>store.db.exec('DELETE FROM count_plans'),/immutable/);assert.throws(()=>store.db.exec('DELETE FROM count_plan_slots'),/immutable/);
 }finally{store.close();}
});
