import test from 'node:test';import assert from 'node:assert/strict';import {spawn,execFileSync} from 'node:child_process';import {mkdtempSync,writeFileSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {Store,hash} from '../server/store.mjs';import {LearnedModel} from '../server/learned.mjs';
test('count schedule HTTP registration survives server restart and exports verifiable evidence',async()=>{
 const dir=mkdtempSync(path.join(os.tmpdir(),'count-api-')),file=path.join(dir,'test.sqlite'),store=new Store(file),learned=new LearnedModel(store),events=[{id:'a',type:'earthquake',mag:5,lat:0,lon:179,time:1},{id:'b',type:'earthquake',mag:5,lat:0,lon:-179,time:2}],snapshot=store.snapshot(events,30,'fixture'),artifact={weights:[1]};
 const parent={id:'fixture',version:'equal-area-weekly-gnn-0.2.1',createdAt:1,artifact,weightsSha256:hash(artifact),inputSnapshotId:snapshot,options:{minMagnitude:5,validationEnd:20},scores:{train:{firstCutoff:0,lastEnd:10,windows:1,models:{graph:{events:2}}},test:{firstCutoff:20,lastEnd:30,models:{graph:{logLikelihood:-72}}}},testWindows:[{cutoff:20,end:30,observed:Array(72).fill(0),graph:Array(72).fill(1)}]};store.db.prepare('INSERT INTO learned_runs VALUES(?,?,?)').run(parent.id,1,JSON.stringify(parent));learned.close();store.close();
 const listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));const root=`http://127.0.0.1:${port}`;let child;
 const start=async()=>{child=spawn(process.execPath,['server/index.mjs'],{windowsHide:true,env:{...process.env,PORT:String(port),SEISMO_DB:file,SEISMO_TEST_MODE:'1'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Test server startup timeout')),10000);child.stdout.on('data',b=>{if(String(b).includes('SeismoSphere running')){clearTimeout(timer);resolve();}});child.on('error',reject);});};
 const stop=async()=>{if(child&&child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}},post=(route,body,headers={})=>fetch(root+route,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
 try{await start();const input={name:'HTTP fixture',parentRunId:'fixture',start:new Date(Date.now()+86400000).toISOString(),issuances:2,stepDays:7},preview=await(await post('/api/count-schedule-preview',input)).json();assert.ok(preview.previewHash);const request={...input,previewHash:preview.previewHash};assert.equal((await post('/api/count-schedule-register',request,{Origin:'https://foreign.example'})).status,403);assert.equal((await post('/api/count-schedule-register',{...request,name:'changed'})).status,400);const p=await(await post('/api/count-schedule-register',request)).json();assert.equal(p.id,preview.previewHash);assert.equal((await(await post('/api/count-schedule-register',request)).json()).id,p.id);await stop();await start();const list=await(await fetch(root+'/api/count-schedules')).json();assert.equal(list.plans.length,1);assert.equal(list.plans[0].id,p.id);assert.equal(list.plans[0].registeredAt,p.registeredAt);await post('/api/count-schedule-stop',{id:p.id});const exported=await(await fetch(root+'/api/count-schedule-export?id='+p.id)).json();assert.equal(exported.stopped,true);assert.equal(exported.forecasts.length,0);const out=path.join(dir,'export.json');writeFileSync(out,JSON.stringify(exported));assert.match(execFileSync(process.execPath,['scripts/reproduce-count-schedule.mjs',out],{encoding:'utf8'}),/PASS/);
 }finally{await stop();}
});
