import {waveformRuns} from '../public/spectrum-data.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {Store,hash} from '../server/store.mjs';
import {Instruments} from '../server/instruments.mjs';
import {PhaseAnalysis,phasePicks} from '../server/phase.mjs';
import {instrumentResponse} from '../server/response.mjs';
import {commandActions,chat} from '../server/ai.mjs';
test('reference travel times retain branches and supported models without interpreting them as detections',async()=>{
 const input={model:'iasp91',phases:['P','S','PP'],event:{lat:0,lon:0,depth:10},station:{lat:0,lon:50}},a=await instrumentResponse(input,'phase');assert.equal(a.distanceDegrees,50);assert.ok(Math.abs(a.arrivals.find(a=>a.phase==='P').timeSeconds-534.4)<.2);assert.ok(Math.abs(a.arrivals.find(a=>a.phase==='S').timeSeconds-965.1)<1);assert.ok(a.arrivals.filter(a=>a.phase==='PP').length>1);assert.match(a.implementation.modelSha256,/^[a-f0-9]{64}$/);const b=await instrumentResponse({...input,model:'ak135'},'phase');assert.notEqual(a.arrivals[0].timeSeconds,b.arrivals[0].timeSeconds);assert.equal(b.receiverDepthKm,0);await assert.rejects(instrumentResponse({...input,event:{...input.event,depth:-1}},'phase'),/depth/);await assert.rejects(instrumentResponse({...input,phases:['garbage']},'phase'),/supported phases/);
});
test('phase records preserve catalog revisions, exact samples and manual residuals with immutable parent history and cutoff isolation',async()=>{
 const store=new Store(':memory:'),instruments=new Instruments(store),phases=new PhaseAnalysis(instruments),now=Date.now(),start=now-86400000,station={network:'XX',station:'TEST',channel:'BHZ',location:'',lat:0,lon:50,sampleRateHz:10},raw='synthetic software test',body={kind:'waveform',createdAt:now-10000,query:{start,end:start+120000},station,segments:[{metadata:{},sampleRateHz:10,samples:Array.from({length:1200},(_,i)=>[start*1000+i*100000,Math.sin(i)])}],summary:{samples:1200,segments:1,gapTransitions:0,overlapTransitions:0,units:'digital counts'},receipt:{fetchedAt:now-10000,sha256:hash(raw)},raw,provenance:{policy:'Synthetic test'}},wave={...body,id:hash(body)};store.db.prepare('INSERT INTO instrument_records VALUES(?,?,?,?,?)').run(wave.id,'waveform',wave.createdAt,hash(wave.query),JSON.stringify(wave));
 const event={id:'synthetic-source',provider:'USGS',type:'earthquake',time:start-534299,updated:start,lat:0,lon:0,depth:10,mag:5,place:'Synthetic'},input={waveformId:wave.id,eventId:event.id,model:'iasp91',phases:['P','S'],asOf:now,mode:'strict'};store.ingest([event],now-5000);assert.equal(phases.events(input).events.length,1);const result=await phases.calculate(input);assert.equal(result.arrivals.length,2);assert.equal(result.event.observedAt,now-5000);assert.equal((await phases.calculate({...input,asOf:Date.now()})).id,result.id);assert.throws(()=>phases.context(result,result.createdAt-1,'strict'),/unavailable/);assert.throws(()=>phases.context(result,start-1,'catalog-replay'),/ends after/);
 const pick={segmentIndex:0,sampleIndex:50,arrivalIndex:0,uncertaintySeconds:.2,polarity:'unclear'},saved=phases.annotate({phaseId:result.id,picks:[pick],asOf:Date.now(),mode:'strict'});assert.equal(saved.parentId,result.id);assert.equal(saved.picks[0].timeUs,wave.segments[0].samples[50][0]);assert.equal(saved.picks[0].residualSeconds,(saved.picks[0].timeUs-result.arrivals[0].timeUs)/1e6);assert.equal(instruments.get(result.id).picks.length,0);assert.equal(phases.annotate({phaseId:result.id,picks:[pick],asOf:Date.now()}).id,saved.id);assert.throws(()=>phasePicks(wave,result.arrivals,[{...pick,sampleIndex:1200}]),/exact saved sample/);assert.throws(()=>phasePicks(wave,result.arrivals,[{...pick,uncertaintySeconds:0}]),/uncertainty/);assert.throws(()=>store.db.prepare('UPDATE instrument_records SET body=? WHERE id=?').run('{}',saved.id),/immutable/);store.ingest([{...event,depth:20,updated:Date.now()}]);assert.equal(instruments.get(saved.id).event.depth,10);const context={phaseEvidence:phases.context(saved,Date.now(),'catalog-replay')};assert.deepEqual(commandActions('Explain the global source and show deep earthquakes',context),[]);const answer=await chat('Explain',context,{aiProvider:'deterministic'});assert.deepEqual(answer.actions,[]);assert.match(answer.answer,/1 manual picks/);assert.match(answer.answer,/positive means later/);store.db.close();
});

test('phase timing can use short exact runs across contiguous blocks without bridging gaps',()=>{
 const source={segments:[{sampleRateHz:10,samples:[[0,1],[100000,2]]},{sampleRateHz:10,samples:[[200000,3],[300000,4]]},{sampleRateHz:10,samples:[[500000,5]]}]};
 const runs=waveformRuns(source,true,1);assert.equal(runs.length,2);assert.equal(runs[0].samples,4);assert.equal(runs[0].endUs,300000);assert.equal(runs[1].startUs,500000);assert.equal(waveformRuns(source,true).length,0);
});
