import {commandActions,chat} from '../server/ai.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Store,hash} from '../server/store.mjs';
import {ProspectiveExperiments,prospectiveContext} from '../server/prospective.mjs';
import {DAY} from '../server/geo.mjs';
const config=JSON.parse(readFileSync(new URL('../config/default.json',import.meta.url))),routes={version:'test-routes',status:'illustrative',routes:[]};
test('registered prospective schedule atomically issues frozen comparisons, preserves omissions and scores only its fixed outcome snapshot',t=>{
 let now=Date.UTC(2030,0,1);t.mock.method(Date,'now',()=>now);const store=new Store(':memory:'),service=new ProspectiveExperiments(store),feed=()=>({status:'live',fetchedAt:now,generated:now,url:'retained fixture feed'}),options=name=>({name,hypothesis:'DS full-hit fraction exceeds matched recent-rate.',start:now+180000,issuances:2,stepDays:1,settleDays:1}),register=(input=options('Frozen comparison'))=>{const preview=service.preview(input,config,routes,[]);return service.register({...input,previewHash:preview.previewHash},config,routes,[]);};
 try{store.ingest([{id:'USGS:a',provider:'USGS',time:now-3600000,lat:0,lon:-10,mag:5,depth:10,magType:'mw',type:'earthquake'},{id:'USGS:b',provider:'USGS',time:now-3600000,lat:0,lon:10,mag:5,depth:10,magType:'mw',type:'earthquake'}],now-1000);const input=options('Frozen comparison'),p=register(input),before=service.view(p.id);assert.equal(before.summary.state,'SCHEDULED');assert.equal(before.summary.primaryDsMinusRecent,null);assert.equal(service.register({...input,previewHash:hash(p.spec)},{...config,radiusKm:999},routes,[]).id,p.id,'Registration retry must not schedule a duplicate');assert.equal(service.tick(feed()).changes,0);now=p.spec.start+1000;
  // A failed slot write must roll back the source snapshot and the whole forecast batch.
  store.db.exec("CREATE TRIGGER fixture_slot_failure BEFORE INSERT ON prospective_slots BEGIN SELECT RAISE(ABORT,'controlled slot failure'); END;");assert.throws(()=>service.tick(feed()),/controlled slot failure/);assert.equal(store.ledger().length,0);assert.equal(store.db.prepare('SELECT count(*) AS n FROM snapshots').get().n,0);store.db.exec('DROP TRIGGER fixture_slot_failure');assert.equal(service.tick(feed()).changes,1);const issued=service.view(p.id),slot=issued.slots[0],forecasts=store.ledger();assert.equal(forecasts.length,3);assert.equal(slot.status,'ISSUED');assert.equal(new Set(forecasts.map(f=>f.engine)).size,3);for(const f of forecasts){assert.equal(f.mode,'prospective');assert.equal(f.validFrom,now);assert.equal(f.issuedAt,now);assert.equal(f.config.radiusKm,400);assert.equal(f.protocolId,p.id);}assert.equal(service.tick(feed()).changes,0);
  service.stop(p.id);assert.equal(service.view(p.id).slots[1].status,'CANCELLED');assert.equal(service.view(p.id).summary.state,'STOPPED · ASSESSING');const ds=forecasts.find(f=>f.engine==='DS'),outcome={id:'USGS:outcome',provider:'USGS',time:ds.validFrom+DAY,lat:ds.center.lat,lon:ds.center.lon,mag:ds.magnitude.central,depth:12,type:'earthquake',magType:'mw'};now=slot.assessmentDueAt+1000;store.ingest([outcome],now-1000);store.set('coverage',[{provider:'USGS',start:0,end:now,minMagnitude:-3}]);assert.equal(service.tick(feed()).changes,1);let view=service.view(p.id);assert.equal(view.summary.completeGroups,1);assert.equal(view.summary.primaryDsMinusRecent,1);assert.equal(view.summary.secondaryDsMinusNull,1);assert.equal(view.summary.state,'CANCELLED');assert.equal(service.verify(p.id).valid,true);const frozen=JSON.stringify(view.assessments);now+=DAY;store.ingest([{...outcome,status:'deleted',updated:now}],now);service.tick(feed());assert.equal(JSON.stringify(service.view(p.id).assessments),frozen,'Later catalog changes must not rewrite the protocol assessment');assert.throws(()=>prospectiveContext(view,slot.recordedAt),/unavailable/);const evidence=prospectiveContext(view,now);assert.equal(evidence.summary.primaryDsMinusRecent,1);assert.equal(evidence.config.aiProvider,undefined);assert.equal(evidence.snapshots,undefined);const exported=service.export(p.id);assert.equal(exported.forecasts.length,3);assert.equal(exported.snapshots.length,2);assert.ok(exported.protocol.spec.implementation.sourceFiles['server/engine.mjs']);
  const stale=register({...options('Missed feed'),issuances:1});now=stale.spec.start+1000;assert.equal(service.tick({status:'stale'}).changes,0);now+=300000;service.tick(feed());assert.equal(service.view(stale.id).slots[0].status,'MISSED_WINDOW');assert.equal(service.view(stale.id).summary.primaryDsMinusRecent,null);
  const changed=register({...options('Changed implementation'),issuances:1});now=changed.spec.start+1;const original=service.runtimeHash;service.runtimeHash='changed';service.tick(feed());assert.equal(service.view(changed.id).slots[0].status,'SKIPPED_VERSION');service.runtimeHash=original;
  for(const table of ['prospective_protocols','prospective_slots','prospective_assessments','prospective_stops'])assert.throws(()=>store.db.exec(`DELETE FROM ${table}`),/immutable/);assert.equal(store.verify().valid,true);
 }finally{store.close();}
});
test('prospective missing and incomplete assessments remain excluded without retrospective replacement',t=>{
 let now=Date.UTC(2031,0,1);t.mock.method(Date,'now',()=>now);const store=new Store(':memory:'),service=new ProspectiveExperiments(store),feed=()=>({status:'live',fetchedAt:now,generated:now});try{store.ingest([{id:'a',time:now-1000,lat:0,lon:-10,mag:5,depth:10,type:'earthquake'},{id:'b',time:now-1000,lat:0,lon:10,mag:5,depth:10,type:'earthquake'}],now-1);const input={name:'Incomplete outcomes',hypothesis:'Predeclared comparison',start:now+180000,issuances:2,stepDays:1,settleDays:1},preview=service.preview(input,config,routes,[]),p=service.register({...input,previewHash:preview.previewHash},config,routes,[]);now=p.spec.start;service.tick(feed());now+=DAY;service.tick(feed());const slots=service.view(p.id).slots;now=slots[0].assessmentDueAt+1;service.tick(feed());let v=service.view(p.id);assert.equal(v.assessments[0].status,'SCORED');assert.equal(v.assessments[0].complete,false);assert.ok(v.assessments[0].metrics.every(m=>m.ambiguous===m.forecasts));now=slots[1].assessmentDueAt+300001;service.tick(feed());v=service.view(p.id);assert.equal(v.assessments[1].status,'MISSED_ASSESSMENT');assert.equal(v.summary.completeGroups,0);assert.equal(v.summary.incompleteGroups,2);assert.equal(v.summary.primaryDsMinusRecent,null);assert.equal(v.summary.state,'COMPLETE');assert.equal(service.verify(p.id).valid,true);
 }finally{store.close();}
});

test('prospective explanation context suppresses all ordinary command actions',()=>{assert.deepEqual(commandActions('Explain the global experiment and show forecasts, research and deep earthquakes',{prospectiveExperiment:{}}),[]);assert.ok(commandActions('Explain the global experiment').includes('explain'));});

test('prospective AI withholds a changed primary result and preserves completed scores after stopping',async t=>{
 const summary={primaryDsMinusRecent:1,state:'CANCELLED'},context={prospectiveExperiment:{summary}},config={aiProvider:'ollama',localModel:'fixture'};
 let answer='The primary contrast is unavailable because the experiment stopped.';
 t.mock.method(globalThis,'fetch',async()=>({ok:true,json:async()=>({message:{content:JSON.stringify({answer,actions:['global']})}})}));
 await assert.rejects(chat('Explain the global experiment',context,config),/did not preserve.*primary result/);
 answer='Primary DS-minus-Recent-rate contrast: 100.00 percentage points.';
 assert.deepEqual((await chat('Explain the global experiment',context,config)).actions,[]);
 summary.primaryDsMinusRecent=null;
 await assert.rejects(chat('Explain',context,config),/did not preserve.*primary result/);
 answer='Primary DS-minus-Recent-rate contrast: unavailable because there are no completely assessed groups.';
 assert.deepEqual((await chat('Explain',context,config)).actions,[]);
});
