import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import {prospectiveFixture} from '../scripts/prospective-fixture.mjs';
test('prospective HTTP review/register is idempotent, exposes frozen assessments and rejects stale previews and foreign writes',async()=>{
 const directory=mkdtempSync(path.join(os.tmpdir(),'seismo-protocol-api-')),file=path.join(directory,'test.sqlite'),fixture=prospectiveFixture(file),listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));const root=`http://127.0.0.1:${port}`,child=spawn(process.execPath,['server/index.mjs'],{windowsHide:true,env:{...process.env,PORT:String(port),SEISMO_DB:file,SEISMO_TEST_MODE:'1'},stdio:['ignore','pipe','pipe']});
 try{await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Protocol test server did not start')),10000);child.stdout.on('data',data=>{if(String(data).includes('SeismoSphere running')){clearTimeout(timeout);resolve();}});child.on('error',reject);});const post=(route,body,headers={})=>fetch(root+route,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)}),input={name:'Future API acceptance',hypothesis:'Test registration, not predictive skill.',start:Date.now()+86400000,issuances:2,stepDays:1,settleDays:2};let preview=await(await post('/api/protocol-preview',input)).json();assert.ok(preview.previewHash);await post('/api/config',{radiusKm:700});assert.equal((await post('/api/protocol-register',{...input,previewHash:preview.previewHash})).status,400);preview=await(await post('/api/protocol-preview',input)).json();assert.equal((await post('/api/protocol-register',{...input,previewHash:preview.previewHash},{Origin:'https://foreign.example'})).status,403);const protocol=await(await post('/api/protocol-register',{...input,previewHash:preview.previewHash})).json();assert.equal(protocol.spec.config.radiusKm,700);assert.equal((await(await post('/api/protocol-register',{...input,previewHash:preview.previewHash})).json()).id,protocol.id);const detail=await(await fetch(root+'/api/protocol?id='+protocol.id)).json();assert.equal(detail.summary.remaining,2);assert.equal(detail.summary.primaryDsMinusRecent,null);await post('/api/protocol-stop',{id:protocol.id});const stopped=await(await fetch(root+'/api/protocol?id='+protocol.id)).json();assert.equal(stopped.summary.state,'CANCELLED');assert.equal(stopped.slots.length,2);assert.equal((await(await post('/api/protocol-check',{})).json()).changes,0);const exported=await(await fetch(root+'/api/protocol-export?id='+fixture.id)).json();assert.equal(exported.integrity.valid,true);assert.equal(exported.summary.completeGroups,1);assert.equal(exported.summary.primaryDsMinusRecent,1);assert.equal(exported.forecastProofs.length,3);const answer=await(await post('/api/chat',{protocolId:fixture.id,message:'Explain this controlled experiment',asOf:Date.now()})).json();assert.equal(answer.provider,'deterministic');assert.deepEqual(answer.actions,[]);assert.match(answer.answer,/1 issued groups/);assert.equal((await post('/api/chat',{protocolId:fixture.id,message:'Explain',asOf:exported.protocol.registeredAt})).status,400);assert.equal((await post('/api/chat',{protocolId:fixture.id,instrumentRecordId:'other',message:'Explain'})).status,400);assert.equal((await(await fetch(root+'/api/ledger')).json()).integrity.count,3);
 }finally{child.kill();await new Promise(r=>child.exitCode!==null?r():child.once('exit',r));}
});
