import test from 'node:test';
import assert from 'node:assert/strict';
import {reliefEvidence} from '../server/relief.mjs';
import {commandActions} from '../server/ai.mjs';
import {parseReliefDods} from '../server/relief-data.mjs';
import {reliefGrid,reliefRadius,RELIEF_RADIUS_M} from '../public/relief-grid.js';
function source(){const parts=[Buffer.from('Dataset { Grid { ARRAY: Float32 z[lat = 2][lon = 4]; MAPS: Float64 lat[lat = 2]; Float64 lon[lon = 4]; } z; } test;\nData:\n')];for(const [values,size]of [[[-100.25,0,100.25,200,300,400,500,600],4],[[-45,45],8],[[-135,-45,45,135],8]]){const b=Buffer.alloc(8+values.length*size);b.writeUInt32BE(values.length);b.writeUInt32BE(values.length,4);values.forEach((v,i)=>size===4?b.writeFloatBE(v,8+i*size):b.writeDoubleBE(v,8+i*size));parts.push(b);}return Buffer.concat(parts);}
test('ETOPO parser preserves signed source floats and rejects malformed DAP counts, missing cells and coordinates',()=>{
 const raw=source(),s=parseReliefDods(raw);assert.equal(s.elevations[0],-100.25);assert.equal(s.packed.readInt16LE(0),-100);assert.equal(s.maximumQuantizationErrorM,.25);assert.equal(s.latitudes[0],-45);assert.throws(()=>parseReliefDods(raw.subarray(0,-1)),/length/);assert.throws(()=>parseReliefDods(Buffer.concat([raw,Buffer.alloc(1)])),/trailing/);const bad=Buffer.from(raw),start=raw.indexOf('Data:\n')+6;bad.writeUInt32BE(9,start);assert.throws(()=>parseReliefDods(bad),/count/);bad.set(raw);bad.writeFloatBE(-99999,start+8);assert.throws(()=>parseReliefDods(bad),/missing/);
});
test('relief interpolation wraps longitude, converges at poles and keeps display scale distinct from source metres',()=>{
 const parsed=parseReliefDods(source()),grid=reliefGrid(parsed.packed.buffer.slice(parsed.packed.byteOffset,parsed.packed.byteOffset+parsed.packed.byteLength),{width:4,height:2,latitudeStart:-45,longitudeStart:-135,latitudeStep:90,longitudeStep:90});assert.equal(grid.heightAt(-45,-135),-100);assert.equal(grid.heightAt(0,-135),100);assert.equal(grid.heightAt(0,180),grid.heightAt(0,-180));assert.equal(grid.heightAt(90,0),450);assert.equal(grid.heightAt(90,172),450);assert.equal(grid.heightAt(-90,-179),50);assert.throws(()=>grid.heightAt(91,0));assert.throws(()=>grid.heightAt(0,181));const dataset={grid,metadata:{receivedAt:'2026-09-13T00:00:00Z'}},cutoff=Date.parse(dataset.metadata.receivedAt);assert.throws(()=>reliefEvidence(dataset,{lat:0,lon:0},cutoff-1),/cutoff/);assert.throws(()=>reliefEvidence(dataset,{lat:91,lon:0},cutoff));assert.equal(reliefEvidence(dataset,{lat:0,lon:0},cutoff).sample.interpolatedM,250);assert.deepEqual(commandActions('Explain the Tonga seafloor',{reliefEvidence:{}}),[]);assert.deepEqual(commandActions('Show terrain'),['relief']);const before=grid.values.slice();assert.equal(reliefRadius(-8000,20,false),1);assert.ok(Math.abs((1-reliefRadius(-8000,20,true))*RELIEF_RADIUS_M-160000)<1e-8);assert.ok(Math.abs((reliefRadius(4000,1,true)-1)*RELIEF_RADIUS_M-4000)<1e-8);assert.deepEqual(grid.values,before);assert.throws(()=>reliefRadius(100,0,true));
});
