import test from 'node:test';
import assert from 'node:assert/strict';
import {Store,canonical} from '../server/store.mjs';
import {ResolutionReviews,resolutionReviewEvidence} from '../server/resolution-reviews.mjs';
import {DAY} from '../server/geo.mjs';
import {chat} from '../server/ai.mjs';
import {resolutionClassification} from '../server/resolution-reviews.mjs';
const forecast=(now,extra={})=>({engine:'DS',engineVersion:'fixture',catalogProvider:'USGS',region:'Controlled target',center:{lat:0,lon:0},radiusKm:100,magnitude:{min:5,max:6,central:5.5},validFrom:now-2*DAY,validUntil:now-DAY,asOf:now-2*DAY,sources:['USGS:source'],sourceEvents:[],mode:'prospective',...extra});
const event=(now,extra={})=>({id:'USGS:match',provider:'USGS',time:now-1.5*DAY,lat:0,lon:.1,mag:5.5,depth:10,type:'earthquake',magType:'mw',status:'reviewed',updated:now-1000,...extra});
test('review explanations preserve the partial-hit envelope distinction and source magnitude scale',async t=>{
 const f=forecast(Date.now()),result={status:'PARTIAL HIT',event:{mag:4.8,magType:'mlg'}},classificationText=resolutionClassification(f,result);assert.match(classificationText,/M4.8 \(mlg\) is outside M5–6/);t.mock.method(globalThis,'fetch',async()=>new Response(JSON.stringify({message:{content:JSON.stringify({answer:'PARTIAL HIT: Mw 4.8 was inside the nominal forecast magnitude envelope.',actions:[]})}})));await assert.rejects(chat('Explain',{resolutionReviewEvidence:{classificationText,currentReview:{result:{status:'PARTIAL HIT'}}}},{aiProvider:'ollama',localModel:'controlled'}),/classification and magnitude range/);
});
test('catalog corrections append reproducible reviews while original forecast, result and earlier evidence stay frozen',t=>{
 const s=new Store(':memory:'),reviews=new ResolutionReviews(s);t.after(()=>s.close());let now=Date.now()-10*DAY;t.mock.method(Date,'now',()=>now);s.set('coverage',[{provider:'USGS',start:now-3*DAY,end:now,minMagnitude:4}]);const [f]=s.issue([forecast(now)],{issuedAt:now-2*DAY});const before=s.verify();s.ingest([event(now),event(now,{id:'EMSC:other',provider:'EMSC'})],now-500);const initial=reviews.review();assert.equal(initial.resolved,1);const first=reviews.attach(s.ledger())[0];assert.equal(first.resolution.status,'HIT');assert.equal(first.latestResolution.status,'HIT');const original=canonical(first.resolution),firstId=first.reviewId;assert.equal(reviews.reproduce(firstId).identical,true);assert.equal(reviews.review().unchanged,1);
 now+=1000;s.ingest([event(now-1000,{mag:3,updated:now})],now);const changed=reviews.review();assert.equal(changed.changed,1);const latest=reviews.attach(s.ledger())[0];assert.equal(latest.latestResolution.status,'MISS');assert.equal(canonical(latest.resolution),original);assert.deepEqual(s.verify(),before);assert.equal(reviews.export(firstId).outcomeSnapshot.events[0].mag,5.5);assert.equal(reviews.reproduce(firstId).result.status,'HIT');assert.equal(reviews.reproduce(latest.reviewId).result.status,'MISS');assert.equal(reviews.history(f.id).entries.length,2);
 const saved=reviews.export(latest.reviewId);assert.throws(()=>resolutionReviewEvidence(saved,now-1),/cutoff/);assert.equal(resolutionReviewEvidence(saved,now).currentReview.result.status,'MISS');assert.throws(()=>s.db.prepare('DELETE FROM resolution_reviews').run(),/immutable/);assert.throws(()=>s.db.prepare('UPDATE resolutions SET result=?').run('{}'),/immutable/);
 const later=now+10000;s.ingest([event(now-1000,{mag:5.7,updated:later})],later);assert.equal(reviews.review().unchanged,1);now=later;assert.equal(reviews.review().changed,1);assert.equal(reviews.attach(s.ledger())[0].latestResolution.status,'HIT');assert.equal(reviews.verify().valid,true);
});
test('coverage must include partial-hit magnitudes and cannot turn missing data into a miss',t=>{
 const s=new Store(':memory:'),reviews=new ResolutionReviews(s),now=Date.now();t.after(()=>s.close());const [f]=s.issue([forecast(now)],{issuedAt:now-2*DAY});s.set('coverage',[{provider:'USGS',start:now-3*DAY,end:now,minMagnitude:5}]);s.ingest([event(now,{mag:4.8})],now-500);assert.equal(reviews.review().awaitingCoverage,1);assert.equal(s.ledger()[0].resolution,null);
 s.resolve(f.id,{status:'HIT',evaluatedAt:now-100});assert.equal(reviews.review().reviewed,1);assert.equal(reviews.attach(s.ledger())[0].latestResolution.status,'AMBIGUOUS');s.set('coverage',[{provider:'USGS',start:now-3*DAY,end:now,minMagnitude:4.5}]);reviews.review();assert.equal(reviews.attach(s.ledger())[0].latestResolution.status,'PARTIAL HIT');s.set('coverage',[]);assert.equal(reviews.review().unchanged,1,'retained coverage evidence survives live coverage pruning');assert.equal(reviews.verify().valid,true);
 s.db.exec('DROP TRIGGER frozen_resolution_update');s.db.prepare('UPDATE resolutions SET result=? WHERE forecast_id=?').run('{"status":"MISS"}',f.id);assert.equal(reviews.verify().valid,false);assert.throws(()=>reviews.review(),/integrity failed/);
});
