import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,readFileSync} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {Store} from '../server/store.mjs';
import {DAY} from '../server/geo.mjs';
test('resolution API exposes both assessment bases, reproduces exports and isolates review AI from forecast issuance',async()=>{
 const file=path.join(mkdtempSync(path.join(os.tmpdir(),'seismo-resolution-')),'test.sqlite'),s=new Store(file),now=Date.now(),config=JSON.parse(readFileSync('config/default.json'));s.set('config',{...config,aiProvider:'deterministic'});s.set('coverage',[{provider:'USGS',start:now-24*DAY,end:now,minMagnitude:3}]);const [f]=s.issue([{engine:'DS',mode:'prospective',region:'Controlled API test',center:{lat:0,lon:0},radiusKm:100,magnitude:{min:5,max:6,central:5.5},validFrom:now-2*DAY,validUntil:now-DAY,sources:[]}],{issuedAt:now-2*DAY});s.resolve(f.id,{status:'HIT',evaluatedAt:now-1000});s.ingest([{id:'USGS:a',provider:'USGS',type:'earthquake',lat:0,lon:-10,mag:5,depth:10,magType:'mw',time:now-13*DAY},{id:'USGS:b',provider:'USGS',type:'earthquake',lat:0,lon:10,mag:5,depth:10,magType:'mw',time:now-13*DAY},{id:'USGS:c',provider:'USGS',type:'earthquake',lat:0,lon:0,mag:5.5,depth:10,magType:'mw',time:now-8*DAY}],now-1000);s.close();const port=14328,root=`http://127.0.0.1:${port}`,child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:String(port),SEISMO_DB:file,SEISMO_TEST_MODE:'1'},windowsHide:true,stdio:['ignore','pipe','pipe']});
 try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Startup timed out')),10000);child.stdout.on('data',b=>{if(String(b).includes('SeismoSphere running')){clearTimeout(timer);resolve();}});child.on('error',reject);});const post=(url,data)=>fetch(root+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),reviewed=await(await post('/api/resolve',{forecastId:f.id})).json();assert.equal(reviewed.changed,1);const latest=await(await fetch(root+'/api/ledger')).json(),original=await(await fetch(root+'/api/ledger?basis=original')).json();assert.equal(latest.forecasts[0].resolution.status,'HIT');assert.equal(latest.forecasts[0].latestResolution.status,'MISS');assert.equal(latest.leaderboard[0].hits,0);assert.equal(original.leaderboard[0].hits,1);assert.equal(latest.forecasts.length,1);const id=latest.forecasts[0].reviewId,exported=await(await fetch(root+'/api/resolution-review-export?id='+id)).json();assert.equal(exported.integrity.valid,true);assert.equal(exported.outcomeSnapshot.events.length,0);assert.equal((await(await fetch(root+'/api/resolution-reproduce?id='+id)).json()).identical,true);const request={resolutionReviewId:id,message:'Explain this assessment',asOf:Date.now(),mode:'strict'},answer=await(await post('/api/chat',request)).json();assert.match(answer.answer,/original HIT; selected assessment MISS/);assert.deepEqual(answer.actions,[]);
  for(const change of [{forecastId:f.id},{weeklyVolcanoId:'other'},{analysisId:'other'},{asOf:exported.review.createdAt-1},{mode:'bad'},{resolutionReviewId:'unknown'}])assert.equal((await post('/api/chat',{...request,...change})).status,400);assert.equal((await post('/api/resolve',{forecastId:'unknown'})).status,400);assert.equal((await fetch(root+'/api/ledger?basis=bad')).status,400);assert.equal((await(await post('/api/resolve',{forecastId:f.id})).json()).unchanged,1);
  const backtest=await post('/api/backtest',{start:new Date(now-12*DAY).toISOString(),end:new Date(now-DAY).toISOString(),stepDays:5}),experiment=await backtest.json();assert.equal(backtest.status,200,JSON.stringify(experiment));const after=(await(await fetch(root+'/api/ledger')).json()).forecasts.filter(f=>f.experimentId===experiment.experimentId);assert.ok(after.length>=3);for(const trial of after){assert.equal(trial.reviewCount,1);assert.equal(trial.latestResolution.status,trial.resolution.status);assert.equal((await(await fetch(root+'/api/resolution-reproduce?id='+trial.reviewId)).json()).identical,true);}
 }finally{child.kill();}
});
