import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {Store,hash} from '../server/store.mjs';
import {Instruments,instrumentContext,instrumentSourceValid} from '../server/instruments.mjs';
import {waveformUtc} from '../public/waveform-geometry.js';
import {instrumentResponse,closeResponseWorkers} from '../server/response.mjs';
test('full response correction preserves immutable sources, known SI scaling, encoding and cutoff isolation',async t=>{
 const fixture=JSON.parse(execFileSync(path.resolve('data/model-runtime',process.platform==='win32'?'Scripts/python.exe':'bin/python'),['scripts/response-decoder-check.py'],{windowsHide:true,encoding:'utf8',timeout:30000}));assert.equal(fixture.knownGainScalingPassed,true);
 const store=new Store(':memory:'),instruments=new Instruments(store),start=fixture.station.startUs/1000,end=start+fixture.values.length/fixture.sampleRateHz*1000;
 const metadata='#Network|Station|Location|Channel|Latitude|Longitude|Elevation|Depth|Azimuth|Dip|SensorDescription|Scale|ScaleFreq|ScaleUnits|SampleRate|StartTime|EndTime\nIU|TEST|00|BHZ|34|-106|1600|100|0|-90|Synthetic|2000000|1|m/s|64|2020-01-01T00:00:00|',wave=`# dataset: GeoCSV 2.0\n# delimiter: ,\n# SID: IU_TEST_00_BHZ\n# sample_count: ${fixture.values.length}\n# sample_rate_hz: 64\n# start_time: 2020-01-01T00:00:00\n# field_unit: UTC, Counts\nTime, Sample\n`+fixture.values.map((v,i)=>waveformUtc(start*1000+i*1e6/64)+', '+v).join('\n');let calls=0;
 t.mock.method(globalThis,'fetch',async url=>{calls++;return new Response(url.includes('level=response')?Buffer.from(fixture.xmlBase64,'base64'):url.includes('/station/')?metadata:wave);});
 try{const stations=await instruments.stations({at:start,networks:'IU',channel:'BHZ'}),source=await instruments.waveform({stationRecordId:stations.id,channelId:stations.channels[0].id,start,end,asOf:Date.now()}),request={waveformId:source.id,asOf:Date.now(),mode:'catalog-replay'};
  await assert.rejects(instruments.response({...request,asOf:end,mode:'strict'}),/unavailable/);const response=await instruments.response(request);assert.equal(response.raw,fixture.xmlBase64);assert.equal(instrumentSourceValid(response),true);assert.equal((await instruments.response(request)).reused,true);assert.equal(calls,3);
  const query={...request,responseId:response.id,runIndex:0,startIndex:0,samples:fixture.values.length,...fixture.options},corrected=await instruments.correct(query),{id,...body}=corrected;assert.equal(hash(body),id);assert.equal(corrected.summary.units,'m/s');assert.equal(corrected.summary.samples,2048);assert.equal(corrected.segments[0].samples[0][0],source.segments[0].samples[0][0]);assert.equal((await instruments.correct(query)).reused,true);assert.equal(store.verify().count,0);
  const context=instrumentContext(corrected,Date.now(),'catalog-replay',source,response);assert.equal(context.correction.summary.units,'m/s');assert.equal(context.correction.values,undefined);assert.equal(context.correction.response.receipt.sha256,response.receipt.sha256);assert.throws(()=>instrumentContext(corrected,corrected.createdAt-1,'strict',source,response),/unavailable/);assert.throws(()=>instrumentContext(corrected,Date.now(),'catalog-replay',source,{...response,id:'wrong'}),/match/);
  const spectralQuery={waveformId:corrected.id,runIndex:0,startIndex:0,samples:2048,window:'hann',detrend:'constant',timeFrequency:{frameSamples:256,hopSamples:128},asOf:Date.now()},spectrum=await instruments.spectrum(spectralQuery);assert.equal(spectrum.summary.sampleUnits,'m/s');assert.equal(spectrum.psdCounts2PerHz,undefined);assert.equal(spectrum.spectrogram.summary.units,'(m/s)²/Hz');assert.equal((await instruments.spectrum(spectralQuery)).id,spectrum.id);const physicalContext=instruments.context(spectrum,Date.now(),'catalog-replay');assert.equal(physicalContext.source.correction.query.responseId,response.id);assert.equal(physicalContext.source.source.id,source.id);assert.equal(physicalContext.source.correction.segments,undefined);assert.equal(physicalContext.spectrum.psd,undefined);for(const cutoff of [source.createdAt-1,response.createdAt-1,corrected.createdAt-1,spectrum.createdAt-1])assert.throws(()=>instruments.context(spectrum,cutoff,'strict'),/unavailable/);await assert.rejects(instruments.spectrum({...spectralQuery,asOf:corrected.createdAt-1,mode:'strict'}),/unavailable/);await assert.rejects(instruments.spectrum({...spectralQuery,waveformId:response.id}),/raw or response-corrected/);
  await assert.rejects(instruments.correct({...query,preFilterHz:[.5,1,20,32]}),/corners/);await assert.rejects(instruments.correct({...query,runIndex:1}),/continuous/);assert.throws(()=>store.db.exec('DELETE FROM instrument_records'),/immutable/);
 }finally{store.close();}
 const cancelled=assert.rejects(instrumentResponse({operation:'metadata',xmlBase64:fixture.xmlBase64,station:fixture.station,startUtc:'2020-01-01T00:00:00Z',endUtc:'2020-01-01T00:00:32Z'}),/stopping/);await closeResponseWorkers();await cancelled;
});
