import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Store} from '../server/store.mjs';
import {RouteHistory,validateRoutes,routeWalks} from '../server/routes.mjs';
import {generate} from '../server/engine.mjs';
import {DAY} from '../server/geo.mjs';
const route=(id,points,next=[])=>({id,name:id,points:points.map(lon=>({lat:0,lon})),next,termination:false,kind:'research-corridor',direction:'forward',provenance:{status:'illustrative'}});
const base={routes:[route('a',[0,5],['b']),route('b',[5,10,15])],maxHops:4,captureKm:50};
test('route graph validates explicit links, keeps immutable revisions and rejects stale writers',()=>{const s=new Store(':memory:'),h=new RouteHistory(s,base),first=h.current();assert.equal(first.routes.length,2);const next=h.save({network:{...base,maxHops:5},baseVersion:first.version,note:'Extend traversal'});assert.equal(next.parentVersion,first.version);assert.equal(h.get(first.version).maxHops,4);assert.throws(()=>h.save({network:base,baseVersion:first.version,note:'stale'}),/changed/);assert.throws(()=>s.db.prepare('UPDATE route_versions SET body=?').run('{}'),/immutable/);assert.throws(()=>validateRoutes({...base,routes:[route('a',[0,5],['missing'])]}),/another route/);assert.throws(()=>validateRoutes({...base,routes:[route('a',[0,5],['b']),route('b',[8,10])]}),/endpoint/);assert.throws(()=>validateRoutes({routes:[{...route('a',[0,5]),provenance:{status:'source-traced'}}]}),/requires/);assert.throws(()=>validateRoutes({routes:[route('a',[0,180])]}),/Adjacent/);s.close();});
test('direction, branches, reflections and bounded cycles use only configured geometry',()=>{const n=validateRoutes(base);assert.deepEqual(routeWalks(n,{lat:0,lon:0}).map(w=>w.center.lon),[5,10,15]);assert.equal(routeWalks(n,{lat:50,lon:0}).length,0);const reversed=validateRoutes({routes:[{...route('r',[0,5,10]),direction:'reverse',termination:true}],captureKm:50,maxHops:4});assert.deepEqual(routeWalks(reversed,{lat:0,lon:10},{reflection:false}).map(w=>w.center.lon),[5,0]);assert.deepEqual(routeWalks(reversed,{lat:0,lon:10}).map(w=>w.center.lon),[5,0,5,10]);const cycle=validateRoutes({routes:[route('a',[0,5],['b']),route('b',[5,0],['a'])],maxHops:12,captureKm:50});assert.ok(routeWalks(cycle,{lat:0,lon:0}).length<12);});
test('engine emits sourced route rules, ignores future releases and versions candidate identity',()=>{const now=100*DAY,config={...JSON.parse(readFileSync(new URL('../config/default.json',import.meta.url))),maxTargets:40,radiusKm:50},event=(id,lon,time,depth=10)=>({id,lat:0,lon,mag:5.5,magType:'mw',time,depth,type:'earthquake',provider:'USGS'}),events=[event('deep',0,now-2*DAY,500),event('follow',5,now-DAY),...Array.from({length:5},(_,i)=>event('swarm'+i,.1+i*.01,now-DAY+i))],network={...validateRoutes({routes:[{...route('r',[0,5,10,15]),kind:'craton-edge',termination:true}],captureKm:100,maxHops:4}),version:'v1'};
 const a=generate(events,now,config,network);assert.ok(a.candidates.some(c=>c.routeId==='r'));assert.ok(a.stats.evaluatedCandidates>a.candidates.length);assert.deepEqual(a.candidates,generate([...events,event('future',10,now+1)],now,config,network).candidates);assert.notDeepEqual(a.candidates.map(c=>c.key),generate(events,now,config,{...network,version:'v2'}).candidates.map(c=>c.key));assert.ok(a.candidates.some(c=>c.factors.some(f=>f.rule==='Configured craton-edge progression')));
 for(const [rules,kind] of [[{deep:false,midpoint:true,spacing:false,swarm:false},'path-midpoint'],[{deep:false,midpoint:false,spacing:true,swarm:false},'equidistant-progression'],[{deep:false,midpoint:false,spacing:false,swarm:true},'swarm-redistribution']]){const r=generate(events,now,{...config,rules:{...config.rules,...rules}},network);assert.ok(r.candidates.some(c=>c.kind===kind),kind);}
});
