import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../server/store.mjs';
import {VolcanoStatus,parseVolcanoStatus,volcanoStatusEvidence,STATUS_INTERVAL} from '../server/volcano-status.mjs';
const feature=(code='ak102',number='')=>({type:'Feature',geometry:{type:'Point',coordinates:[-155.21516,58.40881]},properties:{volcanoCd:code,vnum:number,volcanoName:'Folsoms Bluff',alertLevel:'UNASSIGNED',colorCode:'UNASSIGNED',noticeId:null,noticeSynopsis:null,volcanoUrl:'https://avo.alaska.edu/volcanoes/volcinfo.php?volcname=Folsoms Bluff'}});
const source=(features=[feature()])=>JSON.stringify({type:'FeatureCollection',features});
test('volcano status preserves separate alert systems, missing GVP identities and source times',()=>{
 const f=feature('hi3','332010');Object.assign(f.properties,{alertLevel:'WATCH',colorCode:'YELLOW',noticeId:'DOI-USGS-HVO-2026-09-12T16:10:43+00:00',alertDate:'2026-09-12 17:37:09'});const rows=parseVolcanoStatus(source([f,feature()]));assert.equal(rows[0].number,null);assert.equal(rows[0].alertLevel,'UNASSIGNED');assert.equal(rows[1].alertLevel,'WATCH');assert.equal(rows[1].aviationColor,'YELLOW');assert.equal(rows[1].noticeTime,Date.parse('2026-09-12T16:10:43Z'));assert.equal(rows[1].sourceAlertDate,'2026-09-12 17:37:09');assert.throws(()=>parseVolcanoStatus(source([f,f])),/duplicate/);f.geometry.coordinates[0]=null;assert.throws(()=>parseVolcanoStatus(source([f])),/Invalid/);
});
test('volcano polls preserve receipts and failures, reject later evidence and cannot rewrite history',async t=>{
 const store=new Store(':memory:'),status=new VolcanoStatus(store);t.after(()=>store.close());let now=Date.now()-3600000,raw=source(),failure=false;t.mock.method(Date,'now',()=>now);t.mock.method(globalThis,'fetch',async()=>{if(failure)throw new Error('controlled outage');return new Response(raw);});
 const first=await status.refresh();assert.equal(first.volcanoes.length,1);assert.equal(status.view(now-1).available,false);assert.equal(volcanoStatusEvidence(status.view(), 'ak102',now).selected.alertLevel,'UNASSIGNED');assert.throws(()=>volcanoStatusEvidence(first,'ak102',now-1),/cutoff/);
 now+=31000;const same=await status.refresh({force:true});assert.equal(same.id,first.id);assert.equal(same.createdAt,first.createdAt);assert.equal(same.checkedAt,now);assert.equal(store.db.prepare('SELECT count(*) n FROM volcano_status_records').get().n,1);assert.equal(store.db.prepare('SELECT count(*) n FROM volcano_status_checks').get().n,2);
 const f=feature();f.properties.alertLevel='ADVISORY';f.properties.colorCode='YELLOW';raw=source([f]);now+=31000;const changed=await status.refresh({force:true});assert.notEqual(changed.id,first.id);assert.equal(status.view(first.checkedAt).volcanoes[0].alertLevel,'UNASSIGNED');assert.equal(status.view().volcanoes[0].alertLevel,'ADVISORY');assert.throws(()=>store.db.prepare('UPDATE volcano_status_records SET body=? WHERE id=?').run('{}',first.id),/immutable/);assert.throws(()=>store.db.prepare('DELETE FROM volcano_status_checks').run(),/immutable/);
 failure=true;now+=STATUS_INTERVAL*3;await assert.rejects(status.refresh(),/outage/);assert.equal(status.view().id,changed.id);assert.equal(status.view().stale,true);assert.match(status.view().feed.error,/outage/);assert.deepEqual(status.view(first.checkedAt).feed,{});assert.equal(store.verify().valid,true);const corrupt=status.get(changed.id);corrupt.volcanoes[0].alertLevel='NORMAL';store.db.exec('DROP TRIGGER frozen_volcano_status_update');store.db.prepare('UPDATE volcano_status_records SET body=? WHERE id=?').run(JSON.stringify(corrupt),changed.id);assert.throws(()=>status.get(changed.id),/integrity/);
});
