import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Store} from '../server/store.mjs';
import {WeeklyVolcanoes,parseWeeklyVolcanoes,weeklyVolcanoEvidence,WEEKLY_INTERVAL} from '../server/weekly-volcanoes.mjs';
const source=(description='&lt;p&gt;Poás reported ash.&lt;/p&gt;',point='10.2 -84.2',date='Thu, 03 Sep 2026 04:12:58 -0400')=>Buffer.from(`<?xml version="1.0" encoding="ISO-8859-1"?><rss xmlns:georss="http://www.georss.org/georss"><channel><title>Weekly report</title><link>https://volcano.si.edu/reports_weekly.cfm</link><pubDate>Thu, 03 Sep 2026 04:12:58 -0500</pubDate><item><title>Poás (Costa Rica) - Report for 27 August-2 September 2026 - Continuing Eruptive Activity</title><guid>https://volcano.si.edu/reports_weekly.cfm#vn_345040</guid><pubDate>${date}</pubDate><description>${description}</description>${point===null?'':`<georss:point>${point}</georss:point>`}</item></channel></rss>`,'latin1');
test('weekly XML honors source encoding, independent offsets and absent coordinates; rejects hostile XML',async()=>{
 const p=await parseWeeklyVolcanoes(source('&lt;p&gt;Poás &amp;amp; ash&lt;/p&gt;&lt;script&gt;HIDDEN&lt;/script&gt;'));assert.equal(p.encoding,'ISO-8859-1');assert.equal(p.reports[0].name,'Poás');assert.equal(p.reports[0].text,'Poás & ash');assert.equal(p.publishedAt,'2026-09-03T09:12:58Z');assert.equal(p.reports[0].publishedAt,'2026-09-03T08:12:58Z');assert.equal(p.reports[0].period,'27 August-2 September 2026');assert.equal((await parseWeeklyVolcanoes(source('',null))).reports[0].lat,null);await assert.rejects(parseWeeklyVolcanoes(source('','91 180')),/coordinates/);await assert.rejects(parseWeeklyVolcanoes(source('','0 0','Thu, 03 Sep 2026 04:12:58')),/time zone/);await assert.rejects(parseWeeklyVolcanoes(Buffer.from('<!DOCTYPE rss [<!ENTITY x "boom">]><rss/>')),/entity declarations/);
});
test('weekly reports retain original bytes, immutable history and publication age across polls and failures',async t=>{
 const store=new Store(':memory:'),feed=new WeeklyVolcanoes(store);t.after(()=>store.close());let now=Date.parse('2026-09-13T15:00:00Z'),raw=source(),failure=false;t.mock.method(Date,'now',()=>now);t.mock.method(globalThis,'fetch',async()=>{if(failure)throw new Error('controlled outage');return new Response(raw);});
 const first=await feed.refresh();assert.equal(first.publicationOld,true);assert.equal(first.stale,false);assert.equal(first.receipt.sha256,createHash('sha256').update(raw).digest('hex'));assert.deepEqual(Buffer.from(feed.get(first.id).rawBase64,'base64'),raw);assert.equal(feed.view(now-1).available,false);assert.equal(weeklyVolcanoEvidence(first,'345040',now).selected.name,'Poás');assert.throws(()=>weeklyVolcanoEvidence(first,'345040',now-1),/cutoff/);
 now+=31000;const again=await feed.refresh({force:true});assert.equal(again.id,first.id);assert.equal(again.createdAt,first.createdAt);assert.equal(again.checkedAt,now);assert.equal(again.publicationOld,true);
 now+=31000;raw=source('A revised report.');const changed=await feed.refresh({force:true});assert.notEqual(changed.id,first.id);assert.equal(feed.view(first.checkedAt).id,first.id);assert.throws(()=>store.db.prepare('DELETE FROM weekly_volcano_checks').run(),/immutable/);assert.throws(()=>store.db.prepare('UPDATE weekly_volcano_records SET body=?').run('{}'),/immutable/);
 now+=WEEKLY_INTERVAL*3;failure=true;await assert.rejects(feed.refresh(),/outage/);assert.equal(feed.view().id,changed.id);assert.equal(feed.view().stale,true);assert.match(feed.view().feed.error,/outage/);assert.deepEqual(feed.view(first.checkedAt).feed,{});
 const corrupt=feed.get(changed.id);corrupt.publication.reports[0].text='Invented';store.db.exec('DROP TRIGGER frozen_weekly_volcano_update');store.db.prepare('UPDATE weekly_volcano_records SET body=? WHERE id=?').run(JSON.stringify(corrupt),changed.id);assert.throws(()=>feed.get(changed.id),/integrity/);
});
