import {createHash} from 'node:crypto';
import {hash} from './store.mjs';
const ROOT='https://geodesy.unr.edu/gps_timeseries/IGS20/midas/',FILES={IGS20:'IGS',NA:'NA',PA:'PA',EU:'EU'},MAX_BYTES=16000000;
export function gnssFrame(value='IGS20'){if(!Object.hasOwn(FILES,value))throw new Error('Choose GNSS frame IGS20, NA, PA or EU.');return value;}
// NGL uses 365.25-day years anchored at noon GPS on 2000-01-01.
// UTC noon is a conservative later bound; include half the four-decimal rounding bin.
// This is an eligibility bound, not an exact source epoch conversion.
const fitEndUpperBound=epoch=>Date.UTC(2000,0,1,12)+(epoch-2000+.00005)*365.25*86400000;
export function parseMidas(text,frame='IGS20',receivedAt=Infinity){
 gnssFrame(frame);const stations=[],ids=new Set();
 for(const [i,line]of text.trim().split(/\r?\n/).entries()){
  if(!line.trim())continue;const cells=line.trim().split(/\s+/),values=cells.slice(2).map(Number);
  if(cells.length!==27||!/^[A-Z0-9_]{4}$/.test(cells[0])||!/^MIDAS\d+$/.test(cells[1])||!values.every(Number.isFinite))throw new Error(`Invalid MIDAS row ${i+1}; expected 27 documented fields.`);
  const [firstEpoch,lastEpoch,durationYears,epochs,goodEpochs,pairs,east,north,up,eastUncertainty,northUncertainty,upUncertainty,eastOffset,northOffset,upOffset,eastOutliers,northOutliers,upOutliers,eastPairSD,northPairSD,upPairSD,steps,lat,sourceLongitude,heightM]=values;
  if(ids.has(cells[0])||durationYears<=0||![epochs,goodEpochs,pairs,steps].every(n=>Number.isInteger(n)&&n>=0)||goodEpochs>epochs||[eastUncertainty,northUncertainty,upUncertainty,eastPairSD,northPairSD,upPairSD].some(n=>n<0)||[eastOutliers,northOutliers,upOutliers].some(n=>n<0||n>1)||Math.abs(lat)>90||Math.abs(sourceLongitude)>360)throw new Error(`Invalid MIDAS values or duplicate station at row ${i+1}.`);
  const fitAvailableAtReceipt=fitEndUpperBound(lastEpoch)<=receivedAt,validFitInterval=firstEpoch>=1900&&lastEpoch>=firstEpoch&&lastEpoch<=2200&&Math.abs(lastEpoch-firstEpoch-durationYears)<=.001&&fitAvailableAtReceipt;ids.add(cells[0]);stations.push({validFitInterval,fitAvailableAtReceipt,id:cells[0],version:cells[1],frame,firstEpoch,lastEpoch,durationYears,epochs,goodEpochs,pairs,lat,lon:((sourceLongitude+180)%360+360)%360-180,sourceLongitude,heightM,velocityMyr:{east,north,up},uncertaintyMyr:{east:eastUncertainty,north:northUncertainty,up:upUncertainty},offsetM:{east:eastOffset,north:northOffset,up:upOffset},outlierFraction:{east:eastOutliers,north:northOutliers,up:upOutliers},pairSD:{east:eastPairSD,north:northPairSD,up:upPairSD},steps});
 }
 if(!stations.length||stations.length>50000)throw new Error('Expected 1–50,000 MIDAS stations.');return stations;
}
export class GNSS{
 constructor(store){this.store=store;this.busy=false;this.cache=new Map();store.db.exec(`CREATE TABLE IF NOT EXISTS gnss_receipts(id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,body TEXT NOT NULL);CREATE TRIGGER IF NOT EXISTS immutable_gnss_update BEFORE UPDATE ON gnss_receipts BEGIN SELECT RAISE(ABORT,'GNSS receipts are immutable');END;CREATE TRIGGER IF NOT EXISTS immutable_gnss_delete BEFORE DELETE ON gnss_receipts BEGIN SELECT RAISE(ABORT,'GNSS receipts are immutable');END;`);}
 list(){return this.store.db.prepare('SELECT id,created_at,json_extract(body,\'$.frame\') frame,json_extract(body,\'$.count\') stations,json_extract(body,\'$.receipt.lastModified\') lastModified FROM gnss_receipts ORDER BY created_at DESC LIMIT 100').all().map(r=>({id:r.id,createdAt:r.created_at,frame:r.frame,stations:r.stations,lastModified:r.lastModified}));}
 get(id){let result=this.cache.get(id);if(result)return result;const row=this.store.db.prepare('SELECT body FROM gnss_receipts WHERE id=?').get(id);if(!row)throw new Error('GNSS receipt not found.');const body=JSON.parse(row.body);if(hash({frame:body.frame,source:body.receipt.url,sha256:body.receipt.sha256})!==id||createHash('sha256').update(body.raw).digest('hex')!==body.receipt.sha256)throw new Error('GNSS source integrity mismatch.');result={...body,id,stations:parseMidas(body.raw,body.frame,body.createdAt)};this.cache.set(id,result);while(this.cache.size>4)this.cache.delete(this.cache.keys().next().value);return result;}
 save(raw,frame,receipt){gnssFrame(frame);const stations=parseMidas(raw,frame),digest=createHash('sha256').update(raw).digest('hex'),source=ROOT+'midas.'+FILES[frame]+'.txt';if(receipt.url!==source)throw new Error('GNSS source does not match the selected reference frame.');const id=hash({frame,source,sha256:digest});if(this.store.db.prepare('SELECT id FROM gnss_receipts WHERE id=?').get(id))return {...this.summary(id),reused:true};
  const createdAt=Date.now(),body={frame,createdAt,count:stations.length,receipt:{...receipt,sha256:digest,bytes:Buffer.byteLength(raw)},raw,provenance:{provider:'Nevada Geodetic Laboratory, University of Nevada, Reno',source,frame,method:'Published MIDAS robust trends; the application does not refit these velocities.',format:'https://geodesy.unr.edu/velocities/midas.readme.txt',citations:[{name:'Blewitt et al. (2016), MIDAS robust trend estimator for accurate GPS station velocities without step detection',doi:'https://doi.org/10.1002/2015JB012552'},{name:'Blewitt et al. (2018), Harnessing the GPS data explosion for interdisciplinary science',doi:'https://doi.org/10.1029/2018EO104623'}],attribution:'Credit NGL processing and the original station data providers linked from each NGL station page.',policy:'Long-term geodetic station trends over the supplied per-station fit intervals. IGS20 is a global reference frame; NA, PA and EU remove the respective modeled plate rotation horizontally. No strain field, pressure transfer, earthquake precursor, fault locking or current station health is inferred. Reported component uncertainties are preserved; cross-component covariance is not supplied.'}};
  this.store.db.prepare('INSERT INTO gnss_receipts VALUES(?,?,?)').run(id,createdAt,JSON.stringify(body));return this.summary(id);
 }
 summary(id){const {raw,stations,...body}=this.get(id);return body;}
 refresh(frame='IGS20'){gnssFrame(frame);if(this.busy)throw new Error('A GNSS source download is already running.');this.busy=true;this.controller=new AbortController();this.pending=(async()=>{const url=ROOT+'midas.'+FILES[frame]+'.txt',response=await fetch(url,{signal:AbortSignal.any([this.controller.signal,AbortSignal.timeout(60000)])});if(!response.ok)throw new Error('NGL source HTTP '+response.status);const chunks=[];let bytes=0;for await(const part of response.body){bytes+=part.length;if(bytes>MAX_BYTES)throw new Error('NGL source exceeds the 16 MB limit.');chunks.push(Buffer.from(part));}return this.save(Buffer.concat(chunks).toString('utf8'),frame,{url,fetchedAt:Date.now(),lastModified:response.headers.get('last-modified')});})().finally(()=>{this.busy=false;this.controller=null;});return this.pending;}
 async shutdown(){this.controller?.abort();await this.pending?.catch(()=>{});}
}
export function gnssEvidence(record,stationId,asOf){if(!Number.isFinite(asOf)||asOf<record.createdAt)throw new Error('This GNSS solution was received after the analysis cutoff.');const station=record.stations.find(s=>s.id===stationId);if(!station)throw new Error('GNSS station not present in this saved solution.');if(!station.fitAvailableAtReceipt)throw new Error('The GNSS fit end was not safely before receipt; this station is excluded from AI evidence.');return {recordId:record.id,station,provenance:record.provenance,receipt:record.receipt,displayUnits:'Multiply source m/year values by 1000 for mm/year. Fit epochs remain NGL decimal years.',stationPage:`https://geodesy.unr.edu/NGLStationPages/stations/${station.id}.sta`,limitations:['The copilot receives published velocity summaries, not the daily coordinate time series.','A frame-dependent station velocity is not strain, stress, imminent earthquake probability or evidence of pressure transfer.','Trend intervals differ across stations and may include old or discontinued sites. Receipt time bounds historical use; do not apply these later fits to earlier forecasts.']};}
