import {waveformRuns} from '../public/spectrum-data.js';
import {hash} from './store.mjs';
import {instrumentResponse} from './response.mjs';
import {waveformUtc} from '../public/waveform-geometry.js';
const VERSION='waveform-phase-comparison-0.1.1';
const supported=['P','p','Pn','Pg','Pdiff','PKP','PKIKP','S','s','Sn','Sg','Sdiff','SKS','SKIKS','pP','sP','PP','SS'];
export function phasePicks(source,arrivals,input){
 if(!Array.isArray(input)||input.length>20)throw new Error('Use at most 20 manual picks');
 return input.map(p=>{const segment=source.segments[p.segmentIndex],point=segment?.samples[p.sampleIndex],a=p.arrivalIndex===null?null:arrivals[p.arrivalIndex];if(!Number.isInteger(p.segmentIndex)||!Number.isInteger(p.sampleIndex)||!point||!(p.arrivalIndex===null||Number.isInteger(p.arrivalIndex)&&a)||!Number.isFinite(p.uncertaintySeconds)||p.uncertaintySeconds<=0||p.uncertaintySeconds>120||!['up','down','unclear'].includes(p.polarity))throw new Error('Choose an exact saved sample, an optional modeled arrival, positive uncertainty up to 120 seconds and a polarity label');return {segmentIndex:p.segmentIndex,sampleIndex:p.sampleIndex,timeUs:point[0],amplitude:point[1],sampleIntervalSeconds:1/segment.sampleRateHz,arrivalIndex:p.arrivalIndex,phase:a?.phase??'Unidentified',uncertaintySeconds:p.uncertaintySeconds,polarity:p.polarity,residualSeconds:a?(point[0]-a.timeUs)/1e6:null,method:'Operator sample selection; phase and polarity are unverified interpretations'};});
}
export class PhaseAnalysis{
 constructor(instruments){this.instruments=instruments;this.store=instruments.store;}
 events(input){const source=this.instruments.get(input.waveformId),asOf=Number(input.asOf),mode=input.mode??'catalog-replay';this.instruments.context(source,asOf,mode);if(!Number.isFinite(asOf)||asOf>Date.now()+1000)throw new Error('Choose an elapsed cutoff');const start=source.segments.reduce((t,s)=>Math.min(t,s.samples[0]?.[0]??Infinity),Infinity)/1000,end=source.segments.reduce((t,s)=>Math.max(t,s.samples.at(-1)?.[0]??-Infinity),-Infinity)/1000;const events=this.store.events({asOf,start:start-7200000,strict:mode==='strict',associate:false}).filter(e=>e.type==='earthquake'&&e.time<=end);return {events:events.slice(0,500),total:events.length,policy:'Stored catalog earthquakes from two hours before recording start through its end; not established source associations.'};}
 event(input){const asOf=Number(input.asOf),mode=input.mode??'catalog-replay';if(!Number.isFinite(asOf)||asOf>Date.now()+1000||!['strict','catalog-replay'].includes(mode))throw new Error('Choose an elapsed analysis cutoff');const event=this.store.events({asOf,strict:mode==='strict',associate:false}).find(e=>e.id===input.eventId);if(!event||event.type!=='earthquake')throw new Error('Select a catalog earthquake available at this cutoff');return {event,asOf,mode};}
 async calculate(input){const source=this.instruments.get(input.waveformId),{event,asOf,mode}=this.event(input);if(!['waveform','correction'].includes(source.kind)||!source.summary.samples)throw new Error('Choose a nonempty saved recording');this.instruments.context(source,asOf,mode);const phases=input.phases,model=input.model;if(!['iasp91','ak135'].includes(model)||!Array.isArray(phases)||!phases.length||phases.length>10||new Set(phases).size!==phases.length||phases.some(p=>!supported.includes(p)))throw new Error('Choose iasp91 or ak135 and 1–10 distinct supported phases');const query={waveformId:source.id,eventId:event.id,eventHash:hash(event),model,phases},key=hash({version:VERSION,query}),old=this.store.db.prepare("SELECT body FROM instrument_records WHERE kind='phase' AND query_hash=?").get(key);if(old){const record=JSON.parse(old.body);this.context(record,asOf,mode);return {...record,reused:true};}if(this.instruments.busy)throw new Error('An instrument request is already running');this.instruments.busy=true;
  try{const computed=await instrumentResponse({model,phases,event,station:source.station},'phase'),times=source.segments.flatMap(s=>s.samples.map(p=>p[0])),start=times.reduce((a,b)=>Math.min(a,b),Infinity),end=times.reduce((a,b)=>Math.max(a,b),-Infinity),runs=waveformRuns(source,true,1),arrivals=computed.arrivals.map(a=>{const timeUs=Math.round(event.time*1000+a.timeSeconds*1e6);return {...a,timeUs,inRecordingInterval:timeUs>=start&&timeUs<=end,inRecordedRun:runs.some(r=>timeUs>=r.startUs&&timeUs<=r.endUs)};});return this.save({...computed,arrivals,kind:'phase',version:VERSION,query,event,station:source.station,createdAt:Date.now(),parentId:null,picks:[],summary:{arrivals:arrivals.length,arrivalsInInterval:arrivals.filter(a=>a.inRecordingInterval).length,manualPicks:0,units:source.summary.units},provenance:{inputCutoff:asOf,mode,eventHash:hash(event),sourceId:source.id,policy:'Frozen catalog revision and operator-selected recording; comparison is a hypothesis, not an established association.'}},key);}finally{this.instruments.busy=false;}}
 save(body,key){const id=hash(body);this.store.db.prepare('INSERT INTO instrument_records VALUES(?,?,?,?,?)').run(id,'phase',body.createdAt,key,JSON.stringify({...body,id}));return {...body,id};}
 annotate(input){const parent=this.instruments.get(input.phaseId,'phase'),asOf=Number(input.asOf),mode=input.mode??'catalog-replay';this.context(parent,asOf,mode);if(this.history(parent).length>=1000)throw new Error('This annotation chain reached 1000 revisions; create a fresh comparison');if(asOf>Date.now()+1000)throw new Error('Choose an elapsed analysis cutoff');const source=this.instruments.get(parent.query.waveformId),picks=phasePicks(source,parent.arrivals,input.picks),key=hash({version:VERSION,parentId:parent.id,picks}),old=this.store.db.prepare("SELECT body FROM instrument_records WHERE kind='phase' AND query_hash=?").get(key);if(old){const record=JSON.parse(old.body);this.context(record,asOf,mode);return {...record,reused:true};}const {id,...body}=parent;return this.save({...body,parentId:id,picks,summary:{...parent.summary,manualPicks:picks.length},createdAt:Date.now()},key);}
 history(record){const parents=[],seen=new Set([record.id]);let current=record;while(current.parentId){if(seen.has(current.parentId)||parents.length>=1000)throw new Error('Invalid or excessive phase annotation ancestry');const parent=this.instruments.get(current.parentId,'phase'),{id,...body}=parent;if(hash(body)!==id||parent.query.waveformId!==record.query.waveformId||parent.query.eventHash!==record.query.eventHash||hash(parent.arrivals)!==hash(record.arrivals)||parent.createdAt>current.createdAt)throw new Error('Phase annotation parent integrity mismatch');seen.add(id);parents.push(parent);current=parent;}return parents;}
 context(record,asOf,mode){const source=this.instruments.get(record.query.waveformId),evidence=this.instruments.context(source,asOf,mode);if(record.event.time>asOf||mode==='strict'&&(record.createdAt>asOf||record.event.observedAt>asOf))throw new Error('This phase comparison was unavailable at the requested cutoff');this.history(record);const {id,...body}=record;if(hash(body)!==id||hash(record.event)!==record.query.eventHash)throw new Error('Phase comparison integrity mismatch');return {id,cutoffUtc:new Date(asOf).toISOString(),createdAt:new Date(record.createdAt).toISOString(),event:{...record.event,time: new Date(record.event.time).toISOString()},model:record.query.model,distanceDegrees:record.distanceDegrees,receiverDepthKm:record.receiverDepthKm,station:record.station,source:evidence,summary:record.summary,arrivals:record.arrivals.map(a=>({...a,timeUtc:waveformUtc(a.timeUs)})),picks:record.picks.map(p=>({...p,timeUtc:waveformUtc(p.timeUs)})),implementation:record.implementation,limitations:record.limitations,policy:record.provenance.policy};}
}
