import {readFileSync} from 'node:fs';
import {hash,canonical} from './store.mjs';
import {generate,baselines,validateConfig,scoreForecast,VERSION} from './engine.mjs';
import {SCORING_VERSION} from './resolution-reviews.mjs';
import {coverageComplete} from './import-jobs.mjs';
import {DAY,circleBounds} from './geo.mjs';
const GRACE=300000,FRESH=900000,ENGINES=['DS','Recent-rate','Null'];
const scientificKeys=['catalogProvider','triggerDepth','minMagnitude','lookbackDays','windowDays','radiusKm','magnitudeTolerance','magnitudeMode','deepEscalation','maxTargets','rules'];
const files=['server/prospective.mjs','server/engine.mjs','server/routes.mjs','server/geo.mjs','server/store.mjs','server/import-jobs.mjs','server/resolution-reviews.mjs'];
const date=t=>new Date(t).toISOString();
const frozenBody=r=>{const {id,...body}=r;return body;};
const metrics=forecasts=>ENGINES.map(engine=>{const values=forecasts.filter(f=>f.engine===engine),resolved=values.filter(f=>f.result.status!=='AMBIGUOUS'),hits=values.filter(f=>f.result.status==='HIT');return {engine,forecasts:values.length,resolved:resolved.length,hits:hits.length,partial:values.filter(f=>f.result.status==='PARTIAL HIT').length,misses:values.filter(f=>f.result.status==='MISS').length,ambiguous:values.length-resolved.length,fullHitFraction:resolved.length?hits.length/resolved.length:null};});
export class ProspectiveExperiments{
 constructor(store){this.store=store;this.lastError=null;const sourceFiles=Object.fromEntries(files.map(file=>[file,readFileSync(file,'utf8')]));this.implementation={version:'prospective-protocol-0.1.0',engineVersion:VERSION,scoringVersion:SCORING_VERSION,node:process.version,sourceHashes:Object.fromEntries(files.map(file=>[file,hash(sourceFiles[file])])),sourceFiles};this.runtimeHash=hash(this.implementation);
  store.db.exec(`CREATE TABLE IF NOT EXISTS prospective_protocols(id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,spec_hash TEXT UNIQUE NOT NULL,body TEXT NOT NULL);
   CREATE TABLE IF NOT EXISTS prospective_slots(protocol_id TEXT REFERENCES prospective_protocols(id),ordinal INTEGER,id TEXT UNIQUE NOT NULL,body TEXT NOT NULL,PRIMARY KEY(protocol_id,ordinal));
   CREATE TABLE IF NOT EXISTS prospective_assessments(protocol_id TEXT,ordinal INTEGER,id TEXT UNIQUE NOT NULL,body TEXT NOT NULL,PRIMARY KEY(protocol_id,ordinal),FOREIGN KEY(protocol_id,ordinal) REFERENCES prospective_slots(protocol_id,ordinal));
   CREATE TABLE IF NOT EXISTS prospective_stops(protocol_id TEXT PRIMARY KEY REFERENCES prospective_protocols(id),id TEXT UNIQUE NOT NULL,body TEXT NOT NULL);`);
  for(const table of ['prospective_protocols','prospective_slots','prospective_assessments','prospective_stops'])for(const operation of ['UPDATE','DELETE'])store.db.exec(`CREATE TRIGGER IF NOT EXISTS frozen_${table}_${operation.toLowerCase()} BEFORE ${operation} ON ${table} BEGIN SELECT RAISE(ABORT,'Prospective experiment records are immutable'); END;`);
 }
 preview(input,config,routes,boundaryPoints){
  validateConfig(config);const name=String(input.name??'').trim(),hypothesis=String(input.hypothesis??'').trim(),start=typeof input.start==='number'?input.start:Date.parse(input.start),issuances=Number(input.issuances),stepDays=Number(input.stepDays),settleDays=Number(input.settleDays);
  if(!name||name.length>120||!hypothesis||hypothesis.length>2000)throw new Error('Provide a name up to 120 characters and a hypothesis up to 2000 characters');
  if(!Number.isSafeInteger(start)||start<Date.now()+120000||start>Date.now()+365*DAY||!Number.isInteger(issuances)||issuances<1||issuances>90||!Number.isInteger(stepDays)||stepDays<1||stepDays>30||stepDays*(issuances-1)>365||!Number.isInteger(settleDays)||settleDays<1||settleDays>7)throw new Error('Choose a start at least two minutes ahead, 1–90 issuances every 1–30 days over at most one year, and a 1–7 day assessment delay');
  if(config.catalogProvider!=='USGS'||config.lookbackDays>30)throw new Error('Scheduled experiments require the live USGS catalog and a lookback of at most 30 days');
  const spec={name,hypothesis,start,issuances,stepDays,settleDays,config:Object.fromEntries(scientificKeys.map(k=>[k,structuredClone(config[k])])),routes:structuredClone(routes),boundaryPoints:structuredClone(boundaryPoints),boundaryHash:hash(boundaryPoints),implementation:this.implementation,runtimeHash:this.runtimeHash,engines:ENGINES,controlSeed:42,graceMs:GRACE,maxFeedAgeMs:FRESH,scope:'Global generated targets and matched global controls',
   selection:'Issue every ranked target under the frozen rules and maxTargets cap; one matched Recent-rate and one uniform-area Null control per DS target. No manual target selection or global-ledger deduplication within this experiment.',
   timing:'The host must be running. Start processing within five minutes of each scheduled time; use only revisions received by the actual input cutoff. Forecast validity begins at actual issuance after computation. Never backdate or catch up a missed issuance.',
   inputPolicy:'One USGS catalog, strict local reception history. Retained older observations remain available for analogues. A fresh successful month feed is required; catalog retrieval coverage does not prove uniform earthquake detection completeness.',
   outcomePolicy:'Assess once, at the issued window end plus the fixed delay, within a five-minute grace period. Freeze then-available observations, retrieval coverage and scoring results. Missed assessments remain missing; later general-ledger reviews do not change this primary result.',
   primary:'Equal-issuance mean of DS full-hit fraction minus its matched Recent-rate full-hit fraction, using only issuance groups with all three engines fully assessed. Empty, skipped, missed and incompletely assessed groups remain disclosed and excluded.',
   secondary:'Analogous DS-minus-Null contrast and per-engine full/partial/miss/ambiguous counts. Partial hits are not full hits. No population recall, probability, Brier score, information gain or significance is inferred from these envelope forecasts.',
   stopping:'The planned number of issuances is fixed. Stop is irreversible and records cancellation of all remaining unissued slots; already-issued outcome assessments continue. Data-dependent stopping can bias descriptive comparisons.',
   limitations:['The configured DS route graph is illustrative, not a verified canonical Dutchsinse map.','Overlapping windows, targets and aftershocks create dependent observations; no independent-trial confidence interval or p-value is reported.','All local histories and hashes depend on this installation and its clock; no external timestamp authority is supplied.','Fixed operational exclusions may bias the analyzed subset; inspect every skipped or incomplete slot before interpreting differences.']};
  return {previewHash:hash(spec),spec};
 }
 register(input,config,routes,boundaryPoints){const existing=this.store.db.prepare('SELECT id FROM prospective_protocols WHERE spec_hash=?').get(String(input.previewHash));if(existing)return this.get(existing.id);const preview=this.preview(input,config,routes,boundaryPoints);if(input.previewHash!==preview.previewHash)throw new Error('Protocol inputs or implementation changed; review a fresh preview before registering');if(this.list().filter(p=>!['COMPLETE','CANCELLED'].includes(p.summary.state)).length>=3)throw new Error('This local runtime supports at most three unfinished registered experiments');const body={registeredAt:Date.now(),spec:preview.spec},id=hash(body);this.store.db.prepare('INSERT INTO prospective_protocols VALUES(?,?,?,?)').run(id,body.registeredAt,preview.previewHash,canonical(body));return this.get(id);}
 get(id){const row=this.store.db.prepare('SELECT body FROM prospective_protocols WHERE id=?').get(String(id));if(!row)throw new Error('Prospective protocol not found');const body=JSON.parse(row.body);if(hash(body)!==id)throw new Error('Prospective protocol integrity mismatch');return {id,...body};}
 records(table,id){return this.store.db.prepare(`SELECT id,body FROM ${table} WHERE protocol_id=? ${table==='prospective_stops'?'':'ORDER BY ordinal'}`).all(id).map(r=>({id:r.id,...JSON.parse(r.body)}));}
 view(id){const protocol=this.get(id),slots=this.records('prospective_slots',id),assessments=this.records('prospective_assessments',id),stop=this.records('prospective_stops',id)[0]??null,issued=slots.filter(s=>s.status==='ISSUED'),complete=assessments.filter(a=>a.status==='SCORED'&&a.complete),contrast=engine=>complete.length?complete.reduce((sum,a)=>sum+a.metrics.find(m=>m.engine==='DS').fullHitFraction-a.metrics.find(m=>m.engine===engine).fullHitFraction,0)/complete.length:null,remaining=protocol.spec.issuances-slots.length,pending=issued.length-assessments.length;
  return {protocol,slots,assessments,stop,summary:{state:remaining?'SCHEDULED':pending?(stop?'STOPPED · ASSESSING':'ASSESSING'):(stop?'CANCELLED':'COMPLETE'),planned:protocol.spec.issuances,recordedSlots:slots.length,remaining,issuedGroups:issued.length,emptyGroups:slots.filter(s=>s.status==='NO_TARGETS').length,skippedGroups:slots.filter(s=>!['ISSUED','NO_TARGETS'].includes(s.status)).length,pendingAssessments:pending,completeGroups:complete.length,incompleteGroups:assessments.filter(a=>!a.complete).length,primaryDsMinusRecent:contrast('Recent-rate'),secondaryDsMinusNull:contrast('Null'),runtimeMatches:protocol.spec.runtimeHash===this.runtimeHash},integrity:this.verify(id)};
 }
 list(){return this.store.db.prepare('SELECT id FROM prospective_protocols ORDER BY created_at DESC').all().map(({id})=>{const v=this.view(id);return {id,name:v.protocol.spec.name,registeredAt:v.protocol.registeredAt,start:v.protocol.spec.start,summary:v.summary,integrity:v.integrity};});}
 append(table,protocolId,ordinal,body){const id=hash(body);this.store.db.prepare(`INSERT INTO ${table} VALUES(${table==='prospective_stops'?'?,?,?':'?,?,?,?'})`).run(...(table==='prospective_stops'?[protocolId,id,canonical(body)]:[protocolId,ordinal,id,canonical(body)]));return {id,...body};}
 stop(id){const p=this.get(id),old=this.records('prospective_stops',id)[0];if(old)return old;const now=Date.now();this.store.db.exec('BEGIN IMMEDIATE');try{const stop=this.append('prospective_stops',id,null,{protocolId:id,recordedAt:now,reason:'Operator stopped all remaining unissued slots; existing assessments continue'});const done=new Set(this.records('prospective_slots',id).map(s=>s.ordinal));for(let ordinal=0;ordinal<p.spec.issuances;ordinal++)if(!done.has(ordinal))this.append('prospective_slots',id,ordinal,{protocolId:id,ordinal,scheduledAt:p.spec.start+ordinal*p.spec.stepDays*DAY,recordedAt:now,status:'CANCELLED',reason:stop.reason,forecastIds:[]});this.store.db.exec('COMMIT');return stop;}catch(e){this.store.db.exec('ROLLBACK');throw e;}}
 fresh(feed,now){return feed.status==='live'&&Number.isFinite(feed.fetchedAt)&&Number.isFinite(feed.generated)&&feed.fetchedAt<=now+1000&&feed.generated<=now+1000&&now-feed.fetchedAt<=FRESH&&now-feed.generated<=FRESH;}
 tick(feed){this.lastError=null;let changes=0;try{for(const {id}of this.store.db.prepare('SELECT id FROM prospective_protocols').all()){const p=this.get(id);if(!this.verify(id).valid)throw new Error('Protocol or ledger integrity failed; scheduled processing withheld');const slots=this.records('prospective_slots',id),known=new Set(slots.map(s=>s.ordinal));for(let ordinal=0;ordinal<p.spec.issuances;ordinal++){const now=Date.now(),due=p.spec.start+ordinal*p.spec.stepDays*DAY;if(known.has(ordinal)||due>now)continue;let status=null,reason=null;if(now>due+GRACE){status='MISSED_WINDOW';reason='Host did not complete issuance within its scheduled grace period';}else if(p.spec.runtimeHash!==this.runtimeHash){status='SKIPPED_VERSION';reason='Frozen scientific implementation or Node runtime differs';}else if(!this.fresh(feed,now)){continue;}
    if(status){this.append('prospective_slots',id,ordinal,{protocolId:id,ordinal,scheduledAt:due,recordedAt:now,status,reason,forecastIds:[]});changes++;continue;}
    const events=this.store.events({asOf:now,strict:true,provider:'USGS'}),analysis=generate(events,now,p.spec.config,p.spec.routes,p.spec.boundaryPoints),targets=[...analysis.candidates,...baselines(analysis,events,p.spec.controlSeed)],issuedAt=Date.now();if(issuedAt>due+GRACE)continue;
    this.store.db.exec('BEGIN IMMEDIATE');try{const snapshotId=this.store.snapshot(events,now,'strict-prospective-protocol'),forecasts=this.store.issue(targets.map(c=>({...c,validFrom:issuedAt,validUntil:issuedAt+p.spec.config.windowDays*DAY})),{snapshotId,config:p.spec.config,routeConfig:p.spec.routes,mode:'prospective',issuedAt,status:'ISSUED',protocolId:id,protocolOrdinal:ordinal,protocolHash:id},{transaction:false});this.append('prospective_slots',id,ordinal,{protocolId:id,ordinal,scheduledAt:due,recordedAt:issuedAt,inputCutoff:now,snapshotId,feedReceipt:structuredClone(feed),status:forecasts.length?'ISSUED':'NO_TARGETS',reason:forecasts.length?'All selected targets and matched controls issued atomically':'Frozen rules generated no targets',forecastIds:forecasts.map(f=>f.id),assessmentDueAt:forecasts.length?issuedAt+(p.spec.config.windowDays+p.spec.settleDays)*DAY:null});this.store.db.exec('COMMIT');changes++;}catch(e){this.store.db.exec('ROLLBACK');throw e;}
   }
   const assessed=new Set(this.records('prospective_assessments',id).map(a=>a.ordinal));for(const slot of this.records('prospective_slots',id).filter(s=>s.status==='ISSUED'&&!assessed.has(s.ordinal))){const now=Date.now();if(now<slot.assessmentDueAt)continue;const missed=now>slot.assessmentDueAt+GRACE,mismatch=p.spec.runtimeHash!==this.runtimeHash;if(!missed&&!mismatch&&!this.fresh(feed,now))continue;
    if(missed||mismatch){this.append('prospective_assessments',id,slot.ordinal,{protocolId:id,ordinal:slot.ordinal,slotId:slot.id,recordedAt:now,status:missed?'MISSED_ASSESSMENT':'SKIPPED_VERSION',complete:false,reason:missed?'Outcome assessment grace period elapsed; no retrospective replacement':'Frozen scoring implementation or Node runtime differs',metrics:[]});changes++;continue;}
    const all=this.store.events({asOf:now,strict:true,provider:'USGS'}),coverage=structuredClone(this.store.get('coverage',[])),forecasts=this.store.ledger().filter(f=>slot.forecastIds.includes(f.id)),window=forecasts[0],events=all.filter(e=>e.time>=window.validFrom&&e.time<=window.validUntil),results=forecasts.map(f=>{const coverageQuery={provider:'USGS',start:f.validFrom,end:f.validUntil,minMagnitude:f.magnitude.min-.5,bounds:circleBounds(f.center.lat,f.center.lon,f.radiusKm)},complete=coverageComplete(coverage,coverageQuery);return {forecastId:f.id,forecastHash:f.hash,engine:f.engine,coverageQuery,coverageComplete:complete,result:scoreForecast(f,events,now,complete)};});
    this.store.db.exec('BEGIN IMMEDIATE');try{const snapshotId=this.store.snapshot(events,now,'prospective-protocol-outcomes');this.append('prospective_assessments',id,slot.ordinal,{protocolId:id,ordinal:slot.ordinal,slotId:slot.id,recordedAt:now,observationCutoff:now,status:'SCORED',complete:results.every(r=>r.coverageComplete),scoringVersion:SCORING_VERSION,snapshotId,coverage,feedReceipt:structuredClone(feed),results,metrics:metrics(results),reason:'One assessment at the fixed delay; later ledger reviews are separate'});this.store.db.exec('COMMIT');changes++;}catch(e){this.store.db.exec('ROLLBACK');throw e;}
   }
  }}catch(e){this.lastError=e.message;throw e;}return {changes};
 }
 verify(id){try{const p=this.get(id);if(hash(p.spec.implementation)!==p.spec.runtimeHash||Object.entries(p.spec.implementation.sourceFiles).some(([file,source])=>hash(source)!==p.spec.implementation.sourceHashes[file])||hash(p.spec.boundaryPoints)!==p.spec.boundaryHash)throw new Error('Frozen implementation or reference hash mismatch');if(!this.store.verify().valid)return {valid:false,reason:'Forecast ledger or snapshot failed integrity'};let records=1;const forecasts=new Map(this.store.ledger().map(f=>[f.id,f])),slots=new Map();for(const table of ['prospective_slots','prospective_assessments','prospective_stops'])for(const r of this.records(table,id)){if(hash(frozenBody(r))!==r.id||r.protocolId!==id)throw new Error('Experiment record hash or protocol link mismatch');records++;if(table==='prospective_slots'){if(r.ordinal<0||r.ordinal>=p.spec.issuances||r.scheduledAt!==p.spec.start+r.ordinal*p.spec.stepDays*DAY)throw new Error('Slot schedule mismatch');slots.set(r.ordinal,r);for(const fid of r.forecastIds){const f=forecasts.get(fid);if(!f||f.protocolId!==id||f.protocolOrdinal!==r.ordinal||f.snapshotId!==r.snapshotId)throw new Error('Issued forecast link mismatch');}}if(table==='prospective_assessments'&&r.slotId!==slots.get(r.ordinal)?.id)throw new Error('Assessment slot link mismatch');if(r.snapshotId){const saved=this.store.db.prepare('SELECT body FROM snapshots WHERE id=?').get(r.snapshotId);if(!saved||hash(JSON.parse(saved.body))!==r.snapshotId)throw new Error('Experiment snapshot mismatch');}}
   return {valid:true,records,scope:'Immutable local protocol, schedule, forecast and assessment links; no external timestamp authority'};
  }catch(e){return {valid:false,reason:e.message};}}
 export(id){const view=this.view(id),ids=new Set(view.slots.flatMap(s=>s.forecastIds)),forecasts=this.store.ledger().filter(f=>ids.has(f.id)),snapshotIds=new Set([...view.slots,...view.assessments].map(r=>r.snapshotId).filter(Boolean)),snapshots=[...snapshotIds].map(id=>({id,...JSON.parse(this.store.db.prepare('SELECT body FROM snapshots WHERE id=?').get(id).body)}));const forecastProofs=[...ids].map(id=>{const r=this.store.db.prepare('SELECT body,prev_hash,hash FROM forecasts WHERE id=?').get(id);return {id,body:JSON.parse(r.body),previousHash:r.prev_hash,hash:r.hash};});return {...view,forecasts,forecastProofs,snapshots};}
}
export function prospectiveContext(view,asOf){if(!Number.isFinite(asOf)||view.protocol.registeredAt>asOf||view.slots.some(s=>s.recordedAt>asOf)||view.assessments.some(a=>a.recordedAt>asOf)||view.stop?.recordedAt>asOf||!view.integrity.valid)throw new Error('This protocol view is unavailable at the requested cutoff');const p=view.protocol;return {id:p.id,name:p.spec.name,hypothesis:p.spec.hypothesis,registeredAt:date(p.registeredAt),schedule:{start:date(p.spec.start),issuances:p.spec.issuances,stepDays:p.spec.stepDays,settleDays:p.spec.settleDays,graceMinutes:5},config:p.spec.config,engines:p.spec.engines,scope:p.spec.scope,primary:p.spec.primary,outcomePolicy:p.spec.outcomePolicy,stopping:p.spec.stopping,summary:view.summary,slots:view.slots.map(s=>({ordinal:s.ordinal+1,scheduledAt:date(s.scheduledAt),recordedAt:date(s.recordedAt),status:s.status,reason:s.reason,forecastCount:s.forecastIds.length})),assessments:view.assessments.map(a=>({ordinal:a.ordinal+1,recordedAt:date(a.recordedAt),status:a.status,complete:a.complete,metrics:a.metrics})),limitations:p.spec.limitations};}
