import {hash,canonical} from './store.mjs';
import {scoreForecast} from './engine.mjs';
import {coverageComplete} from './import-jobs.mjs';
import {circleBounds,boundsContain,distance} from './geo.mjs';
export const SCORING_VERSION='frozen-envelope-0.1';
const baseline=f=>hash({forecastId:f.id,forecastHash:f.hash,originalResolution:f.resolution});
const resultValue=result=>{const {evaluatedAt,...value}=result;return value;};
function coverageWitness(coverage,query){
 const eligible=coverage.filter(c=>c.provider===query.provider&&c.minMagnitude<=query.minMagnitude&&c.end>=query.start&&c.start<=query.end&&boundsContain(c.bounds,query.bounds)).sort((a,b)=>a.start-b.start||b.end-a.end||hash(a).localeCompare(hash(b))),witness=[];let reached=query.start;
 for(const c of eligible){if(c.start>reached)break;if(c.end<=reached)continue;witness.push(c);reached=c.end;if(reached>=query.end)break;}return witness;
}
export class ResolutionReviews{
 constructor(store){this.store=store;store.db.exec(`CREATE TABLE IF NOT EXISTS resolution_reviews(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT UNIQUE NOT NULL,forecast_id TEXT NOT NULL REFERENCES forecasts(id),created_at INTEGER NOT NULL,body TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS review_forecasts ON resolution_reviews(forecast_id,seq);
 CREATE TRIGGER IF NOT EXISTS frozen_review_update BEFORE UPDATE ON resolution_reviews BEGIN SELECT RAISE(ABORT,'Resolution reviews are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS frozen_review_delete BEFORE DELETE ON resolution_reviews BEGIN SELECT RAISE(ABORT,'Resolution reviews are immutable'); END;`);}
 history(forecastId){const f=this.store.ledger().find(f=>f.id===String(forecastId));if(!f)throw new Error('Frozen forecast not found');const entries=this.store.db.prepare('SELECT id,body FROM resolution_reviews WHERE forecast_id=? ORDER BY seq').all(f.id).map(r=>({id:r.id,...JSON.parse(r.body)}));return {forecast:f,originalResolution:f.resolution,originalRecordedAt:this.store.db.prepare('SELECT created_at FROM resolutions WHERE forecast_id=?').get(f.id)?.created_at??null,entries};}
 attach(forecasts){const latest=new Map(this.store.db.prepare('SELECT forecast_id,id,body,count FROM (SELECT *,count(*) OVER(PARTITION BY forecast_id) AS count,row_number() OVER(PARTITION BY forecast_id ORDER BY seq DESC) AS position FROM resolution_reviews) WHERE position=1').all().map(r=>[r.forecast_id,r]));return forecasts.map(f=>{const row=latest.get(f.id),review=row?JSON.parse(row.body):null;return {...f,latestResolution:review?.result??f.resolution,reviewId:row?.id??null,reviewCount:row?.count??0,lastReviewedAt:review?.createdAt??null};});}
 review(forecastId=null){if(!this.verify(forecastId).valid)throw new Error('Forecast or review integrity failed; no assessment was appended');const now=Date.now(),forecasts=this.store.ledger();if(forecastId&&!forecasts.some(f=>f.id===String(forecastId)))throw new Error('Frozen forecast not found');const events=this.store.events({asOf:now,strict:true}),coverage=this.store.get('coverage',[]),summary={resolved:0,reviewed:0,changed:0,unchanged:0,awaitingCoverage:0,pending:0,ids:[]};
  // ponytail: scan the retained catalog per forecast; move to indexed/worker evaluation when this ledger outgrows interactive checks.
  for(const f of forecasts.filter(f=>!forecastId||f.id===String(forecastId))){if(f.validUntil>now){summary.pending++;continue;}const previousRow=this.store.db.prepare('SELECT id,body FROM resolution_reviews WHERE forecast_id=? ORDER BY seq DESC LIMIT 1').get(f.id),previous=previousRow?JSON.parse(previousRow.body):null,query={provider:f.catalogProvider??f.config?.catalogProvider??'USGS',start:f.validFrom,end:f.validUntil,minMagnitude:f.magnitude.min-.5,bounds:circleBounds(f.center.lat,f.center.lon,f.radiusKm)},witness=coverageWitness([...coverage,...previous?.coverage??[]],query),complete=coverageComplete(witness,query);
   if(!complete&&!f.resolution){summary.awaitingCoverage++;continue;}
   const outcomes=events.filter(e=>(e.provider??'USGS')===query.provider&&e.type==='earthquake'&&e.time>=f.validFrom&&e.time<=f.validUntil&&e.mag>=f.magnitude.min-.5&&e.mag<=f.magnitude.max+.5&&distance(e,f.center)<=f.radiusKm).sort((a,b)=>a.id.localeCompare(b.id)),snapshot={asOf:f.validUntil,mode:'resolution-catalog',events:outcomes},snapshotId=hash(snapshot),inputHash=hash({forecastHash:f.hash,snapshotId,complete,scoringVersion:SCORING_VERSION});
   if(previous?.inputHash===inputHash){summary.unchanged++;continue;}const result=scoreForecast(f,outcomes,now,complete);if(!result)continue;const old=previous?.result??f.resolution,changed=!!old&&hash(resultValue(old))!==hash(resultValue(result));
   this.store.db.exec('BEGIN IMMEDIATE');try{this.store.snapshot(outcomes,f.validUntil,'resolution-catalog');if(!f.resolution){this.store.resolve(f.id,result);f.resolution=result;summary.resolved++;}
    const record={forecastId:f.id,forecastHash:f.hash,originalResolutionHash:hash(f.resolution),previousHash:previousRow?.id??baseline(f),createdAt:now,observationCutoff:now,inputHash,snapshotId,scoringVersion:SCORING_VERSION,coverage:witness,coverageQuery:query,coverageComplete:complete,result,changedFromPrevious:changed,previousStatus:old?.status??null,reason:!old?'Initial assessment with retained outcome evidence':changed?'Assessment changed under the frozen criteria using the currently retained catalog and coverage':'Outcome evidence recorded; assessment retained',policy:'The issued forecast and original resolution are unchanged. This assessment uses revisions received by its observation cutoff, not a reconstructed historical publication catalog.'};const id=hash(record);this.store.db.prepare('INSERT INTO resolution_reviews(id,forecast_id,created_at,body) VALUES(?,?,?,?)').run(id,f.id,now,canonical(record));this.store.db.exec('COMMIT');summary.reviewed++;if(changed)summary.changed++;summary.ids.push(id);
   }catch(e){this.store.db.exec('ROLLBACK');throw e;}
  }return summary;
 }
 get(id){const row=this.store.db.prepare('SELECT body FROM resolution_reviews WHERE id=?').get(String(id));if(!row)throw new Error('Resolution review not found');const body=JSON.parse(row.body);if(hash(body)!==String(id))throw new Error('Resolution review integrity mismatch');return {id:String(id),...body};}
 export(id){const review=this.get(id),{forecast,entries,originalRecordedAt}=this.history(review.forecastId),row=this.store.db.prepare('SELECT body FROM snapshots WHERE id=?').get(review.snapshotId);if(!row||hash(JSON.parse(row.body))!==review.snapshotId)throw new Error('Outcome snapshot integrity mismatch');return {review,forecast,originalRecordedAt,outcomeSnapshot:{id:review.snapshotId,...JSON.parse(row.body)},history:entries.slice(0,entries.findIndex(r=>r.id===review.id)+1),integrity:this.verify(review.forecastId)};}
 reproduce(id){const saved=this.export(id);if(!saved.integrity.valid)throw new Error('Resolution review chain failed integrity');if(saved.review.scoringVersion!==SCORING_VERSION)throw new Error('This scoring version is not supported');const complete=coverageComplete(saved.review.coverage,saved.review.coverageQuery),result=scoreForecast(saved.forecast,saved.outcomeSnapshot.events,saved.review.observationCutoff,complete);return {id:saved.review.id,identical:canonical(result)===canonical(saved.review.result),result,scoringVersion:SCORING_VERSION,coverageComplete:complete};}
 verify(forecastId=null){if(!this.store.verify().valid)return {valid:false,count:0,reason:'Forecast chain or input snapshot mismatch'};const forecasts=new Map(this.store.ledger().map(f=>[f.id,f])),heads=new Map(),snapshots=new Set();let count=0;for(const row of this.store.db.prepare('SELECT id,forecast_id,created_at,body FROM resolution_reviews '+(forecastId?'WHERE forecast_id=? ':'')+'ORDER BY seq').all(...(forecastId?[String(forecastId)]:[]))){const r=JSON.parse(row.body),f=forecasts.get(row.forecast_id);if(!f||hash(r)!==row.id||r.forecastId!==f.id||r.forecastHash!==f.hash||r.originalResolutionHash!==hash(f.resolution)||r.createdAt!==row.created_at||r.previousHash!==(heads.get(f.id)??baseline(f)))return {valid:false,count,brokenAt:row.id,reason:'Review chain or original resolution mismatch'};if(!snapshots.has(r.snapshotId)){const s=this.store.db.prepare('SELECT body FROM snapshots WHERE id=?').get(r.snapshotId);if(!s||hash(JSON.parse(s.body))!==r.snapshotId)return {valid:false,count,brokenAt:row.id,reason:'Outcome snapshot mismatch'};snapshots.add(r.snapshotId);}heads.set(f.id,row.id);count++;}return {valid:true,count,forecastCount:heads.size,scope:'Append-only per-forecast review chains, anchored to original results and outcome snapshots; no independent timestamp authority'};}
}
export function resolutionClassification(f,result){const event=result.event,magnitude=event?`M${event.mag} (${event.magType??'source scale unspecified'})`:null;return result.status==='PARTIAL HIT'?`PARTIAL HIT: ${magnitude} is outside M${f.magnitude.min}–${f.magnitude.max}, within the ±0.5 partial-hit tolerance.`:result.status==='HIT'?`HIT: ${magnitude} is inside M${f.magnitude.min}–${f.magnitude.max}.`:result.status==='AMBIGUOUS'?'AMBIGUOUS: outcome catalog coverage is incomplete.':'MISS: no event met the frozen full-hit or partial-hit criteria in the retained catalog.';}
const readableResult=(r,f)=>r?{status:r.status,reason:r.reason,spatialErrorKm:r.spatialErrorKm,absoluteErrorFromCentralMagnitude:r.magnitudeError,magnitudeErrorMeaning:`Absolute difference from central M${f.magnitude.central}; not distance outside the nominal envelope`,distanceOutsideNominalMagnitudeRange:r.event?Math.max(f.magnitude.min-r.event.mag,r.event.mag-f.magnitude.max,0):null,timingDays:r.timingDays,outcomeCutoff:Number.isFinite(r.evaluatedAt)?new Date(r.evaluatedAt).toISOString():null,event:r.event?{id:r.event.id,provider:r.event.provider,mag:r.event.mag,magType:r.event.magType??null,depth:r.event.depth,lat:r.event.lat,lon:r.event.lon,time:new Date(r.event.time).toISOString(),observedAt:Number.isFinite(r.event.observedAt)?new Date(r.event.observedAt).toISOString():null}:null}:null;
export function resolutionReviewEvidence(saved,asOf){const r=saved.review;if(!Number.isFinite(asOf)||r.createdAt>asOf||r.observationCutoff>asOf||!saved.integrity.valid)throw new Error('Resolution review unavailable at this observation cutoff');const f=saved.forecast;return {id:r.id,classificationText:resolutionClassification(f,r.result),forecast:{id:f.id,engine:f.engine,mode:f.mode,region:f.region,centerText:`${Math.abs(f.center.lat).toFixed(3)}° ${f.center.lat<0?'S':'N'}, ${Math.abs(f.center.lon).toFixed(3)}° ${f.center.lon<0?'W':'E'}`,radiusKm:f.radiusKm,magnitude:f.magnitude,validFrom:new Date(f.validFrom).toISOString(),validUntil:new Date(f.validUntil).toISOString()},originalResolution:readableResult(f.resolution,f),originalRecordedAt:Number.isFinite(saved.originalRecordedAt)?new Date(saved.originalRecordedAt).toISOString():null,currentReview:{result:readableResult(r.result,f),reason:r.reason,coverageComplete:r.coverageComplete,requiredMagnitudeFloor:r.coverageQuery.minMagnitude,observationCutoff:new Date(r.observationCutoff).toISOString(),changedFromPrevious:r.changedFromPrevious,previousStatus:r.previousStatus},reviewedAt:new Date(r.createdAt).toISOString(),history:saved.history.map(e=>({id:e.id,reviewedAt:new Date(e.createdAt).toISOString(),status:e.result.status,changedFromPrevious:e.changedFromPrevious})),outcomeEventCount:saved.outcomeSnapshot.events.length,policy:r.policy,limitations:['The forecast geometry, magnitude and window were never changed. The original assessment remains preserved.','A revision changes an assessment of the same forecast, not a newly issued forecast or an independent success.','Hindcasts do not contribute to the prospective leaderboard. Precision is not population recall or earthquake probability.','A matching current catalog event does not establish causation. AMBIGUOUS means insufficient recorded coverage, not a miss.','Only the saved review and its observation cutoff are supplied; do not invent later revisions.']};}
