import {hash} from './store.mjs';
import {retrieveSource} from './instruments.mjs';
export const VOLCANO_STATUS_URL='https://volcanoes.usgs.gov/vsc/api/volcanoApi/geojson';
export const STATUS_INTERVAL=15*60000;
const levels=['NORMAL','ADVISORY','WATCH','WARNING','UNASSIGNED'],colors=['GREEN','YELLOW','ORANGE','RED','UNASSIGNED'];
const text=v=>typeof v==='string'&&v.trim()?v.trim():null;
function sourceLink(value){if(!value)return null;const u=new URL(value);if(u.protocol!=='https:'||!/(^|\.)(usgs\.gov|alaska\.edu|volcano\.si\.edu)$/.test(u.hostname))throw new Error('Unexpected USGS volcano source link');return u.href;}
export function parseVolcanoStatus(raw){
 const data=JSON.parse(raw);if(data.type!=='FeatureCollection'||!Array.isArray(data.features)||!data.features.length||data.features.length>2000)throw new Error('Invalid USGS volcano status collection');
 const seen=new Set();return data.features.map(f=>{const p=f.properties??{},[lon,lat]=f.geometry?.coordinates??[],number=text(p.vnum),code=text(p.volcanoCd);if(f.geometry?.type!=='Point'||![lat,lon].every(Number.isFinite)||Math.abs(lat)>90||Math.abs(lon)>180||number!==null&&!/^\d{6}$/.test(number)||!code||!/^[a-z0-9]{2,16}$/i.test(code)||seen.has(code)||!text(p.volcanoName)||!levels.includes(p.alertLevel)||!colors.includes(p.colorCode))throw new Error('Invalid or duplicate USGS volcano status record');seen.add(code);
  const date=text(p.noticeId)?.match(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2})$/)?.[0];
  return {id:code,number,name:p.volcanoName,lat,lon,code,observatory:text(p.obs),region:text(p.region),alertLevel:p.alertLevel,aviationColor:p.colorCode,noticeId:text(p.noticeId),noticeTime:date&&Number.isFinite(Date.parse(date))?Date.parse(date):null,synopsis:text(p.noticeSynopsis),noticeUrl:sourceLink(p.noticeUrl),profileUrl:sourceLink(p.volcanoUrl),sourceAlertDate:text(p.alertDate),sourceColorDate:text(p.colorDate),longTermThreat:text(p.nvewsThreat)};
 }).sort((a,b)=>a.id.localeCompare(b.id));
}
export class VolcanoStatus{
 constructor(store){this.store=store;this.pending=null;this.controller=null;store.db.exec(`CREATE TABLE IF NOT EXISTS volcano_status_records(id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS volcano_status_checks(at INTEGER PRIMARY KEY,record_id TEXT NOT NULL REFERENCES volcano_status_records(id));
 CREATE TRIGGER IF NOT EXISTS frozen_volcano_status_update BEFORE UPDATE ON volcano_status_records BEGIN SELECT RAISE(ABORT,'Volcano status records are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS frozen_volcano_status_delete BEFORE DELETE ON volcano_status_records BEGIN SELECT RAISE(ABORT,'Volcano status records are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS frozen_volcano_check_update BEFORE UPDATE ON volcano_status_checks BEGIN SELECT RAISE(ABORT,'Volcano checks are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS frozen_volcano_check_delete BEFORE DELETE ON volcano_status_checks BEGIN SELECT RAISE(ABORT,'Volcano checks are immutable'); END;`);}
 get(id){const row=this.store.db.prepare('SELECT body FROM volcano_status_records WHERE id=?').get(String(id));if(!row)throw new Error('Saved volcano status not found');const record=JSON.parse(row.body);if(hash(record.raw)!==record.receipt.sha256||record.id!==hash({version:record.version,raw:record.raw})||record.createdAt!==record.receipt.fetchedAt||record.receipt.url!==VOLCANO_STATUS_URL||record.receipt.bytes!==Buffer.byteLength(record.raw)||hash(record.volcanoes)!==hash(parseVolcanoStatus(record.raw)))throw new Error('Volcano status integrity mismatch');return record;}
 view(asOf=Date.now(),id=null){if(!Number.isFinite(asOf)||asOf>Date.now()+1000)throw new Error('Choose an elapsed volcano status cutoff');const check=this.store.db.prepare('SELECT at,record_id FROM volcano_status_checks WHERE at<=? '+(id?'AND record_id=? ':'')+'ORDER BY at DESC LIMIT 1').get(...(id?[asOf,String(id)]:[asOf]));const savedFeed=this.store.get('volcano-status-feed',{}),feed=savedFeed.attemptedAt<=asOf?savedFeed:{};if(!check)return {available:false,asOf,reason:'No USGS volcano status was received by this cutoff.',feed,busy:!!this.pending};const record=this.get(check.record_id);const {raw,...summary}=record;return {available:true,...summary,checkedAt:check.at,asOf,stale:asOf-check.at>STATUS_INTERVAL*2,feed,busy:!!this.pending};}
 async refresh({force=false}={}){if(this.pending)return this.pending;const feed=this.store.get('volcano-status-feed',{}),now=Date.now();if(now-(feed.attemptedAt??0)<(force?30000:STATUS_INTERVAL))return this.view();this.store.set('volcano-status-feed',{...feed,attemptedAt:now});this.controller=new AbortController();this.pending=(async()=>{try{const source=await retrieveSource(VOLCANO_STATUS_URL,'USGS volcano status',{signal:this.controller.signal}),volcanoes=parseVolcanoStatus(source.raw),version='usgs-volcano-status-0.1',id=hash({version,raw:source.raw}),record={id,version,createdAt:source.receipt.fetchedAt,...source,volcanoes,provenance:{provider:'USGS Volcano Hazards Program',url:VOLCANO_STATUS_URL,coverage:'U.S. volcanoes listed by the USGS API; not global coverage.',intervalMinutes:15,policy:'Official volcano ground alert and aviation code are separate source fields. UNASSIGNED is not normal. Notice dates may predate a successful poll; source date strings without time zones are preserved verbatim. Long-term NVEWS threat is not current alert level. No earthquake causation or forecast factor is inferred.'}};
   this.store.db.exec('BEGIN');try{this.store.db.prepare('INSERT OR IGNORE INTO volcano_status_records VALUES(?,?,?)').run(id,record.createdAt,JSON.stringify(record));this.store.db.prepare('INSERT INTO volcano_status_checks VALUES(?,?)').run(source.receipt.fetchedAt,id);this.store.set('volcano-status-feed',{attemptedAt:now,succeededAt:source.receipt.fetchedAt,error:null});this.store.db.exec('COMMIT');}catch(e){this.store.db.exec('ROLLBACK');throw e;}return {...this.view(),busy:false};
  }catch(e){this.store.set('volcano-status-feed',{...feed,attemptedAt:now,error:e.message});throw e;}finally{this.pending=null;this.controller=null;}})();return this.pending;}
 async shutdown(){this.controller?.abort();await this.pending?.catch(()=>{});}
}
export function volcanoStatusEvidence(status,code,asOf){if(!status.available||!Number.isFinite(asOf)||status.createdAt>asOf||status.checkedAt>asOf)throw new Error('Volcano status is unavailable at this observation cutoff');const selected=status.volcanoes.find(v=>v.code===String(code));if(!selected)throw new Error('Select a volcano present in the saved status');if(selected.noticeTime!==null&&selected.noticeTime>asOf)throw new Error('The source notice is dated after this cutoff');return {id:status.id,selected:{...selected,noticeTime:selected.noticeTime===null?null:new Date(selected.noticeTime).toISOString()},receivedAt:new Date(status.createdAt).toISOString(),checkedAt:new Date(status.checkedAt).toISOString(),asOf:new Date(asOf).toISOString(),stale:asOf-status.checkedAt>STATUS_INTERVAL*2,receipt:status.receipt,provenance:status.provenance,limitations:['Explain only this saved status and synopsis; a newer notice may exist.','Ground alert and aviation code address different hazards and may differ. Neither is earthquake probability.','UNASSIGNED means insufficient information to assess status, not no activity or safety.','The synopsis is attributed source text, not SeismoSphere forecasting or independently verified observation.','The API covers U.S. volcanoes; absent volcanoes are outside this feed, not inactive.','A poll receipt is not the notice publication time. Source alert/color date strings have no supplied time zone.']};}
