import {clickGlobeControl} from './browser-controls.mjs';
import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {hash} from '../server/store.mjs';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),root='http://127.0.0.1:4318',reports=[],data=await(await fetch(root+'/api/cratons')).json();assert.equal(data.features.length,114);assert.equal(hash(data.features),data.featuresSha256);assert.equal(data.features.filter(f=>f.properties.reworked==='yes').length,59);assert.equal(data.features.reduce((n,f)=>n+f.geometry.coordinates.reduce((n,r)=>n+r.length,0),0),12796);
for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height]of (process.argv.includes('--desktop-only')?[[1536,1024]]:[[1536,1024],[390,844],[320,740],[844,390]])){
 const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root);await page.locator('.event-row').first().waitFor({state:'attached'});await page.evaluate(async()=>{const {Cratons}=await import('/cratons.js'),update=Cratons.prototype.update;Cratons.prototype.update=function(...args){window.cratonInspection=this;return update.apply(this,args);};});await clickGlobeControl(page,'cratons-open');await page.locator('#craton-status').filter({hasText:'114 regions'}).waitFor();assert.equal(await page.locator('[data-craton]').count(),114);
 await page.locator('#craton-search').fill('nonexistent xyz');assert.equal(await page.locator('[data-craton]').count(),0);await page.locator('#craton-search').fill('Limpopo Belt');await page.locator('[data-craton="0"]').click();assert.match(await page.locator('#craton-detail').innerText(),/Kalahari Craton/);assert.equal(await page.locator('#craton-explain').isEnabled(),true);await page.locator('#craton-detail').scrollIntoViewIfNeeded();assert.equal(await page.locator('#craton-dialog').evaluate(d=>d.scrollWidth>d.clientWidth+1),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`artifacts/${engine}-craton-${width}.png`});await page.locator('#craton-focus').click();await page.waitForFunction(()=>!window.cratonInspection.earth.targetCamera);assert.equal(await page.evaluate(()=>window.cratonInspection.group.visible),true);
 const evidence=await page.evaluate(()=>window.cratonInspection.evidence());assert.equal(evidence.featuresSha256,data.featuresSha256);assert.equal(evidence.selected.properties.reworked,'yes');assert.equal(await page.evaluate(()=>window.cratonInspection.group.children.length),114);
 if(width===1536){await page.screenshot({path:`artifacts/${engine}-craton-earth.png`});await clickGlobeControl(page,'section-toggle');assert.equal(await page.evaluate(()=>window.cratonInspection.group.children.every(x=>x.material.clippingPlanes.length===2&&x.material.clipIntersection)),true);await clickGlobeControl(page,'section-toggle');assert.equal(await page.evaluate(()=>window.cratonInspection.group.children.every(x=>x.material.clippingPlanes.length===0)),true);
  await clickGlobeControl(page,'cratons-open');await page.locator('#craton-near-camera').click();assert.equal(await page.locator('[data-craton]').count(),6);assert.match(await page.locator('#craton-query').innerText(),/not an inside\/outside test/);await page.getByText('Source and conversion',{exact:true}).click();const downloading=page.waitForEvent('download');await page.locator('a[href="/assets/cratons.json"]').click();await(await downloading).saveAs(`artifacts/${engine}-cratons-export.json`);let release,started;const intercepted=new Promise(r=>started=r),gate=new Promise(r=>release=r);await page.route('**/api/chat',async route=>{started();await gate;await route.fulfill({json:{model:'Controlled test response',grounded:false,answer:'LATER_REFERENCE_SHOULD_NOT_LEAK',actions:[]}});});await page.locator('#craton-explain').click();await intercepted;await page.getByRole('button',{name:'Close craton reference',exact:true}).click();
  await page.getByRole('button',{name:'Research lab',exact:true}).click();await page.locator('#replay-date').fill('2011-03-01T00:00');await page.getByRole('button',{name:'Open historical Earth →'}).click();await page.locator('#timeline-time').filter({hasText:'Mar 01'}).waitFor();await clickGlobeControl(page,'cratons-open');assert.match(await page.locator('#craton-status').innerText(),/Later reference/);assert.equal(await page.locator('#craton-explain').isDisabled(),true);release();await page.waitForFunction(()=>!window.cratonInspection.busy);assert.equal((await page.locator('#craton-explanation').innerText()).includes('LATER_REFERENCE_SHOULD_NOT_LEAK'),false);
 }
 assert.deepEqual(errors,[]);reports.push({engine,width,height,features:evidence.features,hash:evidence.featuresSha256,errors});await page.close();
}}finally{await browser.close();}}
writeFileSync(process.argv.includes('--desktop-only')?'artifacts/craton-cutoff-report.json':'artifacts/craton-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
