import {clickGlobeControl} from './browser-controls.mjs';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),root='http://127.0.0.1:4318',id=JSON.parse(readFileSync('artifacts/gnss-import.json')).id,reports=[];
for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height]of [[1536,1024],[390,844],[320,740],[844,390]]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root);await page.locator('.event-row').first().waitFor({state:'attached'});await page.evaluate(async()=>{const {Geodesy}=await import('/gnss.js'),update=Geodesy.prototype.update;Geodesy.prototype.update=function(...args){window.gnssInspection=this;return update.apply(this,args);};});await clickGlobeControl(page,'gnss-open');await page.locator('#gnss-history').selectOption(id);await page.locator('#gnss-status').filter({hasText:'21,812'}).waitFor();await page.locator('#gnss-visible').check();const initial=await page.evaluate(()=>({stations:window.gnssInspection.filtered.length,points:window.gnssInspection.group.children[0].geometry.attributes.position.count,capped:window.gnssInspection.capped}));assert.equal(initial.points,initial.stations);assert.ok(initial.points>10000);
 await page.locator('#gnss-issues summary').click();await page.locator('[data-gnss-issue="0KAR"]').click();await page.locator('#gnss-detail .error-text').waitFor();assert.equal(await page.evaluate(()=>window.gnssInspection.filtered.some(s=>s.id==='0KAR')),false);await page.locator('#gnss-search').fill('P090');await page.locator('[data-gnss="P090"]').click();await page.locator('#gnss-detail').filter({hasText:'-20.291'}).waitFor();assert.match(await page.locator('#gnss-detail').innerText(),/-5\.902/);assert.match(await page.locator('#gnss-detail').innerText(),/-0\.824/);assert.match(await page.locator('#gnss-detail').innerText(),/0\.593/);await page.locator('#gnss-detail').scrollIntoViewIfNeeded();assert.equal(await page.locator('#gnss-dialog').evaluate(d=>d.scrollWidth>d.clientWidth+1),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`artifacts/${engine}-gnss-${width}.png`});await page.locator('#gnss-focus').click();await page.waitForFunction(()=>!window.gnssInspection.earth.targetCamera);assert.equal(await page.evaluate(()=>window.gnssInspection.group.visible),true);assert.equal(await page.locator('.gnss-selection').isVisible(),true);assert.equal(await page.locator('.gnss-selection').evaluate(d=>d.scrollWidth>d.clientWidth+1),false);await page.screenshot({path:`artifacts/${engine}-gnss-selected-${width}.png`});
 if(width===1536){await page.screenshot({path:`artifacts/${engine}-gnss-focused.png`});await clickGlobeControl(page,'section-toggle');assert.equal(await page.evaluate(()=>window.gnssInspection.group.children.every(c=>c.material.clippingPlanes.length===2)),true);await clickGlobeControl(page,'section-toggle');await clickGlobeControl(page,'gnss-open');await page.locator('#gnss-search').fill('');await page.locator('#gnss-near-camera').click();const regional=await page.evaluate(()=>window.gnssInspection.filtered.length);assert.ok(regional>1&&regional<initial.stations);await page.locator('#gnss-global').click();assert.equal(await page.evaluate(()=>window.gnssInspection.filtered.length),initial.stations);await page.getByText('Saved source and limits',{exact:true}).click();const pending=page.waitForEvent('download');await page.locator('#gnss-raw').click();await(await pending).saveAs(`artifacts/${engine}-gnss-source.txt`);await page.getByRole('button',{name:'Close GNSS velocities',exact:true}).click();await page.getByRole('button',{name:'Research lab',exact:true}).click();await page.locator('#replay-date').fill('2011-03-01T00:00');await page.getByRole('button',{name:'Open historical Earth →'}).click();await page.locator('#timeline-time').filter({hasText:'Mar 01'}).waitFor();assert.equal(await page.evaluate(()=>window.gnssInspection.group.visible),false);await clickGlobeControl(page,'gnss-open');assert.match(await page.locator('#gnss-status').innerText(),/Later solution/);assert.equal(await page.locator('#gnss-explain').isDisabled(),true);}
 assert.deepEqual(errors,[]);reports.push({engine,width,height,...initial,errors});await page.close();
}}finally{await browser.close();}}
writeFileSync('artifacts/gnss-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
