import {clickGlobeControl} from './browser-controls.mjs';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {hash} from '../server/store.mjs';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),reports=[];
for(const engine of ['chromium','webkit']){
  const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})}),page=await browser.newPage({viewport:{width:1536,height:1024},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  try{
    await page.goto('http://127.0.0.1:4318');await page.locator('.event-row').first().waitFor();await clickGlobeControl(page,'instruments-open');await page.locator('#stations-form [name="at"]').fill('2010-02-27T07:02');await page.locator('#stations-form button').click();await page.locator('.station-row').first().waitFor();
    assert.match(await page.locator('#instrument-status').innerText(),/206 channel epochs/);await page.locator('#station-search').fill('not-a-station');assert.match(await page.locator('#station-list').innerText(),/No channel/);await page.locator('#station-search').fill('IU.ANMO.00');await page.locator('.station-row').click();const liveRequest=page.waitForResponse(r=>r.url().endsWith('/api/waveform-query'));await page.locator('#waveform-form button').click();assert.equal((await liveRequest).request().postDataJSON().mode,'catalog-replay');await page.locator('#waveform-result svg').waitFor();
    await page.locator('#station-focus').click();await page.locator('#instruments-dialog').waitFor({state:'hidden'});await page.locator('#timeline-time').filter({hasText:'Feb 27'}).waitFor();assert.match(await page.locator('.station-caption').innerText(),/206 STATION CHANNEL/);await page.screenshot({path:`artifacts/${engine}-stations-earth.png`});const canvas=await page.locator('#globe canvas').boundingBox();await page.locator('#globe canvas').click({position:{x:canvas.width/2,y:canvas.height*.445}});await page.locator('#instruments-dialog').waitFor({state:'visible'});assert.match(await page.locator('#station-detail h3').innerText(),/ANMO/);await page.getByRole('button',{name:'Close stations and waveforms'}).click();
    for(const [width,height] of [[1366,768],[1536,1024]]){await page.setViewportSize({width,height});await page.locator('#layers-open').click();await page.locator('.station-caption').scrollIntoViewIfNeeded();const caption=await page.locator('.station-caption').boundingBox(),panel=await page.locator('#layers-panel').boundingBox();assert.ok(caption.y>=panel.y&&caption.y+caption.height<=panel.y+panel.height,JSON.stringify({width,caption,panel}));assert.match(await page.locator('.station-caption').innerText(),/206 STATION CHANNEL/);await page.keyboard.press('Escape');}
    await clickGlobeControl(page,'figure-open');await page.locator('#figure-form button').click();await page.locator('#figure-preview').waitFor({timeout:30000});let downloading=page.waitForEvent('download');await page.locator('#figure-json').click();await(await downloading).saveAs(`artifacts/${engine}-stations-figure.json`);const figure=JSON.parse(readFileSync(`artifacts/${engine}-stations-figure.json`,'utf8'));assert.equal(figure.evidence.seismicStations.visibleChannels.length,206);assert.equal(figure.evidence.seismicStations.selectedChannel.station,'ANMO');await page.locator('#figure-close').click();
    await clickGlobeControl(page,'instruments-open');await page.locator('#waveform-form button').click();await page.locator('#waveform-result svg').waitFor();
    downloading=page.waitForEvent('download');await page.getByRole('link',{name:'Samples + metadata JSON ↓'}).click();await(await downloading).saveAs(`artifacts/${engine}-waveform.json`);const exported=JSON.parse(readFileSync(`artifacts/${engine}-waveform.json`,'utf8')),{id,...body}=exported.record;assert.deepEqual(exported.integrity,{recordValid:true,sourceValid:true});assert.equal(hash(body),id);assert.equal(body.summary.samples,2400);assert.equal(body.segments.length,2);assert.equal(body.segments[0].samples[0][0]%1000000,19538);
    downloading=page.waitForEvent('download');await page.getByRole('link',{name:'Original GeoCSV ↓'}).click();await(await downloading).saveAs(`artifacts/${engine}-waveform-geocsv.txt`);assert.equal(hash(readFileSync(`artifacts/${engine}-waveform-geocsv.txt`,'utf8')),body.receipt.sha256);
    downloading=page.waitForEvent('download');await page.locator('#waveform-svg').click();await(await downloading).saveAs(`artifacts/${engine}-waveform.svg`);const svg=readFileSync(`artifacts/${engine}-waveform.svg`,'utf8'),metadata=await page.evaluate(s=>JSON.parse(new DOMParser().parseFromString(s,'image/svg+xml').querySelector('metadata').textContent),svg);assert.equal(metadata.recordId,id);assert.equal(metadata.summary.samples,2400);
    await page.locator('#waveform-result').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/${engine}-waveform-desktop.png`});
    const layouts=[];for(const [width,height]of [[320,844],[390,844],[768,1024],[844,390]]){await page.setViewportSize({width,height});await page.locator('#waveform-svg').scrollIntoViewIfNeeded();const layout=await page.locator('#instruments-dialog').evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth}));assert.ok(layout.scroll<=layout.client+1,JSON.stringify({width,...layout}));const close=await page.getByRole('button',{name:'Close stations and waveforms'}).boundingBox();assert.ok(close.y>=0&&close.y+close.height<=height);layouts.push({width,height,...layout});}
    await page.setViewportSize({width:390,height:844});await page.locator('#waveform-result svg').evaluate(e=>e.scrollIntoView({block:'center'}));await page.screenshot({path:`artifacts/${engine}-waveform-mobile.png`});
    await page.getByRole('button',{name:'Close stations and waveforms'}).click();await page.locator('[data-mobile="research"]').click();await page.locator('#replay-date').fill('2010-02-27T07:02');await page.locator('#strict-replay').check();await page.locator('#load-replay').click();await page.locator('#timeline-mode').filter({hasText:'STRICT OBSERVATION REPLAY'}).waitFor();assert.equal(await page.locator('.station-caption').isVisible(),false);await clickGlobeControl(page,'instruments-open');assert.equal(await page.locator('#waveform-result svg').count(),0);assert.match(await page.locator('#waveform-result').innerText(),/unavailable at the current observation cutoff/);
    const strict=await page.request.post('http://127.0.0.1:4318/api/waveform-query',{data:{...body.query,asOf:body.query.end,mode:'strict'}});assert.equal(strict.status(),400);assert.deepEqual(errors,[]);reports.push({engine,stationRecordId:body.query.stationRecordId,waveformId:id,samples:2400,layouts,errors,strictRejected:true});
  }finally{await browser.close();}
}
writeFileSync('artifacts/instruments-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
