import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {Store,hash} from '../server/store.mjs';
import {Instruments} from '../server/instruments.mjs';
import {clickGlobeControl} from './browser-controls.mjs';
const directory=mkdtempSync(path.resolve('artifacts/phase-browser-')),file=path.join(directory,'test.sqlite'),real=JSON.parse(readFileSync('artifacts/phase-real-arrivals.json')),physical=JSON.parse(readFileSync('artifacts/chromium-physical-ACC.json')),db=new DatabaseSync('data/seismosphere.sqlite',{readOnly:true}),store=new Store(file);new Instruments(store);const station=JSON.parse(db.prepare('SELECT body FROM instrument_records WHERE id=?').get(real.source.query.stationRecordId).body);db.close();
for(const record of [real.source,real.record,station,physical.source,physical.response])store.db.prepare('INSERT INTO instrument_records VALUES(?,?,?,?,?)').run(record.id,record.kind,record.createdAt,hash(record.query),JSON.stringify(record));const {observedAt,...event}=real.record.event;store.ingest([event],observedAt);store.db.close();
const listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));const root=`http://127.0.0.1:${port}`,child=spawn(process.execPath,['server/index.mjs'],{windowsHide:true,env:{...process.env,PORT:String(port),SEISMO_DB:file,SEISMO_TEST_MODE:'1'},stdio:['ignore','pipe','pipe']}),engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),reports=[];
try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Fixture server startup timeout')),10000);child.stdout.on('data',b=>{if(String(b).includes('SeismoSphere running')){clearTimeout(timer);resolve();}});child.on('error',reject);});for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height,corrected]of [[1366,900,false],[320,740,false],[390,844,true],[844,390,true]]){const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root);await page.locator('#instruments-open').waitFor({state:'attached'});await clickGlobeControl(page,'instruments-open');await page.locator(`#waveform-history option[value="${real.source.id}"]`).waitFor({state:'attached'});await page.locator('#waveform-history').selectOption(real.source.id);if(corrected){await page.locator(`#correction-history option[value="${physical.source.id}"]`).waitFor({state:'attached'});await page.locator('#correction-history').selectOption(physical.source.id);await page.locator('#correction-phases').click();}
const form=page.locator('#phase-form');await form.locator(`[name="eventId"] option[value="${event.id}"]`).waitFor({state:'attached'});await form.locator('[name="eventId"]').selectOption(event.id);const pending=page.waitForResponse(r=>r.url().endsWith('/api/waveform-phases'));await form.locator('button').click();const reply=await pending,record=await reply.json();assert.equal(reply.status(),200,JSON.stringify(record));assert.equal(record.arrivals.length,6);assert.equal(record.summary.arrivalsInInterval,1);assert.equal(record.query.waveformId,corrected?physical.source.id:real.source.id);await page.locator('#phase-result svg').waitFor();
const picker=page.locator('#phase-pick-form');await picker.locator('[name="sampleIndex"]').fill('1140');await picker.locator('[name="arrivalIndex"]').selectOption('5');await picker.locator('[name="uncertaintySeconds"]').fill('0.5');await picker.locator('button').click();const saving=page.waitForResponse(r=>r.url().endsWith('/api/waveform-picks'));await page.locator('#phase-save').click();const savedReply=await saving,saved=await savedReply.json();delete saved.reused;assert.equal(savedReply.status(),200,JSON.stringify(saved));assert.equal(saved.picks.length,1);assert.equal(saved.picks[0].phase,'SS');assert.equal(saved.parentId,record.id);await page.locator('#phase-history').filter({has:page.locator(`option[value="${saved.id}"]`)}).waitFor();assert.equal((await(await fetch(root+'/api/instrument-export?id='+record.id)).json()).record.picks.length,0);
const save=async(selector,ext)=>{const pending=page.waitForEvent('download');await page.locator(selector).click();const file=`artifacts/${engine}-phase-${corrected?'corrected':'raw'}-${width}.${ext}`;await(await pending).saveAs(file);return file;};const exported=JSON.parse(readFileSync(await save('#phase-result a','json'),'utf8'));assert.ok(Object.values(exported.integrity).every(Boolean));const svg=readFileSync(await save('#phase-svg','svg'),'utf8'),metadata=svg.match(/<metadata>([\s\S]*?)<\/metadata>/)[1].replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>');assert.deepEqual(JSON.parse(metadata),saved);await page.locator('#phase-result').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/${engine}-phase-${width}.png`});const layout=await page.locator('#instruments-dialog').evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth,overflow:[...el.querySelectorAll('*')].filter(e=>e.clientWidth&&e.scrollWidth>e.clientWidth+1).slice(0,8).map(e=>({tag:e.tagName,id:e.id,name:e.name,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})),targets:[...el.querySelectorAll('#phase-panel button,#phase-panel input,#phase-panel select')].map(e=>e.getBoundingClientRect().height)}));assert.ok(layout.scroll<=layout.width+1,JSON.stringify({engine,width,height,layout}));assert.ok(layout.targets.every(h=>h>=44));assert.deepEqual(errors,[]);reports.push({engine,width,height,corrected,recordId:saved.id,isolatedManualPick:true,layout,integrity:exported.integrity});await page.close();}}finally{await browser.close();}}writeFileSync('artifacts/phase-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));}finally{child.kill();await new Promise(r=>child.exitCode!==null?r():child.once('exit',r));}
