import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import assert from 'node:assert/strict';
import {prospectiveFixture} from './prospective-fixture.mjs';
const directory=mkdtempSync(path.resolve('artifacts/prospective-browser-')),file=path.join(directory,'test.sqlite'),fixture=prospectiveFixture(file,'artifacts/prospective-scored-fixture.json'),listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));const root=`http://127.0.0.1:${port}`,child=spawn(process.execPath,['server/index.mjs'],{windowsHide:true,env:{...process.env,PORT:String(port),SEISMO_DB:file,SEISMO_TEST_MODE:'1'},stdio:['ignore','pipe','pipe']}),engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),reports=[];
try{await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Protocol fixture server startup timed out')),10000);child.stdout.on('data',data=>{if(String(data).includes('SeismoSphere running')){clearTimeout(timeout);resolve();}});child.on('error',reject);});for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height]of [[1366,900],[320,740],[390,844],[844,390]]){
 const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root);await page.locator('.event-row').first().waitFor({state:'attached'});const desktop=page.locator('[data-view="research"]');await(await desktop.isVisible()?desktop:page.locator('[data-mobile="research"]')).click();await page.locator('#protocol-open').click();await page.locator(`#protocol-history option[value="${fixture.id}"]`).waitFor({state:'attached'});await page.locator('#protocol-history').selectOption(fixture.id);await page.locator('#protocol-detail').filter({hasText:'100.00 percentage points'}).waitFor();const waiting=page.waitForEvent('download');await page.locator('#protocol-detail a').click();const exportPath=`artifacts/${engine}-prospective-scored.json`;await(await waiting).saveAs(exportPath);const exported=JSON.parse(readFileSync(exportPath,'utf8'));assert.equal(exported.integrity.valid,true);assert.equal(exported.forecastProofs.length,3);assert.equal(exported.summary.completeGroups,1);
 const name=`UI acceptance ${engine} ${width}`,form=page.locator('#protocol-form');await form.locator('[name="name"]').fill(name);await form.locator('[name="issuances"]').fill('2');await form.locator('button').click();await page.locator('#protocol-register').waitFor();await form.locator('[name="hypothesis"]').fill('Controlled interface acceptance only; no claim of scientific predictive skill.');assert.equal(await page.locator('#protocol-register').count(),0);await form.locator('button').click();await page.locator('#protocol-register').waitFor();const registering=page.waitForResponse(r=>r.url().endsWith('/api/protocol-register'));await page.locator('#protocol-register').click();const reply=await registering,p=await reply.json();assert.equal(reply.status(),200,JSON.stringify(p));await page.locator('#protocol-detail h3').filter({hasText:name}).waitFor();assert.match(await page.locator('#protocol-detail').innerText(),/Not available/);const layout=await page.locator('#research-dialog').evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth,targets:[...el.querySelectorAll('#prospective-lab button,#prospective-lab input,#prospective-lab select')].filter(e=>e.getBoundingClientRect().height).map(e=>e.getBoundingClientRect().height)}));assert.ok(layout.scroll<=layout.width+1);assert.ok(layout.targets.every(h=>h>=44));await page.locator('#protocol-detail').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/${engine}-prospective-${width}.png`});await page.locator('#protocol-stop').click();await page.locator('#protocol-stop').waitFor({state:'detached'});assert.equal(await page.locator('#protocol-stop').count(),0);assert.equal((await(await fetch(root+'/api/ledger')).json()).integrity.count,3);
 if(width===1366){await page.locator('#protocol-history').selectOption(fixture.id);await page.locator('#protocol-detail h3').filter({hasText:'Controlled scheduler acceptance fixture'}).waitFor();let release;const gate=new Promise(r=>release=r);await page.route('**/api/chat',async route=>{await gate;await route.fulfill({json:{model:'Controlled timing',answer:'LATE_PROTOCOL_ANSWER',actions:[]}});});const thinking=page.waitForRequest(r=>r.url().endsWith('/api/chat'));await page.locator('#protocol-explain').click();await thinking;await page.locator('#protocol-history').selectOption(p.id);await page.locator('#protocol-detail h3').filter({hasText:name}).waitFor();const returned=page.waitForResponse(r=>r.url().endsWith('/api/chat'));release();await returned;await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.getByText('LATE_PROTOCOL_ANSWER',{exact:false}).count(),0);await page.unroute('**/api/chat');}
 assert.deepEqual(errors,[]);reports.push({engine,width,height,registeredId:p.id,stopped:true,isolatedFixture:true,fixtureLedgerCount:3,layout,errors});await page.close();
}}finally{await browser.close();}}writeFileSync('artifacts/prospective-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
}finally{child.kill();await new Promise(r=>child.exitCode!==null?r():child.once('exit',r));}
