import {readFileSync,writeFileSync} from 'node:fs';
import {Store} from '../server/store.mjs';
import {ProspectiveExperiments} from '../server/prospective.mjs';
import {DAY} from '../server/geo.mjs';
export function prospectiveFixture(file,exportPath){
 const originalNow=Date.now,actual=originalNow(),store=new Store(file),config={...JSON.parse(readFileSync('config/default.json','utf8')),aiProvider:'deterministic'},service=new ProspectiveExperiments(store),routes={version:'controlled-fixture',status:'Synthetic software acceptance only',routes:[]};let clock=actual-30*DAY;Date.now=()=>clock;
 try{store.set('config',config);const events=[{id:'USGS:fixture-a',provider:'USGS',time:clock-1000,lat:0,lon:-10,mag:5,depth:10,type:'earthquake',magType:'mw',place:'CONTROLLED FIXTURE A'},{id:'USGS:fixture-b',provider:'USGS',time:clock-1000,lat:0,lon:10,mag:5,depth:10,type:'earthquake',magType:'mw',place:'CONTROLLED FIXTURE B'}];store.ingest(events,clock-1);const input={name:'Controlled scheduler acceptance fixture',hypothesis:'Synthetic software test only; these constructed events cannot establish scientific forecasting skill.',start:clock+180000,issuances:2,stepDays:1,settleDays:1},preview=service.preview(input,config,routes,[]),protocol=service.register({...input,previewHash:preview.previewHash},config,routes,[]);clock=protocol.spec.start+1000;service.tick({status:'live',fetchedAt:clock,generated:clock,url:'fixture://synthetic-month-feed'});service.stop(protocol.id);const slot=service.view(protocol.id).slots[0],ds=store.ledger().find(f=>f.engine==='DS');clock=slot.assessmentDueAt+1000;store.ingest([{id:'USGS:fixture-outcome',provider:'USGS',time:ds.validFrom+DAY,lat:ds.center.lat,lon:ds.center.lon,mag:ds.magnitude.central,depth:12,type:'earthquake',place:'CONTROLLED MATCHING OUTCOME',magType:'mw'}],clock-1);store.set('coverage',[{provider:'USGS',start:0,end:clock,minMagnitude:-3,source:'fixture://synthetic-complete-coverage'}]);service.tick({status:'live',fetchedAt:clock,generated:clock,url:'fixture://synthetic-month-feed'});const payload=service.export(protocol.id);if(exportPath)writeFileSync(exportPath,JSON.stringify(payload,null,2));Date.now=originalNow;store.ingest(events.map((e,i)=>({...e,id:e.id+'-current',time:actual-10000+i})),actual-1000);store.set('feed',{status:'live',fetchedAt:actual,generated:actual,url:'fixture://synthetic-current-feed'});return {id:protocol.id,config};
 }finally{Date.now=originalNow;store.close();}
}
