import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {clickGlobeControl} from './browser-controls.mjs';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),reports=[];
for(const engine of ['chromium','webkit']){
 const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});
 try{for(const [width,height]of [[1366,900],[320,740],[390,844],[844,390]]){
  const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4318');await page.locator('.event-row').first().waitFor({state:'attached'});await clickGlobeControl(page,'recording-open');assert.equal(await page.locator('#recording-dialog').evaluate(d=>d.scrollWidth>d.clientWidth+1),false);
  const supported=await page.evaluate(()=>!!window.MediaRecorder&&!!HTMLCanvasElement.prototype.captureStream);
  if(!supported){assert.match(await page.locator('#recording-status').innerText(),/unavailable/);assert.equal(await page.locator('#recording-form .primary').isDisabled(),true);await page.screenshot({path:`artifacts/${engine}-recording-unavailable-${width}.png`});reports.push({engine,width,height,supported,errors});await page.close();continue;}
  await page.getByRole('button',{name:'Close Earth recording',exact:true}).click();await clickGlobeControl(page,'orbit-toggle');await clickGlobeControl(page,'recording-open');if(width===1366)await page.locator('#recording-form [name=audio]').check();await page.locator('#recording-form .primary').click();await page.locator('#recording-progress').filter({hasText:'2 /'}).waitFor();
  if(width===1366){await page.locator('#recording-pause').click();const paused=await page.locator('#recording-progress').innerText();await page.waitForTimeout(1100);assert.equal(await page.locator('#recording-progress').innerText(),paused);await page.locator('#recording-pause').click();await page.getByRole('button',{name:'Earth tools',exact:true}).click();await page.locator('#sound-settings').click();await page.locator('#sound-sequence').click();await page.locator('#recording-progress').filter({hasText:'4 /'}).waitFor();}
  if(width===320){await clickGlobeControl(page,'plates-toggle');}
  else if(width===844){await page.setViewportSize({width:845,height});}
  else await page.locator('#recording-stop').click();
  await page.locator('#recording-downloads').waitFor({timeout:45000});await page.locator('#recording-preview').evaluate(v=>new Promise((resolve,reject)=>{if(v.readyState>=2)return resolve();v.addEventListener('loadeddata',resolve,{once:true});v.addEventListener('error',()=>reject(new Error(v.error?.message)),{once:true});v.load();}));
  const decoded=await page.locator('#recording-preview').evaluate(async v=>{v.muted=true;await v.play();await new Promise(r=>setTimeout(r,250));v.pause();const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;const ctx=c.getContext('2d');ctx.drawImage(v,0,0);const data=ctx.getImageData(0,80,c.width,c.height-160).data;let lit=0;for(let i=0;i<data.length;i+=4)if(Math.max(data[i],data[i+1],data[i+2])>60)lit++;return {width:v.videoWidth,height:v.videoHeight,duration:v.duration,time:v.currentTime,litPixels:lit,error:v.error?.message??null};});assert.ok(decoded.litPixels>5000);assert.ok(decoded.time>0);assert.equal(decoded.error,null);
  const paths={};for(const kind of ['video','evidence']){const pending=page.waitForEvent('download');await page.locator('#recording-'+kind).click();const download=await pending;paths[kind]=`artifacts/${engine}-recording-${width}`+(kind==='evidence'?'.json':download.suggestedFilename().endsWith('.mp4')?'.mp4':'.webm');await download.saveAs(paths[kind]);}
  if(width===1366){const audio=await page.evaluate(async encoded=>{const context=new AudioContext();try{const data=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),buffer=await context.decodeAudioData(data.buffer);let energy=0,peak=0;for(let c=0;c<buffer.numberOfChannels;c++)for(const x of buffer.getChannelData(c)){energy+=x*x;peak=Math.max(peak,Math.abs(x));}return {energy,peak,channels:buffer.numberOfChannels,sampleRate:buffer.sampleRate,duration:buffer.duration};}finally{await context.close();}},readFileSync(paths.video).toString('base64'));assert.ok(audio.peak>0.00001);assert.ok(audio.energy>0);writeFileSync('artifacts/recording-decoded-audio.json',JSON.stringify(audio,null,2));}
  const payload=JSON.parse(readFileSync(paths.evidence)),e=payload.evidence;assert.equal(createHash('sha256').update(JSON.stringify(e)).digest('hex'),payload.sha256);assert.equal(createHash('sha256').update(readFileSync(paths.video)).digest('hex'),e.video.sha256);assert.equal(decoded.width,e.video.width);assert.equal(decoded.height,e.video.height);assert.ok(e.frames.length>20);assert.notDeepEqual(e.frames[0].camera.position,e.frames.at(-1).camera.position);assert.equal(e.scene.observationCutoff,e.scene.analysisCutoff);if(width===320)assert.equal(e.stopReason,'View data or layers changed');if(width===844)assert.equal(e.stopReason,'Viewport resized');if(width===1366)assert.equal(e.video.audio,true);await page.screenshot({path:`artifacts/${engine}-recording-${width}.png`});assert.deepEqual(errors,[]);reports.push({engine,width,height,supported,decoded,frames:e.frames.length,stopReason:e.stopReason,audio:e.video.audio,errors});await page.close();
 }}finally{await browser.close();}
}
writeFileSync('artifacts/recording-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
