import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {clickGlobeControl} from './browser-controls.mjs';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),pin=JSON.parse(readFileSync('config/relief-source.json')),reports=[];
for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height]of [[1366,900],[320,740],[390,844],[844,390]]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:4318');await page.locator('.event-row').first().waitFor({state:'attached'});await page.evaluate(async()=>{const {Relief}=await import('/relief.js'),sync=Relief.prototype.sync;Relief.prototype.sync=function(){window.reliefInspection=this;return sync.call(this);};});await page.waitForFunction(()=>window.reliefInspection?.earth.plates.children.length>0);await page.evaluate(()=>{const e=window.reliefInspection.earth;window.originalDepths=Array.from(e.points.geometry.attributes.position.array);window.originalPlates=e.plates.children.map(c=>Array.from(c.geometry.attributes.position.array));});
 for(const id of ['paths-toggle','field-toggle','watches-toggle'])await clickGlobeControl(page,id);await clickGlobeControl(page,'relief-open');await page.waitForFunction(()=>!document.querySelector('#relief-enabled').disabled);await page.locator('#relief-enabled').check();await page.locator('#relief-seafloor').check();await page.locator('#relief-colors').check();await page.locator('#relief-scale').selectOption('20');await page.waitForFunction(()=>window.reliefInspection.effectiveScale===20&&window.reliefInspection.geometry);
 const geometry=await page.evaluate(async()=>{const {reliefRadius}=await import('/relief-grid.js'),r=window.reliefInspection,p=r.geometry.attributes.position;let min=Infinity,max=0,error=0;for(let i=0;i<p.count;i+=Math.max(1,Math.floor(p.count/3000))){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),radius=Math.hypot(x,y,z),lat=Math.asin(y/radius)*180/Math.PI,lon=Math.atan2(-z,x)*180/Math.PI;min=Math.min(min,radius);max=Math.max(max,radius);error=Math.max(error,Math.abs(radius-reliefRadius(r.grid.heightAt(lat,lon),20,true)));}return {vertices:p.count,min,max,error,depthsUnchanged:JSON.stringify(window.originalDepths)===JSON.stringify(Array.from(r.earth.points.geometry.attributes.position.array)),platesChanged:window.originalPlates.some((a,i)=>JSON.stringify(a)!==JSON.stringify(Array.from(r.earth.plates.children[i].geometry.attributes.position.array)))};});assert.ok(geometry.min<.98&&geometry.max>1.01);assert.ok(geometry.error<3e-7);assert.equal(geometry.depthsUnchanged,true);assert.equal(geometry.platesChanged,true);assert.equal(geometry.vertices,width===1366?525825:131841);assert.equal(await page.locator('#relief-dialog').evaluate(d=>d.scrollWidth>d.clientWidth+1),false);await page.screenshot({path:`artifacts/${engine}-relief-dialog-${width}.png`});
 await page.locator('[data-relief-place="-22,-174"]').click();await page.waitForFunction(()=>!window.reliefInspection.earth.targetCamera);const gpu=await page.evaluate(()=>{const e=window.reliefInspection.earth,r=e.renderer,gl=r.getContext(),w=r.domElement.width,h=r.domElement.height,a=new Uint8Array(w*h*4),b=new Uint8Array(w*h*4);try{r.render(e.scene,e.camera);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,a);e.surface.visible=false;r.render(e.scene,e.camera);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,b);}finally{e.surface.visible=true;r.render(e.scene,e.camera);}let changed=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>20)changed++;return {surfacePixels:changed};});assert.ok(gpu.surfacePixels>5000);await page.screenshot({path:`artifacts/${engine}-relief-earth-${width}.png`});const timing=await page.evaluate(()=>new Promise(resolve=>{const times=[];let last=performance.now();function tick(now){times.push(now-last);last=now;if(times.length===60){const samples=times.slice(5).sort((a,b)=>a-b);resolve({medianMs:samples[Math.floor(samples.length/2)],p95Ms:samples[Math.floor(samples.length*.95)]});}else requestAnimationFrame(tick);}requestAnimationFrame(tick);}));
 if(width===1366){await clickGlobeControl(page,'section-toggle');await page.waitForFunction(()=>window.reliefInspection.effectiveScale===1);const section=await page.evaluate(()=>({scale:window.reliefInspection.effectiveScale,requested:window.reliefInspection.scale,caps:window.reliefInspection.earth.geology.cap.children.length,clipping:window.reliefInspection.earth.surface.material.clippingPlanes.length}));assert.deepEqual(section,{scale:1,requested:20,caps:2,clipping:2});await page.screenshot({path:`artifacts/${engine}-relief-section.png`});await clickGlobeControl(page,'section-toggle');await page.waitForFunction(()=>window.reliefInspection.effectiveScale===20);await clickGlobeControl(page,'scientific-toggle');assert.equal(await page.evaluate(()=>window.reliefInspection.earth.surface.material.type),'MeshBasicMaterial');await clickGlobeControl(page,'figure-open');await page.getByRole('button',{name:'Capture current Earth',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#figure-status').textContent.includes('Capturing'),{},{timeout:45000});assert.equal(await page.locator('.figure-downloads').isVisible(),true,await page.locator('#figure-status').innerText());const pending=page.waitForEvent('download');await page.locator('#figure-json').click();await(await pending).saveAs(`artifacts/${engine}-relief-figure.json`);const figure=JSON.parse(readFileSync(`artifacts/${engine}-relief-figure.json`));assert.equal(figure.evidence.reliefSurface.provenance.sha256,pin.sha256);assert.equal(figure.evidence.reliefSurface.display.scale,20);assert.equal(createHash('sha256').update(JSON.stringify(figure.evidence)).digest('hex'),figure.sha256);await page.getByRole('button',{name:'Close figure export',exact:true}).click();await clickGlobeControl(page,'relief-open');await page.locator('#relief-dialog details summary').click();const raw=page.waitForEvent('download');await page.locator('[href="/api/relief-export"]').click();await(await raw).saveAs(`artifacts/${engine}-relief-source.dods`);assert.equal(createHash('sha256').update(readFileSync(`artifacts/${engine}-relief-source.dods`)).digest('hex'),pin.sourceSha256);
 }else await clickGlobeControl(page,'relief-open');
 await page.locator('#relief-enabled').uncheck();const restored=await page.evaluate(()=>{const r=window.reliefInspection;return {geometry:r.earth.surface.geometry===r.originalGeometry,plates:window.originalPlates.every((a,i)=>JSON.stringify(a)===JSON.stringify(Array.from(r.earth.plates.children[i].geometry.attributes.position.array)))};});assert.deepEqual(restored,{geometry:true,plates:true});assert.deepEqual(errors,[]);reports.push({engine,width,height,geometry,gpu,timing,restored,errors});await page.close();
}}finally{await browser.close();}}
writeFileSync('artifacts/relief-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
