import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {clickGlobeControl} from './browser-controls.mjs';
import {hash} from '../server/store.mjs';
const root='http://127.0.0.1:4318',engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{source}=JSON.parse(readFileSync('artifacts/chromium-spectrum.json','utf8')),reports=[];
for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height]of [[1366,900],[320,740],[390,844],[844,390]]){
 const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root);await page.locator('.event-row').first().waitFor({state:'attached'});await clickGlobeControl(page,'instruments-open');await page.locator(`#waveform-history option[value="${source.id}"]`).waitFor({state:'attached'});await page.locator('#waveform-history').selectOption(source.id);await page.locator('#correction-form').waitFor();await page.locator('#waveform-join').uncheck();
 const loading=page.waitForResponse(r=>r.url().endsWith('/api/waveform-response'),{timeout:60000});await page.locator('#response-load').click();const loaded=await loading,response=await loaded.json();assert.equal(loaded.status(),200,JSON.stringify(response));assert.equal(response.response.stages.length,3);assert.equal(response.response.sampleRateHz,20);
 const calculating=page.waitForResponse(r=>r.url().endsWith('/api/waveform-correct'),{timeout:45000});await page.locator('#correction-form button').click();const reply=await calculating,result=await reply.json();assert.equal(reply.status(),200,JSON.stringify(result));await page.locator('#correction-result svg').waitFor();assert.equal(result.summary.units,'m/s');assert.equal(result.summary.samples,2020);assert.equal(result.query.responseId,response.id);assert.equal(result.segments[0].samples[0][0],source.segments[0].samples[0][0]);
 await page.locator(`#correction-history option[value="${result.id}"]`).waitFor({state:'attached'});await page.locator('#correction-history').selectOption(result.id);await page.locator('#correction-status').filter({hasText:'Loaded immutable'}).waitFor();
 const layout=await page.locator('#instruments-dialog').evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth,controls:[...el.querySelectorAll('#correction-panel input,#correction-panel select,#correction-panel button')].filter(e=>e.getBoundingClientRect().width).map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}))}));assert.ok(layout.scroll<=layout.client+1,JSON.stringify(layout));assert.ok(layout.controls.every(c=>c.width>=44&&c.height>=44));await page.locator('#correction-result').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/${engine}-response-${width}.png`});
 if(width===1366){const download=async(selector,suffix)=>{const pending=page.waitForEvent('download');await page.locator(selector).click();const file=`artifacts/${engine}-response.${suffix}`;await(await pending).saveAs(file);return readFileSync(file);};
  const payload=JSON.parse((await download('#correction-result a','json')).toString('utf8')),{id,...body}=payload.record;assert.equal(hash(body),id);assert.ok(Object.values(payload.integrity).every(Boolean));assert.equal(payload.source.id,source.id);assert.equal(payload.response.id,response.id);
  const xml=await download('#response-metadata a','xml');assert.equal(createHash('sha256').update(xml).digest('hex'),response.receipt.sha256);assert.deepEqual(xml,Buffer.from(response.raw,'base64'));
  const rows=(await download('#correction-csv','csv')).toString('utf8').trim().split(/\r?\n/).slice(1).map(r=>r.split(','));assert.equal(rows.length,result.summary.samples);assert.deepEqual(rows.map(r=>[Number(r[1]),Number(r[2])]),result.segments[0].samples);
  const svg=(await download('#correction-svg','svg')).toString('utf8'),meta=await page.evaluate(svg=>JSON.parse(new DOMParser().parseFromString(svg,'image/svg+xml').querySelector('metadata').textContent),svg),{id:metaId,...metaBody}=meta;assert.equal(metaId,id);assert.equal(hash(metaBody),id);
 }
 assert.deepEqual(errors,[]);reports.push({engine,width,height,id:result.id,responseId:response.id,summary:result.summary,layout,errors});await page.close();
 }}finally{await browser.close();}}
writeFileSync('artifacts/response-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
