import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import {once} from 'node:events';
import assert from 'node:assert/strict';
import {Store} from '../server/store.mjs';
import {clickGlobeControl} from './browser-controls.mjs';
const {chromium}=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=mkdtempSync('artifacts/routes-acceptance-'),db=dir+'/test.sqlite',store=new Store(db),now=Date.now(),config=JSON.parse(readFileSync('config/default.json'));store.set('config',{...config,aiProvider:'deterministic'});store.set('feed',{status:'live',fetchedAt:now,generated:now,url:'fixture://route-editor'});store.ingest([-10,10].map((lon,i)=>({id:'USGS:route-fixture-'+i,sourceId:'route-fixture-'+i,provider:'USGS',time:now-10000,updated:now-10000,lat:0,lon,depth:500,mag:5.5,magType:'mw',type:'earthquake',status:'reviewed',place:'Software acceptance fixture'})),now-1000);store.close();
const port=46318,base='http://127.0.0.1:'+port,child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:String(port),SEISMO_TEST_MODE:'1',SEISMO_DB:db,SEISMO_TLS_DIR:dir+'/tls'},windowsHide:true,stdio:['ignore','pipe','pipe']});let logs='';child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>logs+=b);
let browser;const reports=[];
try{for(let n=0;n<40;n++){try{if((await fetch(base+'/api/system/health')).ok)break;}catch{}if(child.exitCode!==null)throw new Error(logs);await new Promise(r=>setTimeout(r,200));}
 browser=await chromium.launch({channel:'chrome',headless:true});const original=(await(await fetch(base+'/api/routes')).json()).network;
 for(const [width,height]of [[1536,1024],[390,844]]){const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('.event-row').first().waitFor({state:'attached'});await clickGlobeControl(page,'routes-open');await page.locator('#routes-dialog').waitFor();assert.ok((await page.locator('#route-points input').count())>=4);await page.locator('#route-form [name="name"]').fill('Acceptance route '+width);await page.locator('#routes-save').click();await page.locator('#routes-status').filter({hasText:'Describe this revision'}).waitFor();await page.locator('#route-note').fill('Isolated browser acceptance '+width);await page.locator('#routes-save').click();await page.locator('#routes-dialog').waitFor({state:'hidden'});const saved=(await(await fetch(base+'/api/routes')).json()).network;assert.equal(saved.routes[0].name,'Acceptance route '+width);assert.notEqual(saved.version,original.version);
 await clickGlobeControl(page,'routes-open');await page.locator('#route-form [name="status"]').selectOption('source-traced');await page.locator('#route-preview').click();await page.locator('#routes-status').filter({hasText:'requires a source URL'}).waitFor();await page.locator('#route-form [name="status"]').selectOption('illustrative');await page.locator('#route-preview').click();await page.locator('.route-preview-bar').waitFor();await page.screenshot({path:`artifacts/route-network-${width}.png`});await page.locator('.route-preview-bar button').click();
 if(width>800){const count=await page.locator('.route-point').count();await page.locator('#route-pick').click();const globe=await page.locator('#globe').boundingBox();await page.mouse.click(globe.x+globe.width/2,globe.y+globe.height/2);await page.locator('#routes-dialog').waitFor();assert.equal(await page.locator('.route-point').count(),count+1);}
 const layout=await page.locator('#routes-dialog').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth,targets:[...e.querySelectorAll('button,input,select')].filter(el=>el.getBoundingClientRect().height&&el.type!=='checkbox').map(el=>el.getBoundingClientRect().height)}));assert.ok(layout.scroll<=layout.width+1,JSON.stringify(layout));assert.ok(layout.targets.every(h=>h>=44),JSON.stringify(layout));await page.screenshot({path:`artifacts/route-editor-${width}.png`});assert.deepEqual(errors,[]);reports.push({width,height,version:saved.version,layout,errors});await page.close();}
 const stale=await fetch(base+'/api/routes-save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({network:original,baseVersion:original.version,note:'Stale writer fixture'})});assert.equal(stale.status,400);const history=await(await fetch(base+'/api/routes?version='+original.version)).json();assert.deepEqual(history.network,original);const status=await(await fetch(base+'/api/status')).json();assert.equal(status.integrity.count,0);assert.equal(status.integrity.valid,true);
 writeFileSync('artifacts/routes-browser-report.json',JSON.stringify({reports,immutableOriginal:true,staleWriteRejected:true,forecastsIssued:0},null,2));console.log(JSON.stringify(reports));
}finally{await browser?.close();child.kill();await once(child,'exit').catch(()=>{});writeFileSync(dir+'/server.log',logs);}
