import {clickGlobeControl} from './browser-controls.mjs';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),reports=[];
for(const engine of ['chromium','webkit']){
  const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})}),page=await browser.newPage({viewport:{width:1536,height:1024}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});
  try{
    await page.goto('http://127.0.0.1:4318');await page.locator('.event-row').first().waitFor();
    await page.getByRole('button',{name:'Research lab',exact:true}).click();await page.locator('#replay-date').fill('2011-03-01T00:00');await page.locator('#load-replay').click();await page.locator('#timeline-time').filter({hasText:'Mar 01'}).waitFor();
    // Observe the real instance through the public class during ordinary UI actions; no product test hook.
    await page.evaluate(async()=>{const {Earth}=await import('/globe.js'),original=Earth.prototype.syncPresentation;Earth.prototype.syncPresentation=function(...args){const result=original.apply(this,args);window.renderInspection=this;return result;};});
    await page.locator('#xray-toggle').click();await page.locator('#xray-toggle').click();
    const inspect=()=>page.evaluate(()=>{const e=window.renderInspection,markers=[];e.scene.traverse(c=>{for(const m of c.material?(Array.isArray(c.material)?c.material:[c.material]):[]){const t=m.uniforms?.sprite?.value??m.map;if(m.uniforms?.sprite||t?.source===e.glow.source||t?.source===e.disc.source)markers.push({disc:t===e.disc,blending:m.blending});}});return {presentation:e.presentationEvidence(),events:e.events.map(v=>v.id),forecasts:e.forecasts.map(v=>v.key),camera:e.camera.position.toArray(),section:!!e.geology.section,clipPlanes:e.surfaceMaterial.clippingPlanes?.length??0,markers};});
    const before=await inspect();await page.locator('#scientific-toggle').click();const scientific=await inspect();
    assert.deepEqual(scientific.events,before.events);assert.deepEqual(scientific.forecasts,before.forecasts);assert.deepEqual(scientific.camera,before.camera);assert.equal(scientific.presentation.surfaceMaterial,'MeshBasicMaterial');
    for(const field of ['clouds','atmosphere','halo','stars','automaticCameraMotionAllowed'])assert.equal(scientific.presentation[field],false);
    assert.ok(scientific.markers.length>0);assert.ok(scientific.markers.every(m=>m.disc&&m.blending===1));assert.equal(await page.locator('#orbit-toggle').isDisabled(),true);
    await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:`artifacts/${engine}-scientific-earth.png`});
    await clickGlobeControl(page,'flight-open');assert.equal(await page.locator('#flight-pause').isDisabled(),true);await page.waitForTimeout(3400);assert.match(await page.locator('#flight-progress').innerText(),/Stop 1 of.*paused/);await page.locator('#flight-next').click();assert.match(await page.locator('#flight-progress').innerText(),/Stop 2 of/);await page.locator('#flight-stop').click();
    await page.locator('#xray-toggle').click();assert.equal((await inspect()).presentation.clouds,false);await clickGlobeControl(page,'section-toggle');let section=await inspect();assert.equal(section.section,true);assert.equal(section.clipPlanes,2);assert.ok(section.markers.every(m=>m.disc));
    await page.locator('#scientific-toggle').click();section=await inspect();assert.equal(section.presentation.surfaceMaterial,'MeshPhongMaterial');assert.equal(section.clipPlanes,2);assert.equal(section.presentation.clouds,false);assert.equal(section.presentation.halo,false);
    await page.locator('#scientific-toggle').click();await clickGlobeControl(page,'section-toggle');assert.equal((await inspect()).presentation.clouds,false);await page.locator('#xray-toggle').click();
    await clickGlobeControl(page,'figure-open');await page.locator('#figure-form button').click();await page.locator('.figure-downloads').waitFor({timeout:45000});
    for(const kind of ['json','svg','png']){const download=page.waitForEvent('download');await page.locator('#figure-'+kind).click();await(await download).saveAs(`artifacts/${engine}-scientific-figure.${kind}`);}
    const record=JSON.parse(readFileSync(`artifacts/${engine}-scientific-figure.json`,'utf8'));assert.equal(record.evidence.layers.presentation.style,'scientific');assert.equal(record.evidence.layers.presentation.surfaceMaterial,'MeshBasicMaterial');assert.equal(createHash('sha256').update(JSON.stringify(record.evidence)).digest('hex'),record.sha256);assert.match(readFileSync(`artifacts/${engine}-scientific-figure.svg`,'utf8'),/no cinematic effects/);
    await page.locator('#figure-close').click();const layouts=[];for(const [width,height] of [[320,740],[390,844],[844,390],[768,1024],[1366,768]]){await page.setViewportSize({width,height});await page.locator('#scientific-toggle').scrollIntoViewIfNeeded();const box=await page.locator('#scientific-toggle').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);if(width<=1024)assert.ok(box.height>=44);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);layouts.push({width,height,buttonHeight:box.height});}
    await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:`artifacts/${engine}-scientific-mobile-resized.png`});await page.reload();await page.locator('.event-row').first().waitFor({state:'attached'});assert.equal(await page.locator('#scientific-toggle').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#orbit-toggle').isDisabled(),true);
    const freshMobile=[];for(const [width,height]of [[320,740],[390,844],[844,390]]){const mobileContext=await browser.newContext({viewport:{width,height},storageState:await page.context().storageState()}),mobile=await mobileContext.newPage();await mobile.goto('http://127.0.0.1:4318');await mobile.locator('.event-row').first().waitFor({state:'attached'});await mobile.waitForFunction(async()=>{const {Earth}=await import('/globe.js');return !!Earth&&document.querySelector('#scientific-toggle').getAttribute('aria-pressed')==='true';});await mobile.waitForTimeout(2000);const png=await mobile.screenshot({path:`artifacts/${engine}-scientific-initial-${width}.png`});const blue=await mobile.evaluate(async source=>{const image=new Image();image.src=source;await image.decode();const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,c.width,c.height).data;let blue=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i+2]>80&&pixels[i+2]>pixels[i]*1.35&&pixels[i+2]>pixels[i+1]*1.1)blue++;return blue;},'data:image/png;base64,'+png.toString('base64'));assert.ok(blue>1000,JSON.stringify({engine,width,blue}));freshMobile.push({width,height,oceanPixels:blue});await mobileContext.close();}
    await page.locator('#scientific-toggle').click();assert.equal(await page.locator('#orbit-toggle').isDisabled(),false);assert.equal(await page.evaluate(()=>localStorage.getItem('seismosphere-render-style')),'cinematic');assert.deepEqual(errors,[]);
    reports.push({engine,events:before.events.length,unchangedData:true,solidMarkers:scientific.markers.length,cutawayTransitions:true,manualPath:true,persistence:true,figureHash:record.sha256,layouts,freshMobile,resizeRendering:engine==='webkit'?'Not accepted: installed runtime loses WebGL compositing after resizing; see scripts/webkit-resize-check.mjs':'Verified screenshot',errors});
  }finally{await browser.close();}
}
writeFileSync('artifacts/scientific-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
