import {clickGlobeControl} from './browser-controls.mjs';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {sectionCoordinates} from '../public/section-geometry.js';
const require=createRequire(import.meta.url),engines=require('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),reports=[];
for(const engine of ['chromium','webkit']){
  const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})}),page=await browser.newPage({viewport:{width:1536,height:1024},reducedMotion:'reduce'}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const download=async(id,file)=>{const d=page.waitForEvent('download');await page.locator(id).click();await(await d).saveAs(file);};
  try{
    await page.goto('http://127.0.0.1:4318');await page.locator('.event-row').first().waitFor();await page.getByRole('button',{name:'Research lab',exact:true}).click();await page.locator('#replay-date').fill('2011-03-15T00:00');await page.locator('#load-replay').click();await page.locator('#timeline-time').filter({hasText:'Mar 15'}).waitFor();
    await clickGlobeControl(page,'section-tools');for(const [name,value] of Object.entries({lat:38,lon:142,bearing:70,lengthKm:2500,halfWidthKm:200}))await page.locator(`#section-form [name="${name}"]`).fill(String(value));await page.locator('#section-form [name="follow"]').uncheck();await page.locator('#section-form button').click();await page.locator('#section-slab-load').click();await page.locator('#section-status').filter({hasText:'Published Slab2'}).waitFor({timeout:30000});
    for(const type of ['json','svg','csv'])await download('#section-'+type,`artifacts/${engine}-section.${type}`);
    const evidence=JSON.parse(readFileSync(`artifacts/${engine}-section.json`,'utf8'));assert.equal(evidence.frame.bearing,70);assert.equal(evidence.fixed,true);assert.equal(evidence.catalogContext.mode,'catalog-replay');assert.equal(evidence.catalogContext.filters.hours,720);assert.ok(evidence.events.length>20);assert.ok(evidence.slabContours.segments.length>0);for(const e of evidence.events)assert.equal(sectionCoordinates(e,evidence.frame).inside,true);assert.match(readFileSync(`artifacts/${engine}-section.svg`,'utf8'),/<metadata>/);assert.equal(readFileSync(`artifacts/${engine}-section.csv`,'utf8').split('\r\n').length,evidence.events.length+1);assert.match(readFileSync(`artifacts/${engine}-section.csv`,'utf8'),/time_epoch_ms.*depth_km/);
    await page.locator('#section-profile').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/${engine}-section-profile.png`});
    await page.locator('#section-event-select').selectOption({index:1});assert.equal(await page.locator('#section-dialog').evaluate(e=>e.open),false);assert.match(await page.locator('.geology-caption').textContent(),/70.0° bearing/);await page.getByRole('button',{name:'Close selection'}).click();await page.screenshot({path:`artifacts/${engine}-section-earth.png`});
    await clickGlobeControl(page,'figure-open');await page.locator('#figure-form button').click();await page.locator('.figure-downloads').waitFor({timeout:45000});await download('#figure-json',`artifacts/${engine}-section-figure.json`);const figure=JSON.parse(readFileSync(`artifacts/${engine}-section-figure.json`,'utf8'));assert.equal(figure.evidence.geologicalSection.frame.bearing,70);assert.equal(figure.evidence.render.actualPointEvents.length,evidence.events.length);assert.equal(createHash('sha256').update(JSON.stringify(figure.evidence)).digest('hex'),figure.sha256);await page.locator('#figure-close').click();
    await clickGlobeControl(page,'section-tools');await page.getByText('Set exact endpoints',{exact:true}).click();for(const [name,value] of Object.entries({aLat:-25,aLon:170,bLat:-15,bLon:-170}))await page.locator(`#section-endpoint-form [name="${name}"]`).fill(String(value));await page.locator('#section-endpoint-form button').click();await download('#section-json',`artifacts/${engine}-section-dateline.json`);const dateLine=JSON.parse(readFileSync(`artifacts/${engine}-section-dateline.json`,'utf8'));assert.ok(dateLine.frame.lengthKm<2500);assert.ok(Math.abs(dateLine.frame.start.lon-170)<1e-7);assert.ok(Math.abs(dateLine.frame.end.lon+170)<1e-7);
    await page.locator('#section-draw').click();await page.locator('.section-pickbar').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('#section-toggle').getAttribute('aria-pressed'),'true');
    await clickGlobeControl(page,'section-tools');await page.locator('#section-draw').click();const box=await page.locator('#globe').boundingBox();await page.mouse.click(box.x+box.width*.45,box.y+box.height*.42);await page.locator('.section-pickbar span').filter({hasText:'Pick B'}).waitFor();await page.mouse.click(box.x+box.width*.55,box.y+box.height*.45);await page.locator('#section-dialog').waitFor();await download('#section-json',`artifacts/${engine}-section-picked.json`);const picked=JSON.parse(readFileSync(`artifacts/${engine}-section-picked.json`,'utf8'));assert.ok(picked.frame.lengthKm>=50&&picked.frame.lengthKm<=18000);assert.equal(picked.fixed,true);
    const sizes=[];for(const width of [320,390,768]){await page.setViewportSize({width,height:844});await page.locator('#section-profile').scrollIntoViewIfNeeded();const layout=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,dialog:document.querySelector('#section-dialog').clientWidth,scroll:document.querySelector('#section-dialog').scrollWidth,closeTop:document.querySelector('#section-close').getBoundingClientRect().top}));assert.equal(layout.document,width);assert.ok(layout.scroll<=layout.dialog+1);assert.ok(layout.closeTop>=0);sizes.push(layout);}
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:`artifacts/${engine}-section-mobile-dialog.png`});await page.locator('#section-close').click();await page.screenshot({path:`artifacts/${engine}-section-mobile-earth.png`});await clickGlobeControl(page,'section-toggle');assert.equal(await page.locator('#depth-scale').isDisabled(),false);assert.deepEqual(errors,[]);reports.push({engine,events:evidence.events.length,slabSegments:evidence.slabContours.segments.length,obliqueProfile:true,dateline:true,picking:true,cancelRestored:true,figureEvidence:true,sizes,errors});
    await page.setViewportSize({width:844,height:390});await clickGlobeControl(page,'section-toggle');await page.waitForTimeout(500);const landscape=await page.evaluate(()=>({captionBottom:document.querySelector('.geology-caption').getBoundingClientRect().bottom,timelineTop:document.querySelector('.timeline').getBoundingClientRect().top,width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(landscape.captionBottom<=landscape.timelineTop+2,JSON.stringify(landscape));assert.equal(landscape.width,landscape.scroll);await page.screenshot({path:`artifacts/${engine}-section-landscape.png`});reports.at(-1).landscape=landscape;assert.deepEqual(errors,[]);
  }finally{await browser.close();}
}
writeFileSync('artifacts/section-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
