import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {parseReliefDods} from '../server/relief-data.mjs';
const root='https://www.ngdc.noaa.gov/thredds/dodsC/global/ETOPO2022/60s/60s_surface_elev_netcdf/ETOPO_2022_v1_60s_N90W180_surface.nc',url=root+'.dods?z[4:9:10795][4:9:21595]',sourceDir='data/geology/relief-source',digest=bytes=>createHash('sha256').update(bytes).digest('hex');
await mkdir(sourceDir,{recursive:true});await mkdir('public/assets',{recursive:true});let pin;try{pin=JSON.parse(await readFile('config/relief-source.json','utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
async function source(name,url,expected){let bytes;try{bytes=await readFile(sourceDir+'/'+name);}catch(e){if(e.code!=='ENOENT')throw e;const r=await fetch(url,{signal:AbortSignal.timeout(180000)});if(!r.ok)throw new Error('ETOPO HTTP '+r.status);const chunks=[];let length=0;for await(const part of r.body){length+=part.length;if(length>20000000)throw new Error('ETOPO subset exceeded 20 MB.');chunks.push(Buffer.from(part));}bytes=Buffer.concat(chunks);if(expected&&digest(bytes)!==expected)throw new Error('ETOPO source hash changed; review before updating the pinned model.');await writeFile(sourceDir+'/'+name+'.tmp',bytes);await rename(sourceDir+'/'+name+'.tmp',sourceDir+'/'+name);}if(expected&&digest(bytes)!==expected)throw new Error('Local ETOPO source integrity mismatch.');return bytes;}
const raw=await source('surface-9arcmin.dods',url,pin?.sourceSha256),attributes=await source('surface.das',root+'.das',pin?.attributesSha256);if(!attributes.includes('EGM2008')||!attributes.includes('String positive "up"')||!attributes.includes('String units "meters"'))throw new Error('ETOPO units or vertical datum not verified.');
const grid=parseReliefDods(raw);if(grid.width!==2400||grid.height!==1200||Math.abs(grid.latitudes[0]+89.925)>1e-9||Math.abs(grid.longitudes[0]+179.925)>1e-9)throw new Error('Unexpected ETOPO subset coverage.');
const metadata={schema:'seismosphere.relief.v1',name:'ETOPO 2022 v1 ice-surface / seafloor relief',source:url,sourceSha256:digest(raw),attributesSource:root+'.das',attributesSha256:digest(attributes),receivedAt:pin?.receivedAt??new Date().toISOString(),sha256:digest(grid.packed),width:grid.width,height:grid.height,latitudeStart:grid.latitudes[0],longitudeStart:grid.longitudes[0],latitudeStep:grid.latitudes[1]-grid.latitudes[0],longitudeStep:grid.longitudes[1]-grid.longitudes[0],encoding:'signed 16-bit little-endian metres; rows south to north, columns west to east',sourceSubset:{sourceResolutionArcSeconds:60,stride:9,startIndex:4,method:'One central source cell from each 9×9 block; point decimation, not a block mean.',displayGridArcMinutes:9},minimumM:grid.minimum,maximumM:grid.maximum,maximumQuantizationErrorM:grid.maximumQuantizationErrorM,horizontalDatum:'WGS84 geographic coordinates',verticalDatum:'EGM2008 geoid heights, positive up',citation:'NOAA National Centers for Environmental Information (2022), ETOPO 2022 15 Arc-Second Global Relief Model',doi:'https://doi.org/10.25921/fd45-gt74',homepage:'https://www.ncei.noaa.gov/products/etopo-global-relief-model',documentation:'https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO2022/docs/1.2%20ETOPO%202022%20User%20Guide.pdf',terms:'Freely available for private, academic and commercial uses; retain source citation.',limitations:['Static composite elevation model, not current terrain, tide or a survey at every cell.','The 60-arc-second source is itself downsampled from ETOPO 2022 15-arc-second grids.','The application retains central 9-arc-minute samples and rounds display elevations to the nearest metre; smaller islands, peaks and trenches may be missed.','EGM2008 heights are rendered radially on a mean-radius sphere, not converted to WGS84 ellipsoid heights.','Ice-surface variant: Greenland and Antarctic ice heights are shown, not sub-ice bedrock.']};
if(pin&&metadata.sha256!==pin.sha256)throw new Error('ETOPO derived grid differs from its pinned hash.');
await writeFile('public/assets/relief.bin.tmp',grid.packed);await rename('public/assets/relief.bin.tmp','public/assets/relief.bin');await writeFile('public/assets/relief.json',JSON.stringify(metadata));if(!pin)await writeFile('config/relief-source.json',JSON.stringify(metadata,null,2));console.log(JSON.stringify(metadata,null,2));
