import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {clickGlobeControl} from './browser-controls.mjs';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),reports=[];
for(const engine of ['chromium','webkit']){
 const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})}),page=await browser.newPage({viewport:{width:1366,height:900},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto('http://127.0.0.1:4318');await page.locator('.event-row').first().waitFor();
  const capability=await page.evaluate(()=>({audio:!!(window.AudioContext||window.webkitAudioContext),offline:!!(window.OfflineAudioContext||window.webkitOfflineAudioContext)}));
  if(!capability.audio||!capability.offline){
   assert.equal(await page.locator('#sound-toggle').isDisabled(),true);const layouts=[];
   for(const [width,height]of [[320,740],[390,844],[844,390],[768,1024]]){await page.setViewportSize({width,height});await clickGlobeControl(page,'sound-settings');assert.match(await page.locator('#sound-detail').innerText(),/Web Audio is unavailable/);assert.equal(await page.locator('#sound-sequence').isDisabled(),true);assert.equal(await page.locator('#sound-preview').isDisabled(),true);const sizing=await page.locator('#sound-dialog').evaluate(d=>({client:d.clientWidth,scroll:d.scrollWidth}));assert.ok(sizing.scroll<=sizing.client+1);await page.screenshot({path:`artifacts/${engine}-audio-unavailable-${width}.png`});await page.getByRole('button',{name:'Close audio settings',exact:true}).click();layouts.push({width,height,...sizing});}
   assert.deepEqual(errors,[]);reports.push({engine,capability,audioVerified:false,unavailableStateVerified:true,layouts,errors});continue;
  }
  const signals=await page.evaluate(async()=>{
   const {toneParameters,createTone,updateListener}=await import('/sonification.js'),THREE=await import('three');
   async function render({lon=0,mag=6,depth=0,age=0,z=3,model='equalpower',legacy=false}={}){
    const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext,ctx=new Offline(2,72000,48000),camera=new THREE.PerspectiveCamera();camera.position.set(0,0,z);camera.lookAt(0,0,0);if(legacy){Object.defineProperty(ctx.listener,'positionX',{value:undefined});const original=ctx.createPanner.bind(ctx);ctx.createPanner=()=>{const p=original();Object.defineProperty(p,'positionX',{value:undefined});return p;};}updateListener(ctx,camera);const p=toneParameters({id:'test',lat:0,lon,mag,depth,time:0},age*86400000);createTone(ctx,ctx.destination,p,model);const buffer=await ctx.startRendering(),l=buffer.getChannelData(0),r=buffer.getChannelData(1);let left=0,right=0,crossings=0,peak=0,tail=0;
    for(let i=4800;i<57600;i++){left+=l[i]**2;right+=r[i]**2;peak=Math.max(peak,Math.abs(l[i]),Math.abs(r[i]));if(i<14400&&(l[i]+r[i])>0&&(l[i-1]+r[i-1])<=0)crossings++;}for(let i=65000;i<72000;i++)tail=Math.max(tail,Math.abs(l[i]),Math.abs(r[i]));
    return {left,right,peak,tail,frequency:crossings/.2,parameters:p};
   }
   return {right:await render(),left:await render({lon:180}),reversed:await render({z:-3}),far:await render({z:6}),old:await render({age:8}),deep:await render({depth:700}),loud:await render({mag:8}),hrtf:await render({model:'HRTF'}),legacy:await render({legacy:true})};
  });
  assert.ok(signals.right.right>signals.right.left*1.2);assert.ok(signals.left.left>signals.left.right*1.2);assert.ok(signals.reversed.left>signals.reversed.right*1.2);assert.ok(signals.far.left+signals.far.right<signals.right.left+signals.right.right);assert.ok(signals.old.peak<signals.right.peak);assert.ok(signals.loud.peak>signals.right.peak);assert.ok(Math.abs(signals.right.frequency-990)<10);assert.ok(Math.abs(signals.deep.frequency-110)<10);assert.ok(signals.hrtf.peak>0);assert.ok(signals.hrtf.right>signals.hrtf.left*1.2);assert.equal(signals.right.tail,0);assert.ok(signals.legacy.right>signals.legacy.left*1.2);assert.ok(Math.abs(signals.legacy.frequency-990)<10);
  await page.evaluate(async()=>{const {Earth}=await import('/globe.js'),original=Earth.prototype.syncPresentation;Earth.prototype.syncPresentation=function(...a){const result=original.apply(this,a);window.audioEarth=this;return result;};});await page.locator('#scientific-toggle').click();
  assert.equal(await page.locator('#sound-toggle').getAttribute('aria-pressed'),'false');await clickGlobeControl(page,'sound-settings');await page.locator('#sound-dialog').waitFor();assert.match(await page.locator('#sound-dialog').innerText(),/not recorded ground motion/);assert.equal(await page.locator('#sound-preview').isDisabled(),true);await page.getByRole('button',{name:'Close audio settings',exact:true}).click();
  await page.locator('.event-row').first().click();await page.getByRole('button',{name:'Close selection',exact:true}).click();await clickGlobeControl(page,'sound-toggle');await page.waitForFunction(()=>window.audioEarth.sonification.evidence().last!==null);let evidence=await page.evaluate(()=>window.audioEarth.sonification.evidence());assert.equal(evidence.enabled,true);assert.equal(evidence.last.panningModel,'HRTF');assert.ok(evidence.last.ageDays>=0);
  await clickGlobeControl(page,'sound-settings');await page.locator('#sound-volume').fill('0');await page.locator('#sound-preview').click();await page.waitForFunction(()=>window.audioEarth.sonification.evidence().last.volume===0);await page.locator('#sound-volume').fill('35');await page.locator('#sound-spatial').selectOption('equalpower');await page.locator('#sound-sequence').click();await page.locator('.sonification-panel').waitFor();await page.waitForFunction(()=>window.audioEarth.sonification.evidence().sequence?.index>=2);evidence=await page.evaluate(()=>window.audioEarth.sonification.evidence());assert.equal(evidence.sequence.total,await page.evaluate(()=>window.audioEarth.events.length));assert.equal(evidence.last.panningModel,'equalpower');
  await page.locator('[data-filter="deep"]').click();await page.locator('.sonification-panel').waitFor({state:'hidden'});await page.waitForFunction(()=>window.audioEarth.sonification.evidence().activeVoices===0);assert.equal(await page.evaluate(()=>window.audioEarth.sonification.evidence().sequence),null);
  await clickGlobeControl(page,'section-toggle');await clickGlobeControl(page,'sound-settings');await page.locator('#sound-sequence').click();await page.locator('.sonification-panel').waitFor();assert.equal(await page.evaluate(()=>window.audioEarth.sonification.evidence().sequence.total),await page.evaluate(()=>window.audioEarth.geology.sectionEvents.length));await clickGlobeControl(page,'section-toggle');await page.locator('.sonification-panel').waitFor({state:'hidden'});
  await clickGlobeControl(page,'sound-settings');await page.locator('#sound-sequence').click();await page.locator('.sonification-panel').waitFor();await page.getByRole('button',{name:'Research lab',exact:true}).click();await page.locator('#replay-date').fill('2011-03-01T00:00');await page.locator('#load-replay').click();await page.locator('#timeline-time').filter({hasText:'Mar 01'}).waitFor();assert.equal(await page.evaluate(()=>window.audioEarth.sonification.evidence().last),null);await page.locator('.sonification-panel').waitFor({state:'hidden'});await page.waitForFunction(()=>window.audioEarth.sonification.evidence().activeVoices===0);
  const layouts=[];for(const [width,height]of [[320,740],[390,844],[844,390],[768,1024]]){await page.setViewportSize({width,height});await clickGlobeControl(page,'sound-settings');await page.locator('#sound-sequence').scrollIntoViewIfNeeded();const size=await page.locator('#sound-dialog').evaluate(d=>({client:d.clientWidth,scroll:d.scrollWidth,close:d.querySelector('.icon-btn').getBoundingClientRect().top}));assert.ok(size.scroll<=size.client+1);assert.ok(size.close>=0);await page.screenshot({path:`artifacts/${engine}-audio-${width}.png`});await page.getByRole('button',{name:'Close audio settings',exact:true}).click();layouts.push({width,height,...size});}
  await clickGlobeControl(page,'sound-settings');await page.locator('#sound-sequence').click();await page.locator('.sonification-panel').waitFor();await page.screenshot({path:`artifacts/${engine}-audio-sequence.png`});await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await page.locator('#sound-toggle').getAttribute('aria-pressed'),'false');await page.locator('.sonification-panel').waitFor({state:'hidden'});
  await clickGlobeControl(page,'sound-settings');await page.locator('#sound-mute').click();assert.equal(await page.locator('#sound-toggle').getAttribute('aria-pressed'),'false');await page.getByRole('button',{name:'Close audio settings',exact:true}).click();assert.deepEqual(errors,[]);reports.push({engine,capability,audioVerified:true,signals,sequenceEvents:evidence.sequence.total,cutoffFilterCancellation:true,sectionEvents:true,controlledVisibilityMute:true,mute:true,layouts,errors});
 }finally{await browser.close();}
}
writeFileSync('artifacts/sonification-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports.map(({signals,...report})=>report)));
