import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {clickGlobeControl} from './browser-controls.mjs';
import {hash} from '../server/store.mjs';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),root='http://127.0.0.1:4318',{source}=JSON.parse(readFileSync('artifacts/chromium-spectrum.json','utf8')),reports=[];
for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height]of [[1366,900],[320,740],[390,844],[844,390]]){
 const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root);await page.locator('.event-row').first().waitFor({state:'attached'});await clickGlobeControl(page,'instruments-open');await page.locator(`#station-history option[value="${source.query.stationRecordId}"]`).waitFor({state:'attached'});await page.locator('#station-history').selectOption(source.query.stationRecordId);await page.locator('#station-search').fill('IU.ANMO.00');await page.locator('.station-row').click();await page.locator('#waveform-form button').click();await page.locator('#spectrum-form').waitFor();await page.locator('#waveform-join').uncheck();assert.equal(await page.locator('[name="frameSamples"]').isDisabled(),true);await page.locator('[name="timeFrequency"]').check();await page.locator('[name="frameSamples"]').fill('256');await page.locator('[name="hopSamples"]').fill('128');
 const pending=page.waitForResponse(r=>r.url().endsWith('/api/waveform-spectrum'));await page.locator('#spectrum-form button').click();const response=await pending,result=await response.json();assert.equal(response.status(),200,JSON.stringify(result));await page.locator('#spectrogram-chart').waitFor();assert.equal(result.spectrogram.summary.frames,14);assert.equal(result.spectrogram.summary.frequencyBins,129);assert.equal(result.spectrogram.summary.unusedTailSamples,100);
 await page.locator('#spectrogram-frame').fill('2');await page.locator('#spectrogram-bin').fill('3');assert.match(await page.locator('#spectrogram-cell').innerText(),/Frame 2/);assert.ok((await page.locator('#spectrogram-cell').innerText()).includes(result.spectrogram.psdCounts2PerHz[1][3].toPrecision(7)));
 await page.locator('#spectrogram-chart').scrollIntoViewIfNeeded();const box=await page.locator('#spectrogram-chart').boundingBox(),svgWidth=await page.locator('#spectrogram-chart').evaluate(e=>e.viewBox.baseVal.width);await page.locator('#spectrogram-chart').click({position:{x:(58+(svgWidth-74)*.8)/svgWidth*box.width,y:130/340*box.height}});assert.equal(await page.locator('#spectrogram-frame').inputValue(),'12');
 if(width===1366){const download=async(selector,suffix)=>{const pending=page.waitForEvent('download');await page.locator(selector).click();const file=`artifacts/${engine}-spectrogram.${suffix}`;await(await pending).saveAs(file);return readFileSync(file,'utf8');};const csv=(await download('#spectrogram-csv','csv')).trim().split(/\r?\n/);assert.equal(csv.length,14*129+1);let row=1;for(let i=0;i<14;i++)for(let j=0;j<129;j++)assert.deepEqual(csv[row++].split(',').map(Number),[i,result.spectrogram.frameStartIndices[i],result.spectrogram.frameCenterSeconds[i],result.spectrogram.frequencyHz[j],result.spectrogram.psdCounts2PerHz[i][j]]);
  const svg=await download('#spectrogram-svg','svg'),metadata=await page.evaluate(s=>JSON.parse(new DOMParser().parseFromString(s,'image/svg+xml').querySelector('metadata').textContent),svg),{id,...body}=metadata;assert.equal(hash(body),id);assert.equal(id,result.id);assert.ok(svg.includes('data:image/png;base64,'));const exported=JSON.parse(await download('#spectrum-result a','json'));assert.equal(exported.integrity.recordValid,true);assert.equal(exported.integrity.sourceValid,true);assert.equal(exported.source.id,source.id);
 }
 await page.locator('#spectrogram-chart').scrollIntoViewIfNeeded();await page.locator('#spectrogram-chart').evaluate(e=>{const d=e.closest('dialog');d.scrollTop+=e.getBoundingClientRect().top-d.getBoundingClientRect().top-d.querySelector('.dialog-heading').getBoundingClientRect().height-20;});const layout=await page.locator('#instruments-dialog').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert.ok(layout.scroll<=layout.width+1,JSON.stringify(layout));await page.screenshot({path:`artifacts/${engine}-spectrogram-${width}.png`});assert.deepEqual(errors,[]);reports.push({engine,width,height,id:result.id,summary:result.spectrogram.summary,layout,cellInspection:true,errors});await page.close();
 }}finally{await browser.close();}}
writeFileSync('artifacts/spectrogram-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports.map(({engine,width,id,errors})=>({engine,width,id,errors}))));
