import {createRequire} from 'node:module';
import {writeFileSync,readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {clickGlobeControl} from './browser-controls.mjs';
import {hash} from '../server/store.mjs';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),root='http://127.0.0.1:4318',reports=[];
const {records}=await(await fetch(root+'/api/instruments')).json(),saved=records.find(r=>r.kind==='waveform'&&r.query.station==='ANMO'&&r.count===2400);assert.ok(saved);const {record:source}=await(await fetch(root+'/api/instrument-export?id='+saved.id)).json();
for(const engine of ['chromium','webkit']){const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});try{for(const [width,height]of [[1366,900],[320,740],[390,844],[844,390]]){
 const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(root);await page.locator('.event-row').first().waitFor({state:'attached'});await clickGlobeControl(page,'instruments-open');await page.locator(`#station-history option[value="${source.query.stationRecordId}"]`).waitFor({state:'attached'});await page.locator('#station-history').selectOption(source.query.stationRecordId);await page.locator('#station-search').fill('IU.ANMO.00');await page.locator('.station-row').click();await page.locator('#waveform-form button').click();await page.locator('#spectrum-form').waitFor();await page.locator('#waveform-join').uncheck();
 assert.equal(await page.locator('#spectrum-form [name="runIndex"] option').count(),2);const pending=page.waitForResponse(r=>r.url().endsWith('/api/waveform-spectrum'));await page.locator('#spectrum-form button').click();const response=await pending,result=await response.json();assert.equal(response.status(),200,JSON.stringify(result));await page.locator('#spectrum-result svg').waitFor();assert.equal(result.source.id,source.id);assert.equal(result.summary.sampleRateHz,20);assert.equal(result.summary.samples,source.segments[0].samples.length);assert.equal(result.selection.firstSampleUs,source.segments[0].samples[0][0]);assert.equal(result.frequencyHz.at(-1),10);assert.ok(result.summary.peakNonzeroBinHz>0);
 await page.locator(`#spectrum-history option[value="${result.id}"]`).waitFor({state:'attached'});await page.locator('#spectrum-history').selectOption(result.id);await page.locator('#spectrum-result').filter({hasText:'samples at 20 Hz'}).waitFor();
 if(width===1366){
  const download=async(selector,suffix)=>{const pending=page.waitForEvent('download');await page.locator(selector).click();const file=`artifacts/${engine}-spectrum.${suffix}`;await(await pending).saveAs(file);return readFileSync(file,'utf8');};
  const json=JSON.parse(await download('#spectrum-result a','json')),{id,...body}=json.record;assert.equal(hash(body),id);assert.equal(json.integrity.sourceRecordValid,true);assert.equal(json.integrity.sourceValid,true);assert.equal(json.source.id,source.id);
  const csv=(await download('#spectrum-csv','csv')).trim().split(/\r?\n/);assert.equal(csv.length,result.frequencyHz.length+1);const rows=csv.slice(1).map(line=>line.split(',').map(Number));assert.deepEqual(rows.map(r=>r[0]),result.frequencyHz);assert.deepEqual(rows.map(r=>r[1]),result.psdCounts2PerHz);
  const svg=await download('#spectrum-svg','svg'),meta=await page.evaluate(svg=>JSON.parse(new DOMParser().parseFromString(svg,'image/svg+xml').querySelector('metadata').textContent),svg);assert.equal(meta.id,result.id);assert.equal(hash(Object.fromEntries(Object.entries(meta).filter(([k])=>k!=='id'))),id);
 }
 await page.locator('#spectrum-result svg').scrollIntoViewIfNeeded();await page.locator('#spectrum-result svg').evaluate(e=>{const d=e.closest('dialog'),h=d.querySelector('.dialog-heading');d.scrollTop+=e.getBoundingClientRect().top-d.getBoundingClientRect().top-h.getBoundingClientRect().height-24;});const layout=await page.locator('#instruments-dialog').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth,controls:[...e.querySelectorAll('#spectrum-panel button,#spectrum-panel select,#spectrum-panel input')].filter(e=>e.getClientRects().length).map(e=>(e.type==='checkbox'?e.closest('label'):e).getBoundingClientRect().height)}));assert.ok(layout.scroll<=layout.width+1,JSON.stringify(layout));assert.ok(layout.controls.every(h=>h>=44));await page.screenshot({path:`artifacts/${engine}-spectrum-${width}.png`});
 // Invalid windows must not save new analyses or change a reviewed result.
 const bad=await page.request.post(root+'/api/waveform-spectrum',{data:{...result.query,asOf:Date.now(),mode:'catalog-replay',samples:result.summary.samples+1}});assert.equal(bad.status(),400);
 let release;await page.route('**/api/waveform-spectrum',async route=>{const reply=await route.fetch();await new Promise(resolve=>release=resolve);await route.fulfill({response:reply});});const sent=page.waitForRequest(r=>r.url().endsWith('/api/waveform-spectrum'));await page.locator('#spectrum-form button').click();await sent;await page.locator('.station-row').click();const returned=page.waitForResponse(r=>r.url().endsWith('/api/waveform-spectrum'));while(!release)await new Promise(resolve=>setTimeout(resolve,20));release();await returned;assert.equal(await page.locator('#spectrum-panel').isVisible(),false);assert.equal(await page.locator('#spectrum-result svg').count(),0);
 assert.deepEqual(errors,[]);reports.push({engine,width,height,id:result.id,summary:result.summary,layout,lateChannelResponseWithheld:true,errors});await page.close();
 }}finally{await browser.close();}}
const strict=await fetch(root+'/api/waveform-spectrum',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(readFileSync('artifacts/chromium-spectrum.json','utf8')).record.query,asOf:source.query.end,mode:'strict'})});assert.equal(strict.status,400);
writeFileSync('artifacts/spectrum-browser-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
