import {clickGlobeControl} from './browser-controls.mjs';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const engines=createRequire(import.meta.url)('C:/Users/blocp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),root='http://127.0.0.1:4318',reports=[],sha=v=>createHash('sha256').update(v).digest('hex');
const raw=await(await fetch(root+'/assets/gvp-volcanoes.json')).text(),dataset=JSON.parse(raw),source=await(await fetch(root+'/assets/gvp-volcanoes-source.json')).text();assert.equal(sha(source),dataset.provenance.receipt.sha256);assert.equal(sha(JSON.stringify(dataset.volcanoes)),dataset.provenance.normalizedSha256);
for(const engine of ['chromium','webkit']){
  const browser=await engines[engine].launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});
  try{for(const [width,height]of (process.argv.includes('--desktop-only')?[[1536,1024]]:[[1536,1024],[390,844],[320,740],[844,390]])){
    const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});await page.goto(root);await page.locator('.event-row').first().waitFor({state:'attached'});
    await page.evaluate(async()=>{const {Volcanoes}=await import('/volcanoes.js'),original=Volcanoes.prototype.update;Volcanoes.prototype.update=function(...args){const value=original.apply(this,args);window.volcanoInspection=this;return value;};});
    await clickGlobeControl(page,'volcanoes-open');await page.locator('#volcano-status').filter({hasText:'1,214'}).waitFor();assert.equal(await page.locator('.volcano-row').count(),100);if(width===1536){await page.locator('#volcano-visible').check();assert.equal(await page.evaluate(()=>window.volcanoInspection.group.children[0].geometry.attributes.position.count),1214);await page.getByRole('button',{name:'Close volcanoes',exact:true}).click();await page.screenshot({path:`artifacts/${engine}-volcano-global.png`});await clickGlobeControl(page,'volcanoes-open');}await page.locator('#volcano-more').click();assert.equal(await page.locator('.volcano-row').count(),200);
    await page.locator('#volcano-search').fill('no such volcano qqq');assert.equal(await page.locator('.volcano-row').count(),0);await page.locator('#volcano-search').fill('Axial Seamount');await page.locator('[data-volcano="GVP:331021"]').click();assert.match(await page.locator('#volcano-detail').innerText(),/-1410 m relative to sea level/);assert.match(await page.locator('#volcano-detail').innerText(),/2015 CE/);
    await page.locator('#volcano-search').fill('Kilauea');await page.locator('[data-volcano="GVP:332010"]').click();assert.match(await page.locator('#volcano-detail').innerText(),/1222 m relative to sea level/);assert.match(await page.locator('#volcano-detail').innerText(),/2026 CE/);assert.equal(await page.locator('#volcano-dialog').evaluate(d=>d.scrollWidth>d.clientWidth+1),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#volcano-detail').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/${engine}-volcano-dialog-${width}.png`});
    const download=page.waitForEvent('download');await page.getByRole('link',{name:'Source record + provenance'}).click();const filename=`artifacts/${engine}-volcano-source-${width}.json`;await(await download).saveAs(filename);const exported=JSON.parse(readFileSync(filename,'utf8'));assert.equal(exported.volcano.number,332010);assert.equal(exported.datasetSha256,sha(raw));assert.equal(exported.provenance.receipt.sha256,sha(source));
    await page.locator('#volcano-focus').click();await page.waitForTimeout(1800);const overlay=await page.evaluate(()=>{const v=window.volcanoInspection;return {visible:v.group.visible,points:v.group.children[0].geometry.attributes.position.count,evidence:v.evidence(),triangle:!!v.group.children[0].material.map};});assert.equal(overlay.visible,true);assert.equal(overlay.points,1);assert.equal(overlay.triangle,true);assert.deepEqual(overlay.evidence.displayedIds,['GVP:332010']);await page.screenshot({path:`artifacts/${engine}-volcano-earth-${width}.png`});
    if(width===1536){
      const pick=await page.evaluate(()=>{const v=window.volcanoInspection,position=v.group.children[0].geometry.attributes.position,c=v.earth.camera,p=c.position.clone().set(position.getX(0),position.getY(0),position.getZ(0)).project(c),r=v.earth.renderer.domElement.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};});await page.mouse.click(pick.x,pick.y);await page.locator('#volcano-dialog').waitFor();assert.match(await page.locator('#volcano-detail h3').innerText(),/Kilauea/);await page.getByRole('button',{name:'Close volcanoes',exact:true}).click();
      await clickGlobeControl(page,'section-toggle');assert.deepEqual(await page.evaluate(()=>window.volcanoInspection.group.children.map(c=>c.material.clippingPlanes.length)),[2]);await page.locator('#scientific-toggle').click();assert.equal(await page.evaluate(()=>window.volcanoInspection.group.children[0].material.map===window.volcanoInspection.texture),true);await clickGlobeControl(page,'section-toggle');
      await clickGlobeControl(page,'figure-open');await page.locator('#figure-form button').click();await page.locator('.figure-downloads').waitFor({timeout:45000});for(const kind of ['json','svg']){const download=page.waitForEvent('download');await page.locator('#figure-'+kind).click();await(await download).saveAs(`artifacts/${engine}-volcano-figure.${kind}`);}const figure=JSON.parse(readFileSync(`artifacts/${engine}-volcano-figure.json`,'utf8'));assert.equal(sha(JSON.stringify(figure.evidence)),figure.sha256);assert.equal(figure.evidence.volcanoReference.selected.number,332010);assert.equal(figure.evidence.volcanoReference.symbolRadiusEarthUnits,1.015);assert.equal(figure.evidence.volcanoReference.displayedPoints[0].name,'Kilauea');assert.ok(figure.evidence.credits.some(c=>c.url==='https://volcano.si.edu/'));assert.match(readFileSync(`artifacts/${engine}-volcano-figure.svg`,'utf8'),/GVP volcano reference/);await page.locator('#figure-close').click();
      await clickGlobeControl(page,'volcanoes-open');await page.locator('#volcano-near-camera').click();assert.ok(await page.locator('.volcano-row').count()>0);assert.match(await page.locator('#volcano-query').innerText(),/500 km/);await page.getByRole('button',{name:'Close volcanoes',exact:true}).click();
      await page.getByRole('button',{name:'Research lab',exact:true}).click();await page.locator('#replay-date').fill('2011-03-01T00:00');await page.locator('#load-replay').click();await page.locator('#timeline-time').filter({hasText:'Mar 01'}).waitFor();await clickGlobeControl(page,'volcanoes-open');assert.equal(await page.evaluate(()=>window.volcanoInspection.group.visible),true);assert.match(await page.locator('#volcano-status').innerText(),/5.4.0/);
    }
    assert.deepEqual(errors,[]);reports.push({engine,width,height,sourceHash:exported.provenance.receipt.sha256,visiblePoints:overlay.points,errors});await page.close();
  }}finally{await browser.close();}
}
writeFileSync(process.argv.includes('--desktop-only')?'artifacts/volcano-desktop-report.json':'artifacts/volcano-report.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
